import {validateAssetQuality,type AssetQualityRecord} from './assetQuality';
import {validateModelAsset,summarizeAsset,type ModelAssetVersion,type ModelAssetSummary} from './modelAssets';
const DB='chat3d.model-assets.v1';
function open():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{if(typeof indexedDB==='undefined'){reject(Error('浏览器不支持资产存储'));return;}const request=indexedDB.open(DB,2);request.onupgradeneeded=()=>{for(const [name,keyPath] of [['items','id'],['versions',['id','version']],['reviews',['assetId','version']]] as const){if(!request.result.objectStoreNames.contains(name))request.result.createObjectStore(name,{keyPath:typeof keyPath==='string'?keyPath:[...keyPath]});}};request.onsuccess=()=>{const db=request.result;db.onversionchange=()=>db.close();resolve(db);};request.onerror=()=>reject(Error('资产库打开失败'));request.onblocked=()=>reject(Error('资产库被旧页面占用，请关闭旧页面后重试'));});}
export async function listModelAssets():Promise<ModelAssetSummary[]>{const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('items'),r=tx.objectStore('items').getAll();tx.oncomplete=()=>{db.close();resolve((r.result as ModelAssetSummary[]).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));};tx.onabort=()=>{db.close();reject(Error('资产列表读取失败'));};});}
export async function readModelAsset(id:string,version:number):Promise<ModelAssetVersion>{const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('versions'),r=tx.objectStore('versions').get([id,version]);tx.oncomplete=()=>{db.close();try{if(!r.result)throw Error('未找到该资产版本');validateModelAsset(r.result);resolve(r.result);}catch(e){reject(e);}};tx.onabort=()=>{db.close();reject(Error('资产读取失败'));};});}
export async function saveModelAsset(asset:ModelAssetVersion,expectedVersion=0):Promise<void>{validateModelAsset(asset);if(asset.version!==expectedVersion+1)throw Error('新版本必须连续递增');const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction(['items','versions'],'readwrite'),items=tx.objectStore('items'),r=items.get(asset.id);let conflict=false;r.onsuccess=()=>{if((r.result?.version??0)!==expectedVersion){conflict=true;tx.abort();return;}tx.objectStore('versions').add(structuredClone(asset));items.put(summarizeAsset(asset));};tx.oncomplete=()=>{db.close();resolve();};tx.onabort=()=>{db.close();reject(Error(conflict?'资产已被其他页面更新，请刷新后另存新版本':'资产保存失败，可能存储空间不足；原有版本未改动'));};tx.onerror=()=>{};});}

export async function readAssetQuality(id:string,version:number):Promise<AssetQualityRecord|undefined>{const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('reviews'),r=tx.objectStore('reviews').get([id,version]);tx.oncomplete=()=>{db.close();resolve(r.result);};tx.onabort=()=>{db.close();reject(Error('验收记录读取失败'));};});}
export async function saveAssetQuality(record:AssetQualityRecord):Promise<void>{const a=await readModelAsset(record.assetId,record.version);await validateAssetQuality(a,record);const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('reviews','readwrite');tx.objectStore('reviews').put(structuredClone(record));tx.oncomplete=()=>{db.close();resolve();};tx.onabort=()=>{db.close();reject(Error('验收记录保存失败'));};});}
export interface AssetLibraryBackup {format:'chat3d-asset-library';schemaVersion:1;createdAt:string;versions:ModelAssetVersion[];reviews?:AssetQualityRecord[]}
export async function exportAssetLibrary():Promise<AssetLibraryBackup>{const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction(['versions','reviews']),r=tx.objectStore('versions').getAll(),reviews=tx.objectStore('reviews').getAll();tx.oncomplete=()=>{db.close();resolve({format:'chat3d-asset-library',schemaVersion:1,createdAt:new Date().toISOString(),versions:r.result,reviews:reviews.result});};tx.onabort=()=>{db.close();reject(Error('资产备份读取失败'));};});}
export async function importAssetLibrary(text:string):Promise<number>{
 if(new TextEncoder().encode(text).length>50*1024*1024)throw Error('资产库备份超过50MB');
 const b=JSON.parse(text) as AssetLibraryBackup;if(b?.format!=='chat3d-asset-library'||b.schemaVersion!==1||!Array.isArray(b.versions)||!b.versions.length||b.versions.length>200)throw Error('资产库备份格式或数量无效');
 const mapping=new Map<string,string>(),seen=new Set<string>(),grouped=new Map<string,number[]>();
 for(const a of b.versions){validateModelAsset(a);const key=a.id+':'+a.version;if(seen.has(key))throw Error('资产版本重复');seen.add(key);const rows=grouped.get(a.id)??[];rows.push(a.version);grouped.set(a.id,rows);if(!mapping.has(a.id))mapping.set(a.id,crypto.randomUUID());}
 for(const versions of grouped.values())if(versions.sort((a,b)=>a-b).some((v,i)=>v!==i+1))throw Error('备份必须包含从v1开始的连续版本');
 const importedReviews:AssetQualityRecord[]=[];if(b.reviews!==undefined){if(!Array.isArray(b.reviews)||b.reviews.length>200)throw Error('备份验收记录数量无效');const keys=new Set<string>();for(const r of b.reviews){const a=b.versions.find(a=>a.id===r.assetId&&a.version===r.version);if(!a||keys.has(r.assetId+':'+r.version))throw Error('备份验收记录引用无效');keys.add(r.assetId+':'+r.version);await validateAssetQuality(a,r);importedReviews.push({...structuredClone(r),assetId:mapping.get(r.assetId)!,origin:'imported'});}}
 const values=b.versions.map(a=>({...structuredClone(a),id:mapping.get(a.id)!}));const latest=new Map<string,ModelAssetVersion>();for(const a of values)if(!latest.has(a.id)||latest.get(a.id)!.version<a.version)latest.set(a.id,a);
 const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction(['items','versions','reviews'],'readwrite');for(const r of importedReviews)tx.objectStore('reviews').add(r);for(const a of values)tx.objectStore('versions').add(a);for(const a of latest.values())tx.objectStore('items').add(summarizeAsset(a));tx.oncomplete=()=>{db.close();resolve(latest.size);};tx.onabort=()=>{db.close();reject(Error('备份恢复失败，未写入部分资产'));};});
}
