import type {SceneDocument,Vec3} from './types';
import {applyBatch,type Command} from './commands';
import {existingPoseCommands} from './preservedPose';
import {rigWorldAxis,rigWorldPoint,validatePoseRig} from './poseRig';
export function getPoseRig(doc:SceneDocument,assemblyId:string){const nodes=doc.nodes.filter(n=>(n.assemblyId??n.id)===assemblyId),hosts=nodes.filter(n=>n.poseRig);if(hosts.length!==1)throw Error(hosts.length?'组件关节记录重复，请重新标定':'此组件尚未标定关节和抓握点');const rig=hosts[0].poseRig!;validatePoseRig(rig,nodes);return {nodes,rig,hostId:hosts[0].id};}
export function poseRigContext(doc:SceneDocument,assemblyId:string){try{const {nodes,rig}=getPoseRig(doc,assemblyId);return {assemblyId,valid:true,joints:rig.joints.map(j=>({key:j.key,name:j.name,memberIds:j.memberIds,pivot:rigWorldPoint(nodes.find(n=>n.id===j.anchorNodeId)!,j.pivot),axis:rigWorldAxis(nodes.find(n=>n.id===j.anchorNodeId)!,j.axis)})),anchors:rig.anchors.map(a=>({key:a.key,name:a.name,kind:a.kind,nodeId:a.nodeId,point:rigWorldPoint(nodes.find(n=>n.id===a.nodeId)!,a.point)})),limitations:'用户或模型标定的刚体关节点，不是自动骨骼/碰撞验收。'};}catch(e){return {assemblyId,valid:false,reason:(e as Error).message};}}
export interface RigContact {sourceKey:string;targetAssemblyId:string;targetKey:string;tolerance:number}
export function poseWithRigCommands(doc:SceneDocument,assemblyId:string,steps:{jointKey:string;angle:number}[],contacts:RigContact[]=[]){
 if(!Array.isArray(steps)||!steps.length||steps.length>12||contacts.length>16)throw Error('一次需要1–12个关节步骤，最多16项接触检查');let working=doc;const commands:Command[]=[];
 for(const step of steps){const {rig,nodes}=getPoseRig(working,assemblyId),joint=rig.joints.find(j=>j.key===step.jointKey);if(!joint)throw Error('已保存关节不存在');const anchor=nodes.find(n=>n.id===joint.anchorNodeId)!;const batch=existingPoseCommands(working,assemblyId,[{nodeIds:joint.memberIds,pivot:rigWorldPoint(anchor,joint.pivot),axis:rigWorldAxis(anchor,joint.axis),angle:step.angle}]);const result=applyBatch(working,{operations:batch});if(result.errors.length)throw result.errors[0];working=result.doc;commands.push(...batch);}
 const checks=contacts.map(c=>{if(!Number.isFinite(c.tolerance)||c.tolerance<=0||c.tolerance>.5)throw Error('接触容差应大于0且不超过0.5米');const source=getPoseRig(working,assemblyId),target=getPoseRig(working,c.targetAssemblyId),a=source.rig.anchors.find(a=>a.key===c.sourceKey),b=target.rig.anchors.find(a=>a.key===c.targetKey);if(!a||!b)throw Error('接触检查引用了不存在的抓握/接触点');const p=rigWorldPoint(source.nodes.find(n=>n.id===a.nodeId)!,a.point),q=rigWorldPoint(target.nodes.find(n=>n.id===b.nodeId)!,b.point),distance=Math.hypot(...p.map((v,i)=>v-q[i]) as Vec3);return {...c,distance,pass:distance<=c.tolerance};});
 if(checks.some(c=>!c.pass))throw Error('接触点距离未达到容差，未应用任何本次姿态修改：'+checks.filter(c=>!c.pass).map(c=>`${c.sourceKey}→${c.targetKey} ${c.distance.toFixed(4)}m > ${c.tolerance}m`).join('；'));
 return {commands,checks,limitations:'仅检查已标定点的距离，不证明接触面、穿插、受力或视觉质量合格。'};
}
