import {safeRequestFootprint} from '../ai/requestFootprint';
import type {AgentActivity} from '../ai/modelingAgent';
// Only allowlisted operational metadata. Never export messages, raw errors, URLs,
// tool arguments, scene content, images or credentials (even if an error echoed them).
const finite=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)&&v>=0?v:undefined;
const identifier=(v:unknown)=>typeof v==='string'&&/^[a-zA-Z0-9][a-zA-Z0-9._:/-]{0,127}$/.test(v)&&!/^sk-|bearer|token-/i.test(v)?v:undefined;
export function runDiagnostics(status:string,activity:AgentActivity|null,error:string|null){
 const category=!error?null:/体验页访问验证|访问会话/.test(error)?'site-access':/网络|连接|fetch|Connection/i.test(error)?'connection':/超时|无响应/.test(error)?'timeout':/校验|参数|工具/.test(error)?'validation':'unclassified';
 return {format:'chat3d-diagnostics-v1',createdAt:new Date().toISOString(),status,errorCategory:category,httpStatus:error?.match(/HTTP\s+(\d{3})/i)?.[1]??null,run:activity?{outcome:['preview-ready','partial','answered','budget-exhausted','cancelled','failed'].includes(activity.outcome??'')?activity.outcome:undefined,executionMeta:activity.executionMeta?{appVersion:identifier(activity.executionMeta.appVersion),model:identifier(activity.executionMeta.model),buildCommit:identifier(activity.executionMeta.buildCommit),initialRevision:finite(activity.executionMeta.initialRevision),contextPolicy:identifier(activity.executionMeta.contextPolicy),executionMode:activity.executionMeta.executionMode==='pi'?'pi':undefined}:undefined,turns:activity.turn,usageIncomplete:!!activity.usageIncomplete||activity.timings.some(t=>t.kind==='model'&&(t.usageState==='unknown'||(!t.usageState&&!(Number(t.inputTokens)>0||Number(t.outputTokens)>0)))),subagents:activity.parallelRuns?.map(r=>({status:r.status,rounds:r.rounds,toolCalls:r.toolCalls,inputTokens:r.inputTokens,outputTokens:r.outputTokens,usageReported:r.usageReported,startedAt:r.startedAt,endedAt:r.endedAt})),toolCalls:activity.toolCalls,inputTokens:activity.inputTokens,outputTokens:activity.outputTokens,timings:activity.timings.map(t=>({kind:t.kind,toolName:t.kind==='tool'&&typeof t.toolName==='string'&&/^[a-z][a-z0-9_]{0,63}$/.test(t.toolName)?t.toolName:undefined,repeatedInput:typeof t.repeatedInput==='boolean'?t.repeatedInput:undefined,argumentsChars:finite(t.argumentsChars),resultChars:finite(t.resultChars),sceneRevision:finite(t.sceneRevision),firstDataAt:finite(t.firstDataAt),firstContentAt:finite(t.firstContentAt),responseAt:finite(t.responseAt),usageState:t.kind==='model'?(['reported','reported-zero','unknown'].includes(t.usageState??'')?t.usageState:(Number(t.inputTokens)>0||Number(t.outputTokens)>0?'reported':'unknown')):undefined,uncachedInputTokens:finite(t.uncachedInputTokens),cacheReadTokens:finite(t.cacheReadTokens),cacheWriteTokens:finite(t.cacheWriteTokens),startedAt:t.startedAt,endedAt:t.endedAt,failed:t.failed??false,inputTokens:t.inputTokens,outputTokens:t.outputTokens,requestFootprint:safeRequestFootprint(t.requestFootprint)}))}:null};
}
