import {Box3,Matrix4,Quaternion,Vector3} from 'three';import type {SceneNode,Geometry} from './types';
export function projectMeshUV(node:SceneNode,mode:'planar'|'cylindrical'|'box',axis:'x'|'y'|'z'='y'):Geometry{
 if(node.geometry?.type!=='mesh')throw Error('此工具仅为缺UV的网格建立投影；参数几何已自带UV');const original=node.geometry.params;if(!['planar','cylindrical','box'].includes(mode)||!['x','y','z'].includes(axis))throw Error('UV投影参数无效');
 const mat=new Matrix4().compose(new Vector3(...node.transform.position),new Quaternion(...node.transform.rotationQuaternion),new Vector3(...node.transform.scale));const world:Vector3[]=[];const box=new Box3();for(let i=0;i<original.positions.length;i+=3){const v=new Vector3(...original.positions.slice(i,i+3) as [number,number,number]).applyMatrix4(mat);world.push(v);box.expandByPoint(v);}const centre=box.getCenter(new Vector3()),size=box.getSize(new Vector3()),dimensions=axis==='y'?['x','z','y'] as const:axis==='x'?['y','z','x'] as const:['x','y','z'] as const;const [u,v,h]=dimensions;
 const points=world.map(p=>mode==='cylindrical'?[Math.atan2(p[v]-centre[v],p[u]-centre[u])/(Math.PI*2)+.5,(p[h]-box.min[h])/Math.max(size[h],1e-6)]:[(p[u]-box.min[u])/Math.max(size[u],1e-6),(p[v]-box.min[v])/Math.max(size[v],1e-6)]);
 const positions:number[]=[],normals:number[]=[],uvs:number[]=[],indices:number[]=[],map=new Map<string,number>();
 for(let t=0;t<original.indices.length;t+=3){const corners=original.indices.slice(t,t+3);const values=corners.map(i=>points[i][0]);const seam=mode==='cylindrical'&&Math.max(...values)-Math.min(...values)>.5;
  let face='';let boxAxes:readonly ['x'|'y'|'z','x'|'y'|'z']=['x','y'];
  if(mode==='box'){const normal=new Vector3().subVectors(world[corners[1]],world[corners[0]]).cross(new Vector3().subVectors(world[corners[2]],world[corners[0]]));const dominant=Math.abs(normal.x)>=Math.abs(normal.y)&&Math.abs(normal.x)>=Math.abs(normal.z)?'x':Math.abs(normal.y)>=Math.abs(normal.z)?'y':'z';face=dominant+(normal[dominant]<0?'-':'+');boxAxes=dominant==='x'?['z','y']:dominant==='y'?['x','z']:['x','y'];}
  for(const index of corners){let uv=[...points[index]];if(mode==='box'){const [a,b]=boxAxes;uv=[(world[index][a]-box.min[a])/Math.max(size[a],1e-6),(world[index][b]-box.min[b])/Math.max(size[b],1e-6)];if(face.endsWith('-'))uv[0]=1-uv[0];}if(seam&&uv[0]<.5)uv[0]+=1;const key=index+':'+face+':'+uv[0];let next=map.get(key);if(next===undefined){next=positions.length/3;map.set(key,next);positions.push(...original.positions.slice(index*3,index*3+3));if(original.normals)normals.push(...original.normals.slice(index*3,index*3+3));uvs.push(...uv.map(x=>Math.round(x*100000)/100000));}indices.push(next);}}

 return {type:'mesh',params:{positions,indices,uvs,...(original.normals?{normals}:{})}};
}
