import assert from 'node:assert/strict';
import {createServer} from 'vite';
const vite=await createServer({server:{middlewareMode:true},appType:'custom'});let passed=0;const test=async(n,f)=>{await f();console.log('PASS',n);passed++;};
try{
 const {createInitialDoc,useEditorStore:store}=await vite.ssrLoadModule('/src/store.ts');const {applyBatch}=await vite.ssrLoadModule('/src/domain/commands.ts');const {validateAnimation,createAnimationEvaluator}=await vite.ssrLoadModule('/src/domain/animation.ts');const {parseProject,serializeProject}=await vite.ssrLoadModule('/src/domain/project.ts');const {parseModelResponse}=await vite.ssrLoadModule('/src/ai/provider.ts');const {checkEditScope}=await vite.ssrLoadModule('/src/domain/editScope.ts');const {AnimationClock}=await vite.ssrLoadModule('/src/scene/animationPlayback.ts');
 const create=(name,x)=>({op:'createPrimitive',name,parentId:null,geometry:{type:'box',params:{width:1,height:1,depth:1}},transform:{position:[x,0,0],rotationQuaternion:[0,0,0,1],scale:[1,1,1]}});
 const base=applyBatch(createInitialDoc(),{operations:[create('material',0),create('machine',10)]}).doc;const [a,b]=base.nodes.map(n=>n.id);
 const move={id:'move',name:'移动与停留',targetIds:[a],channel:'position',keyframes:[{time:0,value:[0,0,0]},{time:2,value:[2,0,0]},{time:4,value:[2,0,0]},{time:6,value:[0,0,0]}]};
 const program=(tracks=[move])=>({version:1,name:'动态产线',duration:6,loop:true,tracks});const apply=(animation)=>applyBatch(base,{operations:[{op:'setAnimation',animation}]}).doc;
 await test('animation move dwell return is deterministic without mutating scene baseline',()=>{const d=apply(program()),raw=JSON.stringify(d),sample=createAnimationEvaluator(d);assert.deepEqual(sample(1).get(a).transform.position,[1,0,0]);assert.deepEqual(sample(3).get(a).transform.position,[2,0,0]);assert.deepEqual(sample(6).get(a).transform.position,[0,0,0]);assert.deepEqual(sample(3),sample(3));assert.equal(sample(1).has(b),false);assert.equal(JSON.stringify(d),raw);});
 await test('rotation around world pivot and scale/visibility channels compose',()=>{const d=apply(program([{id:'r',name:'转动',targetIds:[b],channel:'rotation',axis:[0,1,0],pivot:[0,0,0],keyframes:[{time:0,value:0},{time:6,value:90}]},{id:'s',name:'缩放',targetIds:[b],channel:'scale',keyframes:[{time:0,value:[1,1,1]},{time:6,value:[2,2,2]}]},{id:'v',name:'显隐',targetIds:[b],channel:'visibility',keyframes:[{time:0,value:true},{time:4,value:false}]}]));const pose=createAnimationEvaluator(d)(6).get(b);assert.ok(Math.abs(pose.transform.position[0])<1e-7);assert.ok(Math.abs(pose.transform.position[2]+10)<1e-7);assert.deepEqual(pose.transform.scale,[2,2,2]);assert.equal(pose.visible,false);});
 await test('bounded motion expressions generate new curves without eval or scene presets',()=>{const tr={...move,keyframes:undefined,expression:[{op:'sin',args:['t']},0,{op:'sub',args:[{op:'cos',args:['t']},1]}]};const sample=createAnimationEvaluator(apply(program([tr])));assert.ok(Math.abs(sample(Math.PI/2).get(a).transform.position[0]-1)<1e-8);assert.ok(validateAnimation(program([{...tr,expression:['fetch(secret)',0,0]}]),base.nodes).length);});
 await test('division by zero stops evaluation rather than corrupting transforms',()=>{const d=apply(program([{...move,keyframes:undefined,expression:[{op:'div',args:[1,{op:'sub',args:['t',2]}]},0,0]}]));assert.throws(()=>createAnimationEvaluator(d)(2),/零/);assert.deepEqual(d.nodes[0].transform.position,[0,0,0]);});
 await test('binding and release follow only the source movement inside their time window',()=>{const d=apply(program([{...move,targetIds:[b],keyframes:[{time:0,value:[0,0,0]},{time:6,value:[6,0,0]}]},{id:'follow',name:'取放',targetIds:[a],channel:'follow',sourceId:b,start:2,end:4}]));const e=createAnimationEvaluator(d);assert.equal(e(1).get(a).transform.position[0],0);assert.equal(e(3).get(a).transform.position[0],1);assert.equal(e(5).get(a).transform.position[0],2);});
 await test('invalid references cycles duplicate channels and invalid timings are rejected atomically',()=>{for(const tracks of [[{...move,targetIds:['missing']}],[move,{...move,id:'duplicate'}],[{...move,keyframes:[{time:2,value:[0,0,0]}]}],[{id:'fa',name:'a',targetIds:[a],channel:'follow',sourceId:b,start:0,end:6},{id:'fb',name:'b',targetIds:[b],channel:'follow',sourceId:a,start:0,end:6}]]){const result=applyBatch(base,{operations:[create('must rollback',5),{op:'setAnimation',animation:program(tracks)}]});assert.ok(result.errors.length);assert.equal(result.doc,base);}});
 await test('JSON project roundtrip and undo redo preserve animation without playback state',()=>{const d=apply(program());assert.deepEqual(parseProject(serializeProject(d)).animation,d.animation);store.setState({doc:base,past:[],future:[],aiStatus:'idle'});store.getState().applyCommandBatch([{op:'setAnimation',animation:program()}],'animate');assert.ok(store.getState().doc.animation);store.getState().undo();assert.equal(store.getState().doc.animation,undefined);store.getState().redo();assert.ok(store.getState().doc.animation);store.getState().applyCommandBatch([{op:'clearAnimation'}],'clear');store.getState().undo();assert.ok(store.getState().doc.animation);});
 await test('AI command parser exposes animation and resolves same-batch temporary target IDs',()=>{const ops=parseModelResponse(JSON.stringify({summary:'move',operations:[{...create('new',1),tempId:'part'},{op:'setAnimation',animation:program([{...move,targetIds:['part']}])}]})).operations;const r=applyBatch(base,{operations:ops});assert.equal(r.errors.length,0);assert.equal(r.doc.animation.tracks[0].targetIds[0],r.doc.nodes[2].id);});
 await test('local edit scope protects unselected motion and indirect follower dependencies',()=>{assert.equal(checkEditScope(base,apply(program()),{nodeIds:[a]}).length,0);assert.ok(checkEditScope(base,apply(program([{...move,targetIds:[b]}])),{nodeIds:[a]}).length);const d=apply(program([{...move,targetIds:[a]},{id:'f',name:'follow',targetIds:[b],channel:'follow',sourceId:a,start:0,end:6}]));const next=applyBatch(d,{operations:[{op:'setAnimation',animation:program([{...move,keyframes:[{time:0,value:[0,0,0]},{time:6,value:[3,0,0]}]},d.animation.tracks[1]])}]}).doc;assert.ok(checkEditScope(d,next,{nodeIds:[a]}).length);});
 await test('play pause reset speed seek and session reconfiguration are bounded',()=>{const c=new AnimationClock();c.configure(2,true);c.play();c.tick(.2);assert.equal(c.state.time,.2);c.pause();c.tick(.2);assert.equal(c.state.time,.2);c.setSpeed(2);c.play();c.tick(.2);assert.equal(c.state.time,.6000000000000001);c.seek(2);c.tick(.1);assert.ok(c.state.time<1);c.reset();assert.equal(c.state.time,0);assert.equal(c.state.playing,false);c.configure(1,false);c.seek(.9);c.play();c.tick(.2);assert.equal(c.state.time,1);assert.equal(c.state.playing,false);c.configure();assert.equal(c.state.duration,0);});
 console.log(`${passed} animation domain and playback checks passed`);
}finally{await vite.close();}
