import assert from 'node:assert/strict';import {createServer} from 'vite';
const server=await createServer({server:{middlewareMode:true},appType:'custom'});let passed=0;const test=async(n,f)=>{await f();passed++;console.log('PASS',n)};
try{
const {createInitialDoc,useEditorStore:store}=await server.ssrLoadModule('/src/store.ts');const {parseModelResponse}=await server.ssrLoadModule('/src/ai/provider.ts');const {applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts');const {checkEditScope}=await server.ssrLoadModule('/src/domain/editScope.ts');const {serializeProject,parseProject}=await server.ssrLoadModule('/src/domain/project.ts');
const part=(name,x=0)=>({name,geometry:{type:'box',params:{width:1,height:1,depth:1}},transform:{position:[x,.5,0]},materialId:'mat_paint'});
const parse=operations=>parseModelResponse(JSON.stringify({summary:'编辑检查',operations}));
const fixture=()=>applyBatch(createInitialDoc(),parse([{op:'createAssembly',name:'设备A',sceneRole:'equipment',planKey:'设备A',parts:[part('左',-1),part('右',1)]},{op:'createAssembly',name:'设备B',parts:[part('外部',6)]}])).doc;
const reset=d=>store.setState({doc:d,past:[],future:[],aiStatus:'idle',pendingBatch:null,pendingResult:null,previewDoc:null,messages:[]});
await test('whole rotation and uniform scaling use bottom center, preserve IDs and do not move neighbors',()=>{const d=fixture();reset(d);const r=store.getState().applyCommandBatch(parse([{op:'transformAssembly',targetId:d.nodes[0].id,rotationDegrees:[0,90,0],scaleFactor:2}]).operations,'整机变换');assert.equal(r.ok,true);const after=store.getState().doc;assert.ok(Math.abs(after.nodes[0].transform.position[0])<1e-9);assert.ok(Math.abs(after.nodes[0].transform.position[1]-1)<1e-9);assert.ok(Math.abs(after.nodes[0].transform.position[2]-2)<1e-9);assert.deepEqual(after.nodes[0].transform.scale,[2,2,2]);assert.deepEqual(after.nodes[2],d.nodes[2]);store.getState().undo();assert.deepEqual(store.getState().doc.nodes,d.nodes);store.getState().redo();assert.deepEqual(store.getState().doc.nodes,after.nodes)});
await test('append is one reversible transaction and stays inside a fully selected assembly',()=>{const d=fixture();reset(d);const op=parse([{op:'appendAssemblyParts',targetId:d.nodes[0].id,parts:[part('新部件',0)]}]).operations;assert.equal(store.getState().applyCommandBatch(op,'追加').ok,true);const after=store.getState().doc;assert.equal(after.nodes.length,4);assert.equal(after.nodes[3].assemblyId,d.nodes[0].assemblyId);assert.equal(checkEditScope(d,after,{nodeIds:d.nodes.slice(0,2).map(n=>n.id),allowAssemblyAdditions:true,lockPlacement:true}).length,0);assert.ok(checkEditScope(d,after,{nodeIds:[d.nodes[0].id],allowAssemblyAdditions:true}).length);store.getState().undo();assert.deepEqual(store.getState().doc.nodes,d.nodes);store.getState().redo();assert.deepEqual(store.getState().doc.nodes,after.nodes);assert.deepEqual(parseProject(serializeProject(after)).nodes,after.nodes)});
await test('replacing a non-anchor target deletes exactly listed parts and undo removes new parts too',()=>{const d=fixture();reset(d);const r=store.getState().applyCommandBatch(parse([{op:'replaceAssemblyParts',targetId:d.nodes[1].id,partIds:[d.nodes[1].id],parts:[part('新右A',1),part('新右B',2)]}]).operations,'替换');assert.equal(r.ok,true);const after=store.getState().doc;assert.equal(after.nodes.length,4);assert.ok(!after.nodes.some(n=>n.id===d.nodes[1].id));assert.deepEqual(after.nodes.find(n=>n.id===d.nodes[2].id),d.nodes[2]);assert.equal(store.getState().past[0].applied[0].after.nodes.length,3);store.getState().undo();assert.deepEqual(store.getState().doc.nodes,d.nodes);store.getState().redo();assert.deepEqual(store.getState().doc.nodes,after.nodes)});
await test('replacing the anchor keeps the component addressable and preserves grouping',()=>{const d=fixture();const r=applyBatch(d,parse([{op:'replaceAssemblyParts',targetId:d.nodes[0].id,partIds:[d.nodes[0].id],parts:[part('新锚点'),part('新机构',.5)]}]));assert.equal(r.errors.length,0);assert.ok(r.doc.nodes.some(n=>n.id===d.nodes[0].id));const move=applyBatch(r.doc,{operations:[{op:'translateAssembly',targetId:d.nodes[0].id,value:[1,0,0]}]});assert.equal(move.errors.length,0);assert.equal(move.applied[0].before.nodes.length,3)});
await test('cross-component replacement and unsafe transforms reject atomically',()=>{const d=fixture();const replace=applyBatch(d,parse([{op:'replaceAssemblyParts',targetId:d.nodes[0].id,partIds:[d.nodes[2].id],parts:[part('不应创建')]}]));assert.ok(replace.errors.length);assert.deepEqual(replace.doc,d);const bad=applyBatch(d,{operations:[{op:'transformAssembly',targetId:d.nodes[0].id,scaleFactor:0}]});assert.ok(bad.errors.length);assert.deepEqual(bad.doc,d)});
await test('subsequent local edits can target newly appended parts without expanding original scope',()=>{const d=fixture(),scope={nodeIds:d.nodes.slice(0,2).map(n=>n.id),allowAssemblyAdditions:true};const first=applyBatch(d,parse([{op:'appendAssemblyParts',targetId:d.nodes[0].id,parts:[part('追加')]}])).doc;const second=applyBatch(first,{operations:[{op:'setAppearance',targetId:first.nodes.at(-1).id,baseColor:'#123456'}]}).doc;assert.equal(checkEditScope(d,second,scope).length,0);const outside=structuredClone(second);outside.nodes.find(n=>n.id===d.nodes[2].id).assemblyId=d.nodes[0].assemblyId;assert.ok(checkEditScope(d,outside,scope).length)});
await test('batch copying uses actual part count instead of charging every small assembly as 2000 nodes',()=>{const d=fixture();const r=applyBatch(d,{operations:[1,2,3,4].map(i=>({op:'duplicateAssembly',targetId:d.nodes[0].id,offset:[i*3,0,0]}))});assert.equal(r.errors.length,0);assert.equal(r.doc.nodes.length,d.nodes.length+8)});
await test('actual allocation budget still rejects oversized copy batches atomically',()=>{const parts=Array.from({length:10},(_,i)=>({...part('part'+i),repeat:{count:100,step:[.01,0,0]}}));const d=applyBatch(createInitialDoc(),parse([{op:'createAssembly',name:'large',parts}])).doc;assert.equal(d.nodes.length,1000);const r=applyBatch(d,{operations:[1,2,3,4].map(i=>({op:'duplicateAssembly',targetId:d.nodes[0].id,offset:[i*3,0,0]}))});assert.match(r.errors[0].message,/实际新增/);assert.deepEqual(r.doc,d);assert.equal(r.applied.length,0)});
console.log(`${passed} assembly editing checks passed`);
}finally{await server.close()}
