import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {indexedDB} from 'fake-indexeddb';
import {createServer} from 'vite';
import React from 'react';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'https://example.test'});
for(const name of ['window','document','HTMLElement','HTMLInputElement','Element','CustomEvent','Node','NodeFilter','MutationObserver','Event','MouseEvent','localStorage','location','DocumentFragment'])Object.defineProperty(globalThis,name,{value:dom.window[name],configurable:true});
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});globalThis.indexedDB=indexedDB;globalThis.getComputedStyle=dom.window.getComputedStyle;globalThis.requestAnimationFrame=fn=>setTimeout(fn,0);globalThis.cancelAnimationFrame=clearTimeout;window.requestAnimationFrame=globalThis.requestAnimationFrame;window.cancelAnimationFrame=globalThis.cancelAnimationFrame;globalThis.ResizeObserver=class{observe(){} unobserve(){} disconnect(){}};
globalThis.CSS={escape:value=>String(value).replace(/[^a-zA-Z0-9_-]/g,char=>'\\'+char)};globalThis.SVGElement=dom.window.SVGElement;globalThis.IS_REACT_ACT_ENVIRONMENT=true;
HTMLElement.prototype.scrollIntoView=()=>{};
const {render,fireEvent,waitFor,cleanup,act}=await import('@testing-library/react');
const {Theme}=await import('@radix-ui/themes');
const server=await createServer({plugins:[{name:'workbench-viewport-fixture',enforce:'pre',load(id){if(id.endsWith('/src/ui/ViewportPanel.tsx'))return "import React from 'react';export function ViewportPanel(){return React.createElement('div',{'data-testid':'viewport-fixture'});}";}}],server:{middlewareMode:true},appType:'custom'});let passed=0;

try{
 const {CanvasAssetShelf,CanvasInspector}=await server.ssrLoadModule('/src/ui/CanvasPanels.tsx'),{AppearanceProvider}=await server.ssrLoadModule('/src/ui/Appearance.tsx');
 const {useEditorStore:store,createInitialDoc}=await server.ssrLoadModule('/src/store.ts'),w=await server.ssrLoadModule('/src/workspace.ts'),{createModelAsset}=await server.ssrLoadModule('/src/domain/modelAssets.ts'),storage=await server.ssrLoadModule('/src/domain/modelAssetStorage.ts');
 await w.initializeWorkspace();w.createSession(undefined,{moduleKind:'scene',title:'画布试验'});
 store.getState().applyCommandBatch([{op:'createPrimitive',name:'测试托盘',parentId:null,geometry:{type:'box',params:{width:1.2,height:.15,depth:1}},transform:{position:[0,.075,0],scale:[1,1,1],rotationQuaternion:[0,0,0,1]},materialId:'mat_blue'}],'fixture');
 const node=store.getState().doc.nodes[0],asset=createModelAsset(store.getState().doc,[node.id],{name:'测试托盘',category:'仓储'});await storage.saveModelAsset(asset,0);
 const {useCompositionTool,cancelAssetPlacement}=await server.ssrLoadModule('/src/ui/manualComposition.tsx');store.setState({viewportStatus:'ready'});
 const wrap=child=>React.createElement(AppearanceProvider,null,child);let closed=false;
 let ui=render(wrap(React.createElement(CanvasAssetShelf,{onClose:()=>closed=true,onLibrary:()=>{}})));
 await waitFor(()=>assert.ok(ui.getByRole('button',{name:'选择资产 测试托盘'})));console.log('PASS asset shelf reads actual saved assets');passed++;
 fireEvent.change(ui.getByRole('textbox',{name:'搜索画布资产'}),{target:{value:'missing'}});assert.equal(ui.queryByRole('button',{name:'选择资产 测试托盘'}),null);fireEvent.change(ui.getByRole('textbox',{name:'搜索画布资产'}),{target:{value:''}});console.log('PASS asset shelf filters without changing models');passed++;
 fireEvent.click(ui.getByRole('button',{name:'选择资产 测试托盘'}));await act(async()=>store.setState({aiStatus:'generating'}));assert.equal(ui.getByRole('button',{name:'放置 v1'}).disabled,true);assert.equal(store.getState().doc.nodes.length,1);await act(async()=>store.setState({aiStatus:'idle'}));console.log('PASS asset insertion is locked while AI runs');passed++;
 const origin=w.useWorkspaceStore.getState().activeId,duplicateDoc=store.getState().doc;await act(async()=>{fireEvent.click(ui.getByRole('button',{name:'放置 v1'}));w.createSession(duplicateDoc);});await waitFor(()=>assert.match(ui.getByRole('alert').textContent,/会话已切换/));assert.equal(store.getState().doc,duplicateDoc);assert.equal(w.getSessionEditor(origin).getState().doc,duplicateDoc);assert.equal(closed,false);await act(async()=>w.switchSession(origin));console.log('PASS async asset insertion rejects navigation even when imported projects share ID and revision');passed++;
 await act(async()=>fireEvent.click(ui.getByRole('button',{name:'放置 v1'})));await waitFor(()=>assert.equal(closed,true));assert.equal(store.getState().doc.nodes.length,1);assert.equal(useCompositionTool.getState().placement.asset.version,1);assert.equal(useCompositionTool.getState().placement.origin,w.getSessionEditor(origin));cancelAssetPlacement();assert.equal(store.getState().doc.nodes.length,1);console.log('PASS shelf starts fixed-version pointer preview and cancellation does not insert at origin');passed++;cleanup();
 store.getState().select([node.id]);let tab='position';const inspector=()=>wrap(React.createElement(CanvasInspector,{onClose:()=>{},onAdvanced:()=>{},tab,setTab:v=>{tab=v;ui.rerender(inspector())}}));ui=render(inspector());
 assert.ok(ui.getByText(/1200 × 150 × 1000 mm/));console.log('PASS inspector dimensions are measured from live geometry');passed++;
 fireEvent.change(ui.getByRole('spinbutton',{name:'画布位移 X'}),{target:{value:'2'}});fireEvent.click(ui.getByRole('button',{name:'应用更改'}));assert.equal(store.getState().doc.nodes[0].transform.position[0],2);await act(async()=>store.getState().undo());assert.equal(store.getState().doc.nodes[0].transform.position[0],0);console.log('PASS contextual position editing is real and undoable');passed++;
 fireEvent.click(ui.getByRole('button',{name:'尺寸',exact:true}));fireEvent.change(ui.getByRole('spinbutton',{name:'画布缩放倍数'}),{target:{value:'2'}});fireEvent.click(ui.getByRole('button',{name:'应用更改'}));assert.deepEqual(store.getState().doc.nodes[0].transform.scale,[2,2,2]);await act(async()=>store.getState().undo());console.log('PASS contextual scaling preserves proportions and supports undo');passed++;
 fireEvent.change(ui.getByRole('spinbutton',{name:'画布缩放倍数'}),{target:{value:'0'}});fireEvent.click(ui.getByRole('button',{name:'应用更改'}));assert.deepEqual(store.getState().doc.nodes[0].transform.scale,[1,1,1]);assert.ok(ui.getByRole('status'));console.log('PASS invalid scales do not mutate the model');passed++;
 fireEvent.click(ui.getByRole('button',{name:'设为颜色 #D5444C'}));assert.equal(store.getState().doc.materials.find(m=>m.id===store.getState().doc.nodes[0].materialId).baseColor.toLowerCase(),'#d5444c');await act(async()=>store.getState().undo());console.log('PASS contextual color swatches edit actual materials with undo');passed++;
 await act(async()=>store.setState({aiStatus:'previewing'}));assert.equal(document.querySelector('fieldset').disabled,true);console.log('PASS pending preview locks contextual edits');passed++;
 await act(async()=>store.setState({aiStatus:'idle'}));cleanup();
 const part=(count,index)=>({name:'bulk'+index,geometry:{type:'box',params:{width:.01,height:.01,depth:.01}},transform:{position:[0,0,index*.1],scale:[1,1,1],rotationQuaternion:[0,0,0,1]},repeat:{count,step:[.02,0,0]}});
 await act(async()=>store.getState().applyCommandBatch([{op:'createAssembly',name:'269零件属性测试',parts:[part(100,0),part(100,1),part(69,2)]}],'large fixture'));
 const members=store.getState().doc.nodes.filter(n=>n.assemblyName==='269零件属性测试');assert.equal(members.length,269);store.getState().select(members.map(n=>n.id));tab='position';ui=render(inspector());
 fireEvent.change(ui.getByRole('spinbutton',{name:'画布位移 X'}),{target:{value:'1'}});fireEvent.click(ui.getByRole('button',{name:'应用更改'}));assert.ok(ui.getByText('已修改，可撤销'));assert.equal(store.getState().doc.nodes.find(n=>n.id===members[0].id).transform.position[0],1);await act(async()=>store.getState().undo());assert.equal(store.getState().doc.nodes.find(n=>n.id===members[0].id).transform.position[0],0);console.log('PASS actual inspector applies and undoes a 269-part model without command-budget failure');passed++;

 cleanup();const large={...createInitialDoc(),nodes:Array.from({length:2601},(_,i)=>({...structuredClone(node),id:'ui-large-'+i,name:'零件 '+i,assemblyId:i%2===0?'partial-ui':undefined,transform:{position:[i%100*.02,0,Math.floor(i/100)*.02],scale:[1,1,1],rotationQuaternion:[0,0,0,1]}}))};const largeIds=large.nodes.slice(0,2600).map(n=>n.id);
 await act(async()=>store.setState({doc:large,selection:largeIds,past:[],future:[],aiStatus:'idle',previewDoc:null}));tab='position';ui=render(inspector());
 for(const mode of ['位置','旋转','尺寸','颜色']){
  if(mode==='颜色')fireEvent.click(ui.getByRole('button',{name:'设为颜色 #D5444C'}));
  else {fireEvent.click(ui.getByRole('button',{name:mode,exact:true}));fireEvent.change(ui.getByRole('spinbutton',{name:mode==='位置'?'画布位移 X':mode==='旋转'?'画布旋转 Y':'画布缩放倍数'}),{target:{value:mode==='旋转'?'45':'2'}});fireEvent.click(ui.getByRole('button',{name:'应用更改'}));}
  assert.equal(ui.getByRole('status').textContent,'已修改，可撤销');assert.equal(store.getState().past.length,1);const changed=store.getState().doc;assert.notDeepEqual(changed.nodes[2599],large.nodes[2599]);assert.deepEqual(changed.nodes[2600],large.nodes[2600]);await act(async()=>store.getState().undo());assert.deepEqual(store.getState().doc.nodes,large.nodes);assert.deepEqual(store.getState().doc.materials,large.materials);await act(async()=>store.getState().redo());assert.deepEqual(store.getState().doc.nodes,changed.nodes);await act(async()=>store.getState().undo());console.log('PASS actual inspector edits/undoes/redoes 2600 partial independent parts: '+mode);passed++;
 }
 fireEvent.click(ui.getByRole('button',{name:'尺寸',exact:true}));fireEvent.change(ui.getByRole('spinbutton',{name:'画布缩放倍数'}),{target:{value:''}});fireEvent.click(ui.getByRole('button',{name:'应用更改'}));assert.match(ui.getByRole('status').textContent,/请输入/);assert.equal(store.getState().past.length,0);assert.deepEqual(store.getState().doc.nodes,large.nodes);
 fireEvent.change(ui.getByRole('spinbutton',{name:'画布缩放倍数'}),{target:{value:'3'}});const beforeClose=store.getState().doc;fireEvent.click(ui.getByRole('button',{name:'关闭属性面板'}));cleanup();assert.equal(store.getState().doc,beforeClose);assert.equal(store.getState().past.length,0);console.log('PASS invalid and dismissed 2600-part property input never partially commits');passed++;
 await act(async()=>store.setState({aiStatus:'idle'}));await w.flushWorkspace();console.log(`${passed} canvas interaction checks passed`);
}finally{cleanup();await server.close();dom.window.close()}
