import assert from 'node:assert/strict';
import {indexedDB,IDBFactory} from 'fake-indexeddb';
import {createServer} from 'vite';
globalThis.indexedDB=indexedDB;
const server=await createServer({server:{middlewareMode:true},appType:'custom'});let count=0;const test=async(n,f)=>{await f();count++;console.log('PASS',n)};
try{
 const c=await server.ssrLoadModule('/src/domain/libraryCategories.ts'),s=await server.ssrLoadModule('/src/domain/modelAssetStorage.ts'),a=await server.ssrLoadModule('/src/domain/modelAssets.ts'),{createInitialDoc}=await server.ssrLoadModule('/src/store.ts');
 const root=await c.saveLibraryCategory('生产设备'),child=await c.saveLibraryCategory('检测设备',undefined,{parentValue:root.value});
 await test('parent filter includes children and paths use stable IDs',async()=>{const rows=await c.listLibraryCategories();assert.equal(c.categoryMatches(rows,child.value,root.value),true);assert.equal(c.categoryPath(rows,child.value),'生产设备 / 检测设备');assert.equal(c.categoryMatches(rows,'人员',root.value),false);});
 await test('third levels and duplicate siblings are rejected; same names across parents are allowed',async()=>{await assert.rejects(c.saveLibraryCategory('三级',undefined,{parentValue:child.value}),/两级/);await assert.rejects(c.saveLibraryCategory('检测设备',undefined,{parentValue:root.value}),/已存在/);const second=await c.saveLibraryCategory('检测设备',undefined,{parentValue:'仓储'});assert.notEqual(second.value,child.value);});
 await test('scene and asset category catalogs are independent and legacy values remain visible',async()=>{const scene=await c.saveLibraryCategory('生产设备',undefined,{kind:'scene'});await c.saveLibraryCategory('场景专属',scene,{kind:'scene'});assert.equal(c.categoryLabel(await c.listLibraryCategories(),root.value),'生产设备');assert.equal(c.categoryLabel(await c.listLibraryCategories([],'scene'),scene.value),'场景专属');assert.ok((await c.listLibraryCategories(['旧场景'],'scene')).some(x=>x.value==='旧场景'));assert.equal((await c.listLibraryCategories([],'scene')).some(x=>x.value===child.value),false);const old=await c.saveLibraryCategory('旧共享分类');await c.saveLibraryCategory('已有显示名称',old);assert.equal(c.categoryLabel(await c.listLibraryCategories([old.value],'scene'),old.value),'已有显示名称');});
 const doc=createInitialDoc();doc.nodes=[{id:'part',name:'part',kind:'primitive',parentId:null,visible:true,geometry:{type:'box',params:{width:1,height:1,depth:1}},materialId:'mat_gray',transform:{position:[0,0,0],scale:[1,1,1],rotationQuaternion:[0,0,0,1]}}];
 const one=a.createModelAsset(doc,['part'],{name:'one',category:'设备'}),two=a.createModelAsset(doc,['part'],{name:'two',category:'设备'});await s.saveModelAsset(one);await s.saveModelAsset(two);
 await test('bulk moves are atomic and preserve immutable geometry versions',async()=>{let rows=await s.listModelAssets();await s.moveModelAssetsToCategory(rows,child.value);assert.ok((await s.listModelAssets()).every(x=>x.category===child.value));assert.deepEqual(await s.readModelAsset(one.id,1),one);await assert.rejects(s.moveModelAssetsToCategory(rows,'人员'),/变化/);assert.ok((await s.listModelAssets()).every(x=>x.category===child.value));});
 await test('missing targets and stale members never partially move a selection',async()=>{let rows=await s.listModelAssets();await assert.rejects(s.moveModelAssetsToCategory(rows,'missing'),/不存在/);await s.updateModelAssetMetadata(two.id,{name:'updated',category:child.value},rows.find(x=>x.id===two.id));await assert.rejects(s.moveModelAssetsToCategory(rows,'人员'),/变化/);assert.ok((await s.listModelAssets()).every(x=>x.category===child.value));});
 await test('category hierarchy and separate scene labels roundtrip through backup',async()=>{const backup=await s.exportAssetLibrary();globalThis.indexedDB=new IDBFactory();await s.importAssetLibrary(JSON.stringify(backup));const rows=await c.listLibraryCategories();assert.equal(c.categoryMatches(rows,child.value,root.value),true);assert.equal(c.categoryLabel(await c.listLibraryCategories([],'scene'),'生产设备'),'场景专属');const bad=structuredClone(backup);bad.categories.find(x=>x.value===root.value).parentValue=child.value;await assert.rejects(s.importAssetLibrary(JSON.stringify(bad)),/两级/);});
 console.log(count+' category hierarchy checks passed');
}finally{await server.close()}
