import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import React from 'react';
import { createServer } from 'vite';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'https://example.test'});
for(const name of ['window','document','HTMLElement','Node','MutationObserver','Event','MouseEvent','localStorage','location']) Object.defineProperty(globalThis,name,{value:dom.window[name],configurable:true});
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
let handler;let requests=[];
globalThis.fetch=async(...args)=>{requests.push(args);const r=await handler(...args);r.headers.set('x-chat3d-proxy','1');return r;};
const {render,fireEvent,waitFor,cleanup,act}=await import('@testing-library/react');
const server=await createServer({server:{middlewareMode:true},appType:'custom'});
let passed=0;
const test=async(name,fn)=>{await fn();passed++;console.log('PASS',name);cleanup()};
try {
 const {ChatPanel}=await server.ssrLoadModule('/src/ui/ChatPanel.tsx');
 const {useEditorStore:store,createInitialDoc}=await server.ssrLoadModule('/src/store.ts');
 const config={baseURL:'https://example.test/v1',apiKey:'mock-test',model:'vision-test',useMock:false,agentMode:'single'};
 const reset=()=>{store.setState({viewportStatus:'ready',doc:createInitialDoc(),messages:[],composerText:'',composerImages:[],lastRun:null,aiStatus:'idle',aiError:null,aiConfig:config,pendingBatch:null,pendingResult:null,previewDoc:null,past:[],future:[]});requests=[]};
 const mount=()=>render(React.createElement(React.StrictMode,null,React.createElement(ChatPanel)));
 const send=(ui,text='创建一个盒子')=>{fireEvent.change(ui.getByLabelText('建模指令'),{target:{value:text}});fireEvent.click(ui.getByRole('button',{name:'发送',exact:true}))};
 const directOps=()=>JSON.parse(output).operations.map(op=>({...op,parentId:null,materialId:'mat_white',transform:{position:[0,.5,0],scale:[1,1,1],rotationQuaternion:[0,0,0,1]}}));
 const output=JSON.stringify({summary:'一个盒子',operations:[{op:'createPrimitive',name:'box',geometry:{type:'box',params:{width:1,height:1,depth:1}}}]});
 await test('scope selector is visible and empty selected-only requests retain the draft without calling model',async()=>{reset();const {applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts');const d=applyBatch(createInitialDoc(),{operations:directOps()}).doc;store.setState({doc:d,selection:[]});const ui=mount();fireEvent.change(ui.getByLabelText('对话修改范围'),{target:{value:'selection'}});send(ui,'改颜色');assert.match(ui.getByRole('status').textContent,/先选择/);assert.equal(requests.length,0);assert.equal(ui.getByLabelText('建模指令').value,'改颜色');assert.equal(store.getState().messages.length,0);});
 await test('explicit selected-only UI rejects out-of-scope model edits before showing preview',async()=>{reset();const {applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts');const d=applyBatch(createInitialDoc(),{operations:[...directOps(),...directOps()]}).doc;store.setState({doc:d,selection:[d.nodes[0].id]});handler=async()=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({summary:'bad edit',operations:[{op:'rename',targetId:d.nodes[1].id,name:'outside'}]})}}]}));const ui=mount();fireEvent.change(ui.getByLabelText('对话修改范围'),{target:{value:'selection'}});send(ui,'改所有名称');await waitFor(()=>assert.equal(store.getState().aiStatus,'error'));assert.equal(store.getState().pendingResult,null);assert.deepEqual(store.getState().doc,d);});
 await test('missing configuration preserves draft and does not create misleading sent message',async()=>{reset();store.setState({aiConfig:null});const ui=mount();send(ui);assert.equal(ui.getByLabelText('建模指令').value,'创建一个盒子');assert.equal(store.getState().messages.length,0);assert.equal(requests.length,0)});
 await test('waiting visible, drafting allowed, duplicate send blocked, stop aborts and stale response ignored',async()=>{reset();let release;handler=()=>new Promise(r=>release=r);const ui=mount();send(ui);await waitFor(()=>assert.equal(requests.length,1));assert.ok(ui.getByText('正在处理你的请求，模型返回说明后会在这里显示。'));fireEvent.change(ui.getByLabelText('建模指令'),{target:{value:'下一条草稿'}});fireEvent.keyDown(ui.getByLabelText('建模指令'),{key:'Enter'});assert.equal(requests.length,1);fireEvent.click(ui.getByRole('button',{name:'停止生成'}));assert.equal(requests[0][1].signal.aborted,true);await act(async()=>release(new Response(JSON.stringify({choices:[{message:{content:output}}]}))));assert.equal(store.getState().pendingBatch,null);assert.equal(ui.getByLabelText('建模指令').value,'下一条草稿');assert.equal(store.getState().doc.nodes.length,0)});
 await test('active Pi accepts guidance without a concurrent request and displays receipt',async()=>{
   reset();store.setState({aiConfig:{...config,agentMode:'pi',stream:true}});let release;let n=0;
   const reply=text=>new Response('data: '+JSON.stringify({choices:[{index:0,delta:{role:'assistant',content:text},finish_reason:null}]})+'\n\ndata: '+JSON.stringify({choices:[{index:0,delta:{},finish_reason:'stop'}]})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}});
   handler=async()=>{n++;return n===1?new Promise(r=>release=r):reply('已收到，请按八米设计');};
   const ui=mount();send(ui,'先讨论货架');await waitFor(()=>assert.ok(release));fireEvent.change(ui.getByLabelText('建模指令'),{target:{value:'货架八米高，先回答如何分层'}});fireEvent.click(ui.getByRole('button',{name:'发送引导'}));assert.equal(requests.length,1);assert.equal(ui.getByLabelText('建模指令').value,'');assert.ok(ui.getByText('补充要求 · 等待接收'));
   await act(async()=>release(reply('初步建议')));await waitFor(()=>assert.equal(store.getState().aiStatus,'idle'));assert.equal(requests.length,2);assert.match(requests[1][1].body,/货架八米/);assert.ok(ui.getByText('补充要求 · 已送入模型上下文'));
 });
 await test('stopping Pi marks queued guidance undelivered and ignores late response',async()=>{
   reset();store.setState({aiConfig:{...config,agentMode:'pi',stream:true}});let release;handler=()=>new Promise(r=>release=r);const ui=mount();send(ui);await waitFor(()=>assert.ok(release));fireEvent.change(ui.getByLabelText('建模指令'),{target:{value:'改成红色'}});fireEvent.click(ui.getByRole('button',{name:'发送引导'}));fireEvent.click(ui.getByRole('button',{name:'停止生成'}));assert.ok(ui.getByText('补充要求 · 未送达，可重新发送'));await act(async()=>release(new Response('data: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})));assert.equal(store.getState().doc.nodes.length,0);assert.equal(requests.length,1);
 });
 await test('two completed Pi tasks on one mounted page use independent live cancellation signals',async()=>{
   reset();store.setState({aiConfig:{...config,agentMode:'pi',stream:true}});
   handler=async()=>new Response('data: '+JSON.stringify({choices:[{index:0,delta:{role:'assistant',content:'请补充需求'},finish_reason:null}]})+'\n\ndata: '+JSON.stringify({choices:[{index:0,delta:{},finish_reason:'stop'}]})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}});
   const ui=mount();send(ui,'第一个问题');await waitFor(()=>assert.equal(store.getState().aiStatus,'idle'));const first=requests[0][1].signal;send(ui,'第二个问题');await waitFor(()=>assert.equal(requests.length,2));await waitFor(()=>assert.equal(store.getState().aiStatus,'idle'));assert.notEqual(requests[1][1].signal,first);assert.equal(requests[1][1].signal.aborted,false);assert.equal(store.getState().messages.filter(m=>m.role==='user').length,2);
 });
 await test('later task is saved without steering or starting a second request and can be prepared after stopping',async()=>{
   reset();store.setState({aiConfig:{...config,agentMode:'pi',stream:true}});let release;handler=()=>new Promise(r=>release=r);const ui=mount();send(ui);await waitFor(()=>assert.ok(release));fireEvent.change(ui.getByLabelText('执行中消息用途'),{target:{value:'later'}});fireEvent.change(ui.getByLabelText('建模指令'),{target:{value:'后面创建一个独立货架'}});fireEvent.click(ui.getByRole('button',{name:'保存后续任务'}));assert.equal(requests.length,1);assert.equal(store.getState().messages.at(-1).queuedTask.status,'waiting');fireEvent.click(ui.getByRole('button',{name:'停止生成'}));fireEvent.click(ui.getByRole('button',{name:'准备发送'}));assert.equal(ui.getByLabelText('建模指令').value,'后面创建一个独立货架');assert.equal(requests.length,1);await act(async()=>release(new Response('data: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})));
 });
 await test('requirement report distinguishes measured matches from unverified visual requests',async()=>{reset();const {RequirementList}=await server.ssrLoadModule('/src/ui/RequirementList.tsx');const ui=render(React.createElement(RequirementList,{report:{revision:7,items:[{quote:'四个货架',target:'货架',kind:'count',expected:'4',status:'pass',actual:'匹配4个'},{quote:'蓝色料箱',target:'料箱',kind:'color',expected:'蓝色',status:'unknown',actual:'需要视觉核对'}]}}));assert.ok(ui.getByText('数据符合 · 四个货架'));assert.ok(ui.getByText('待核对 · 蓝色料箱'));});
 await test('Site access recovery uses the official top-level login route without credentials or automatic requests',async()=>{
   reset();const previous=globalThis.location;Object.defineProperty(globalThis,'location',{value:new URL('https://sample.chatgpt.site/'),configurable:true});try{const {SiteAccessRecovery}=await server.ssrLoadModule('/src/ui/SiteAccessRecovery.tsx');const ui=render(React.createElement(SiteAccessRecovery,{error:'体验页访问验证未通过（HTTP 401）'}));const a=ui.getByRole('link',{name:'重新登录体验页'});assert.equal(a.href,'https://sample.chatgpt.site/signin-with-chatgpt');assert.equal(a.target,'_blank');assert.ok(a.rel.includes('noopener'));assert.ok(ui.getByRole('button',{name:'下载当前场景备份'}));assert.equal(requests.length,0);assert.equal(store.getState().aiConfig.apiKey,'mock-test');}finally{Object.defineProperty(globalThis,'location',{value:previous,configurable:true});}
 });
 await test('real stream progress counts characters and keeps scene unchanged until confirmation',async()=>{reset();let writer;handler=async()=>new Response(new ReadableStream({start(c){writer=c}}),{headers:{'content-type':'text/event-stream'}});const ui=mount();send(ui);await waitFor(()=>assert.ok(writer));const enc=new TextEncoder();const chunk=t=>enc.encode('data: '+JSON.stringify({choices:[{delta:{content:t}}]})+'\n\n');await act(async()=>writer.enqueue(chunk(output.slice(0,20))));assert.ok(ui.getByRole('region',{name:'思考与执行摘要'}));assert.equal(ui.queryByText(/收到 20 字符/),null);assert.equal(store.getState().doc.nodes.length,0);await act(async()=>{writer.enqueue(chunk(output.slice(20)));writer.enqueue(enc.encode('data: [DONE]\n\n'));writer.close()});await waitFor(()=>assert.ok(ui.getByRole('button',{name:'应用修改'})));assert.equal(store.getState().doc.nodes.length,0);fireEvent.click(ui.getByRole('button',{name:'应用修改'}));assert.equal(store.getState().doc.nodes.length,1);assert.equal(store.getState().messages.at(-1).outcome,'applied');assert.ok(ui.getByText('✓ 已应用 · 可用工具栏撤销'))});
 await test('discard records outcome and failure restores text for explicit retry',async()=>{reset();handler=async()=>new Response(JSON.stringify({choices:[{message:{content:output}}]}));let ui=mount();send(ui);await waitFor(()=>assert.ok(ui.getByRole('button',{name:'放弃修改'})));fireEvent.click(ui.getByRole('button',{name:'放弃修改'}));assert.equal(store.getState().messages.at(-1).outcome,'discarded');assert.equal(store.getState().doc.nodes.length,0);handler=async()=>{throw new TypeError('Failed to fetch')};send(ui,'重新创建');await waitFor(()=>assert.ok(ui.getByRole('button',{name:'恢复指令重试'})));fireEvent.click(ui.getByRole('button',{name:'恢复指令重试'}));assert.equal(ui.getByLabelText('建模指令').value,'重新创建')});
 await test('follow-up includes previous reference and shows thumbnail',async()=>{reset();store.setState({messages:[{id:'photo',role:'user',text:'参考图',images:['data:image/jpeg;base64,test'],createdAt:Date.now()}]});handler=async()=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({summary:'请提供尺寸',operations:[]})}}]}));const ui=mount();send(ui,'保持比例');await waitFor(()=>assert.equal(store.getState().aiStatus,'idle'));const body=JSON.parse(requests[0][1].body);assert.ok(body.messages.at(-1).content.some(p=>p.type==='image_url'));assert.ok(ui.getByAltText('参考图 1'));assert.equal(store.getState().doc.nodes.length,0)});
 await test('timeout aborts transport and allows explicit retry; late replies cannot create preview',async()=>{reset();let release;handler=()=>new Promise(r=>release=r);const realSet=globalThis.setTimeout;globalThis.setTimeout=(fn,ms,...args)=>realSet(fn,ms===180000?20:ms,...args);try{const ui=mount();send(ui);await waitFor(()=>assert.equal(store.getState().aiStatus,'error'));assert.match(store.getState().aiError,/3 分钟/);assert.equal(requests[0][1].signal.aborted,true);await act(async()=>release(new Response(JSON.stringify({choices:[{message:{content:output}}]}))));assert.equal(store.getState().pendingBatch,null);}finally{globalThis.setTimeout=realSet}});
 await test('reference reuse can be disabled and non-stream mode is explicitly sent',async()=>{reset();store.setState({aiConfig:{...config,stream:false},messages:[{id:'photo',role:'user',text:'old',images:['data:image/jpeg;base64,test'],createdAt:Date.now()}]});handler=async()=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({summary:'ok',operations:[]})}}]}));const ui=mount();fireEvent.click(ui.getByRole('checkbox',{name:/沿用最近参考图/}));send(ui,'独立任务');await waitFor(()=>assert.equal(requests.length,1));const body=JSON.parse(requests[0][1].body);assert.equal(body.stream,false);assert.equal(typeof body.messages.at(-1).content,'string');await waitFor(()=>assert.equal(store.getState().aiStatus,'idle'))});
 await test('ChatPanel integrates the production Pi loop and keeps draft separate until user confirms',async()=>{
   reset();store.setState({aiConfig:{...config,agentMode:'pi',stream:true}});
   const {registerSceneCapture}=await server.ssrLoadModule('/src/scene/capture.ts');const unregister=registerSceneCapture(async()=> 'data:image/jpeg;base64,YWJj');
   let n=0;handler=async()=>{n++;const actions=n===1?[['plan_model',{steps:['建主体','检查'],assumptions:'估算'}],['edit_scene',{summary:'create',operations:JSON.parse(output).operations}],['capture_view',{view:'perspective'}]]:[['review_model',{observations:'已经查看外形比例',issues:[]}],['submit_preview',{summary:'Pi生成预览',remainingIssues:[]}]];const tc=actions.map(([name,args],i)=>({index:i,id:`ui_${n}_${i}`,type:'function',function:{name,arguments:JSON.stringify(args)}}));return new Response('data: '+JSON.stringify({choices:[{index:0,delta:{role:'assistant',tool_calls:tc},finish_reason:null}]})+'\n\ndata: '+JSON.stringify({choices:[{index:0,delta:{},finish_reason:'tool_calls'}]})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})};
   try{const ui=mount();send(ui);await waitFor(()=>assert.ok(ui.getByRole('button',{name:'应用修改'})),{timeout:5000});assert.equal(n,2);assert.equal(store.getState().doc.nodes.length,0);assert.equal(store.getState().previewDoc.nodes.length,1);assert.ok(ui.getByRole('region',{name:'思考与执行摘要'}));assert.equal(ui.queryByText(/工具执行/),null);assert.ok(ui.getByRole('region',{name:'思考与执行摘要'}).closest('.chat-transcript'));fireEvent.click(ui.getByRole('button',{name:'应用修改'}));assert.equal(store.getState().doc.nodes.length,1);}finally{unregister()}
 });
 const firstDraftResponse=(withSubmit=false)=>{const actions=[['plan_model',{steps:['主要设备布局','复核'],assumptions:'按阶段完成',design:{flow:['加工'],layout:'设备沿操作通道依次安排',equipment:[{name:'加工设备',count:1,features:['加工空间']}],checks:['比例与通道'],composition:{zones:[{name:'生产区',purpose:'加工'}],connections:[],support:[],palette:['灰蓝'],presentation:'统一比例和材质层次'}} }],['edit_scene',{summary:'阶段主体',operations:JSON.parse(output).operations}]];if(withSubmit)actions.push(['submit_data_preview',{summary:'全部数据完成，待视觉验收'}]);const tool_calls=actions.map(([name,args],i)=>({index:i,id:`checkpoint_${i}`,type:'function',function:{name,arguments:JSON.stringify(args)}}));return new Response('data: '+JSON.stringify({choices:[{index:0,delta:{role:'assistant',tool_calls},finish_reason:null}]})+'\n\ndata: '+JSON.stringify({choices:[{index:0,delta:{},finish_reason:'tool_calls'}]})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})};
 await test('unfinished Pi draft remains visible, explicitly retained then continued without automatic calls',async()=>{
  reset();store.setState({aiConfig:{...config,agentMode:'pi',stream:true}});let n=0;handler=async()=>++n===1?firstDraftResponse():new Response('data: '+JSON.stringify({choices:[{index:0,delta:{content:'稍后完善'},finish_reason:null}]})+'\n\ndata: '+JSON.stringify({choices:[{index:0,delta:{},finish_reason:'stop'}]})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}});
  const ui=mount();send(ui,'创建完整车间');await waitFor(()=>assert.ok(ui.getByRole('button',{name:'应用修改'})),{timeout:5000});assert.equal(store.getState().doc.nodes.length,0);assert.equal(store.getState().previewDoc.nodes.length,1);assert.equal(store.getState().pendingBatch.incomplete,true);fireEvent.click(ui.getByRole('button',{name:'应用修改'}));assert.equal(store.getState().doc.nodes.length,1);assert.equal(ui.getByLabelText('建模指令').value,'');assert.equal(n,2);act(()=>store.getState().undo());assert.equal(store.getState().doc.nodes.length,0);
 });
 for(const mode of ['stop','timeout'])await test(`Pi ${mode} preserves successful checkpoint and ignores late reply`,async()=>{
  reset();store.setState({aiConfig:{...config,agentMode:'pi',stream:true}});let n=0,release;handler=async()=>++n===1?firstDraftResponse():new Promise(r=>release=r);
  const realSet=globalThis.setTimeout;if(mode==='timeout')globalThis.setTimeout=(fn,ms,...args)=>realSet(fn,ms===180000?100:ms,...args);
  try{const ui=mount();send(ui);await waitFor(()=>assert.ok(release));if(mode==='stop')fireEvent.click(ui.getByRole('button',{name:'停止生成'}));await waitFor(()=>assert.ok(ui.getByRole('button',{name:'应用修改'})));assert.equal(store.getState().doc.nodes.length,0);assert.equal(store.getState().previewDoc.nodes.length,1);const requestId=store.getState().pendingBatch.requestId;await act(async()=>release(new Response('data: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})));assert.equal(store.getState().pendingBatch.requestId,requestId);fireEvent.click(ui.getByRole('button',{name:'放弃修改'}));assert.equal(store.getState().pendingBatch,null);assert.equal(store.getState().doc.nodes.length,0);}finally{globalThis.setTimeout=realSet}
 });
 await test('Pi active stream outlives the idle window, then pauses only when activity stops',async()=>{
  reset();store.setState({aiConfig:{...config,agentMode:'pi',stream:true}});
  let n=0,body;handler=async()=>++n===1?firstDraftResponse():new Response(new ReadableStream({start(c){body=c}}),{headers:{'content-type':'text/event-stream'}});
  const realSet=globalThis.setTimeout;globalThis.setTimeout=(fn,ms,...args)=>realSet(fn,ms===180000?180:ms,...args);
  try{
   const ui=mount();send(ui);await waitFor(()=>assert.ok(body));
   for(let i=0;i<8;i++)await act(async()=>{body.enqueue(new TextEncoder().encode('data: '+JSON.stringify({choices:[{index:0,delta:{content:'继续细化'},finish_reason:null}]})+'\n\n'));await new Promise(r=>realSet(r,60));});
   assert.equal(store.getState().aiStatus,'generating');assert.equal(store.getState().pendingBatch.incomplete,true);
   await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));assert.match(store.getState().pendingBatch.summary,/连续3分钟/);assert.equal(store.getState().previewDoc.nodes.length,1);
   assert.equal(requests.at(-1)[1].signal.aborted,true);
  }finally{globalThis.setTimeout=realSet}
 });
 await test('preview comparison switches displayed document only and requires after-view before apply',async()=>{
  reset();handler=async()=>new Response(JSON.stringify({choices:[{message:{content:output}}]}));const ui=mount();send(ui);await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));
  assert.ok(ui.getByText(/修改对比：新增 1/));const pending=store.getState().pendingResult.doc;fireEvent.click(ui.getByRole('button',{name:'查看修改前'}));assert.equal(store.getState().previewDoc.nodes.length,0);assert.equal(store.getState().pendingResult.doc,pending);assert.equal(ui.getByRole('button',{name:'应用修改'}).disabled,true);fireEvent.click(ui.getByRole('button',{name:'查看修改后'}));assert.equal(store.getState().previewDoc.nodes.length,1);fireEvent.click(ui.getByRole('button',{name:'应用修改'}));assert.equal(store.getState().doc.nodes.length,1);
 });
 await test('selected-object guard also protects single-call compatibility mode',async()=>{
  reset();const {applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts');const {parseModelResponse}=await server.ssrLoadModule('/src/ai/provider.ts');const d=applyBatch(createInitialDoc(),parseModelResponse(output)).doc;store.setState({doc:d,selection:[d.nodes[0].id]});handler=async()=>new Response(JSON.stringify({choices:[{message:{content:output}}]}));const ui=mount();assert.equal(ui.queryByRole('checkbox',{name:/仅修改选中对象/}),null);send(ui,'只修改选中对象的颜色');await waitFor(()=>assert.equal(store.getState().aiStatus,'error'));assert.match(store.getState().aiError,/不允许新增/);assert.deepEqual(store.getState().doc,d);
 });
 await test('highlighting one object does not restrict ordinary conversation edits',async()=>{reset();const {applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts');const {parseModelResponse}=await server.ssrLoadModule('/src/ai/provider.ts');const d=applyBatch(createInitialDoc(),parseModelResponse(output)).doc;store.setState({doc:d,selection:[d.nodes[0].id]});handler=async()=>new Response(JSON.stringify({choices:[{message:{content:output}}]}));const ui=mount();assert.equal(ui.queryByRole('checkbox',{name:/仅修改选中/}),null);assert.equal(ui.queryByRole('checkbox',{name:/允许给完整选中/}),null);send(ui,'添加另一个独立对象');await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));assert.equal(store.getState().pendingBatch.editScope.nodeIds,undefined);assert.equal(store.getState().pendingResult.doc.nodes.length,d.nodes.length+1);assert.deepEqual(store.getState().doc,d);});
 await test('preset preview entry points are absent',async()=>{reset();const ui=mount();assert.equal(ui.queryByRole('button',{name:/预览.*无需模型/}),null);assert.equal(requests.length,0)});
 await test('machining request does not populate a preset before model output',async()=>{reset();store.setState({aiConfig:{...config,agentMode:'pi',stream:true}});let release;handler=()=>new Promise(r=>release=r);const ui=mount();send(ui,'做一个机加工产线车间沙盘');await waitFor(()=>assert.ok(release));assert.equal(store.getState().previewDoc,null);assert.equal(store.getState().doc.nodes.length,0);fireEvent.click(ui.getByRole('button',{name:'停止生成'}));await act(async()=>release(new Response('data: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})));assert.equal(store.getState().pendingBatch,null);});
 await test('preview can be refined without applying, preserves IDs and undoes the whole chain once',async()=>{
  reset();handler=async()=>new Response(JSON.stringify({choices:[{message:{content:output}}]}));const ui=mount();send(ui);await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));
  const first=store.getState().pendingResult.doc.nodes[0].id;const initial=store.getState().pendingBatch.requestId;
  handler=async()=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({summary:'**已改色**',operations:[{op:'setAppearance',targetId:first,baseColor:'#cc4422'}]})}}]}));
  send(ui,'把刚生成的盒子改成红色');await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));
  assert.equal(store.getState().doc.nodes.length,0);assert.equal(store.getState().pendingResult.doc.nodes[0].id,first);assert.equal(store.getState().pendingBatch.operations.length,2);
  assert.equal(store.getState().messages.find(m=>m.batch?.requestId===initial).outcome,'superseded');assert.equal(ui.container.querySelectorAll('.conversation-process').length,2);assert.ok(ui.getByText('已改色').closest('strong'));
  assert.ok(ui.getByRole('button',{name:'应用修改'}).closest('.chat-transcript'));fireEvent.click(ui.getByRole('button',{name:'应用修改'}));assert.equal(store.getState().past.length,1);assert.equal(store.getState().doc.nodes[0].id,first);
  act(()=>store.getState().undo());assert.equal(store.getState().doc.nodes.length,0);act(()=>store.getState().redo());assert.equal(store.getState().doc.nodes[0].id,first);
 });
 await test('failed or stopped refinement preserves previous preview and ignores late replies',async()=>{
  for(const mode of ['error','stop']){
   reset();handler=async()=>new Response(JSON.stringify({choices:[{message:{content:output}}]}));const ui=mount();send(ui);await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));const before=store.getState().pendingResult.doc;let release;
   handler=mode==='error'?async()=>{throw new Error('upstream unavailable')}:()=>new Promise(r=>release=r);send(ui,'继续细化');
   if(mode==='stop'){await waitFor(()=>assert.ok(release));fireEvent.click(ui.getByRole('button',{name:'停止生成'}));await act(async()=>release(new Response(JSON.stringify({choices:[{message:{content:output}}]}))));}
   await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));assert.deepEqual(store.getState().pendingResult.doc,before);assert.equal(store.getState().doc.nodes.length,0);fireEvent.click(ui.getByRole('button',{name:'放弃修改'}));assert.equal(store.getState().doc.nodes.length,0);cleanup();
  }
 });
 await test('continued preview enforces the latest explicit scope without restricting previously validated edits',async()=>{
  reset();handler=async()=>new Response(JSON.stringify({choices:[{message:{content:output}}]}));const ui=mount();send(ui);await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));const parent=store.getState().pendingResult.doc;act(()=>store.setState({selection:[parent.nodes[0].id]}));
  handler=async()=>new Response(JSON.stringify({choices:[{message:{content:output}}]}));send(ui,'只修改选中对象的颜色');await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));assert.deepEqual(store.getState().pendingResult.doc,parent);assert.match(store.getState().messages.at(-1).text,/不允许新增/);
 });
 await test('per-request execution history survives ChatPanel remount without replaying requests',async()=>{
  reset();handler=async()=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({summary:'无需修改',operations:[]})}}]}));let ui=mount();send(ui,'说明当前结构');await waitFor(()=>assert.equal(store.getState().aiStatus,'idle'));const old=structuredClone(store.getState().messages[0].run);cleanup();ui=mount();assert.equal(ui.getAllByRole('region',{name:'思考与执行摘要'}).length,1);assert.deepEqual(store.getState().messages[0].run,old);assert.equal(requests.length,1);
 });
 await test('Pi refinement checkpoint composes prior draft and remains atomic after cancellation',async()=>{
  reset();handler=async()=>new Response(JSON.stringify({choices:[{message:{content:output}}]}));const ui=mount();send(ui);await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));const target=store.getState().pendingResult.doc.nodes[0].id;
  act(()=>store.setState({aiConfig:{...config,agentMode:'pi',stream:true}}));let turn=0,release;handler=async()=>{if(++turn>1)return new Promise(r=>release=r);const tool_calls=[{index:0,id:'refine',type:'function',function:{name:'edit_scene',arguments:JSON.stringify({summary:'改名阶段',operations:[{op:'rename',targetId:target,name:'改名后的盒子'}]})}}];return new Response('data: '+JSON.stringify({choices:[{index:0,delta:{role:'assistant',tool_calls},finish_reason:null}]})+'\n\ndata: '+JSON.stringify({choices:[{index:0,delta:{},finish_reason:'tool_calls'}]})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})};
  send(ui,'将盒子改名');await waitFor(()=>assert.ok(release));assert.equal(store.getState().pendingBatch.operations.length,2);fireEvent.click(ui.getByRole('button',{name:'停止生成'}));await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));assert.equal(store.getState().pendingResult.doc.nodes[0].id,target);assert.equal(store.getState().pendingResult.doc.nodes[0].name,'改名后的盒子');assert.equal(store.getState().doc.nodes.length,0);
  await act(async()=>release(new Response('data: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})));fireEvent.click(ui.getByRole('button',{name:'应用修改'}));assert.equal(store.getState().doc.nodes[0].name,'改名后的盒子');act(()=>store.getState().undo());assert.equal(store.getState().doc.nodes.length,0);
 });
 await test('no demo entry and legacy demo configuration cannot generate or consume input',async()=>{
  reset();store.setState({aiConfig:{...config,useMock:true}});const ui=mount();assert.equal(ui.queryByRole('button',{name:'体验离线演示'}),null);assert.ok(ui.getByRole('button',{name:'连接模型'}));send(ui,'创建长1.2米工作台');assert.equal(requests.length,0);assert.equal(store.getState().pendingBatch,null);assert.equal(store.getState().messages.length,0);assert.equal(ui.getByLabelText('建模指令').value,'创建长1.2米工作台');
 });
 await test('renderer failure never claims a rotatable ready preview, and confirmation remains usable',async()=>{
  reset();store.setState({viewportStatus:'error'});handler=async()=>new Response(JSON.stringify({choices:[{message:{content:output}}]}));const ui=mount();send(ui);await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));assert.ok(ui.getByText(/实时三维画面不可用/));assert.equal(ui.queryByText(/可旋转/),null);fireEvent.click(ui.getByRole('button',{name:'应用修改'}));assert.equal(store.getState().doc.nodes.length,1);assert.equal(store.getState().viewportStatus,'error');
 });
 await test('second request upstream 401 preserves draft and uses credentials on both calls without retrying',async()=>{
  reset();let n=0;handler=async()=>++n===1?new Response(JSON.stringify({choices:[{message:{content:output}}]})):new Response('{"error":{"message":"Unauthorized"}}',{status:401});const ui=mount();send(ui);await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));const draft=store.getState().pendingResult.doc;send(ui,'继续改成红色');await waitFor(()=>assert.equal(requests.length,2));await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));assert.deepEqual(store.getState().pendingResult.doc,draft);assert.equal(store.getState().doc.nodes.length,0);assert.match(store.getState().messages.at(-1).text,/401|密钥|Key/);assert.equal(requests.length,2);for(const [,init] of requests)assert.equal(new Headers(init.headers).get('authorization'),'Bearer mock-test');
 });
 await test('demo parser does not turn ambiguous or negated requests into creation and renames without adding the linking word',async()=>{const {parseInput}=await server.ssrLoadModule('/tests/fixtures/mockModel.ts');for(const text of ['工作台变红','不要创建工作台','改成绿色','创建一个不要背板的工作台'])assert.equal(parseInput(text,[]).operations.length,0);const result=parseInput('重命名为立柱',['target']);assert.equal(result.operations[0].name,'立柱');assert.equal(parseInput('创建一个工作台',[]).operations.length,15)});
 await test('Pi renderer-unavailable explicit data submission returns one-request stage and keeps explicit confirmation undoable',async()=>{
  reset();store.setState({viewportStatus:'error',aiConfig:{...config,agentMode:'pi',stream:true}});handler=async()=>firstDraftResponse(true);const ui=mount();send(ui,'创建工作台');await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));assert.equal(requests.length,1);assert.equal(store.getState().pendingBatch.incomplete,true);assert.equal(store.getState().doc.nodes.length,0);assert.match(store.getState().pendingBatch.summary,/未经视觉验收/);fireEvent.click(ui.getByRole('button',{name:'应用修改'}));assert.equal(store.getState().doc.nodes.length,1);assert.equal(requests.length,1);act(()=>store.getState().undo());assert.equal(store.getState().doc.nodes.length,0);
 });
 console.log(`${passed} chat component checks passed; all API calls mocked`);
} finally {cleanup();await server.close();dom.window.close()}
