import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import React from 'react';
import { createServer } from 'vite';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'https://example.test'});
for(const name of ['window','document','HTMLElement','Node','MutationObserver','Event','MouseEvent','localStorage','location']) Object.defineProperty(globalThis,name,{value:dom.window[name],configurable:true});
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
let handler;let requests=[];
globalThis.fetch=(...args)=>{requests.push(args);return handler(...args)};
const {render,fireEvent,waitFor,cleanup,act}=await import('@testing-library/react');
const server=await createServer({server:{middlewareMode:true},appType:'custom'});
let passed=0;
const test=async(name,fn)=>{await fn();passed++;console.log('PASS',name);cleanup()};
try {
 const {ChatPanel}=await server.ssrLoadModule('/src/ui/ChatPanel.tsx');
 const {useEditorStore:store,createInitialDoc}=await server.ssrLoadModule('/src/store.ts');
 const config={baseURL:'https://example.test/v1',apiKey:'mock-test',model:'vision-test',useMock:false,agentMode:'single'};
 const reset=()=>{store.setState({doc:createInitialDoc(),messages:[],composerText:'',composerImages:[],lastRun:null,aiStatus:'idle',aiError:null,aiConfig:config,pendingBatch:null,pendingResult:null,previewDoc:null,past:[],future:[]});requests=[]};
 const mount=()=>render(React.createElement(React.StrictMode,null,React.createElement(ChatPanel)));
 const send=(ui,text='创建一个盒子')=>{fireEvent.change(ui.getByLabelText('建模指令'),{target:{value:text}});fireEvent.click(ui.getByRole('button',{name:'发送',exact:true}))};
 const output=JSON.stringify({summary:'一个盒子',operations:[{op:'createPrimitive',name:'box',geometry:{type:'box',params:{width:1,height:1,depth:1}}}]});
 await test('missing configuration preserves draft and does not create misleading sent message',async()=>{reset();store.setState({aiConfig:null});const ui=mount();send(ui);assert.equal(ui.getByLabelText('建模指令').value,'创建一个盒子');assert.equal(store.getState().messages.length,0);assert.equal(requests.length,0)});
 await test('waiting visible, drafting allowed, duplicate send blocked, stop aborts and stale response ignored',async()=>{reset();let release;handler=()=>new Promise(r=>release=r);const ui=mount();send(ui);await waitFor(()=>assert.equal(requests.length,1));assert.ok(ui.getByText('请求已发起，等待模型响应'));fireEvent.change(ui.getByLabelText('建模指令'),{target:{value:'下一条草稿'}});fireEvent.keyDown(ui.getByLabelText('建模指令'),{key:'Enter'});assert.equal(requests.length,1);fireEvent.click(ui.getByRole('button',{name:'停止生成'}));assert.equal(requests[0][1].signal.aborted,true);await act(async()=>release(new Response(JSON.stringify({choices:[{message:{content:output}}]}))));assert.equal(store.getState().pendingBatch,null);assert.equal(ui.getByLabelText('建模指令').value,'下一条草稿');assert.equal(store.getState().doc.nodes.length,0)});
 await test('real stream progress counts characters and keeps scene unchanged until confirmation',async()=>{reset();let writer;handler=async()=>new Response(new ReadableStream({start(c){writer=c}}),{headers:{'content-type':'text/event-stream'}});const ui=mount();send(ui);await waitFor(()=>assert.ok(writer));const enc=new TextEncoder();const chunk=t=>enc.encode('data: '+JSON.stringify({choices:[{delta:{content:t}}]})+'\n\n');await act(async()=>writer.enqueue(chunk(output.slice(0,20))));assert.ok(ui.getByText('正在接收模型输出'));assert.ok(ui.getByText(/收到 20 字符/));assert.equal(store.getState().doc.nodes.length,0);await act(async()=>{writer.enqueue(chunk(output.slice(20)));writer.enqueue(enc.encode('data: [DONE]\n\n'));writer.close()});await waitFor(()=>assert.ok(ui.getByRole('button',{name:'确认应用'})));assert.equal(store.getState().doc.nodes.length,0);fireEvent.click(ui.getByRole('button',{name:'确认应用'}));assert.equal(store.getState().doc.nodes.length,1);assert.equal(store.getState().messages.at(-1).outcome,'applied');assert.ok(ui.getByText(/已应用/))});
 await test('discard records outcome and failure restores text for explicit retry',async()=>{reset();handler=async()=>new Response(JSON.stringify({choices:[{message:{content:output}}]}));let ui=mount();send(ui);await waitFor(()=>assert.ok(ui.getByRole('button',{name:'放弃预览'})));fireEvent.click(ui.getByRole('button',{name:'放弃预览'}));assert.equal(store.getState().messages.at(-1).outcome,'discarded');assert.equal(store.getState().doc.nodes.length,0);handler=async()=>{throw new TypeError('Failed to fetch')};send(ui,'重新创建');await waitFor(()=>assert.ok(ui.getByRole('button',{name:'恢复指令重试'})));fireEvent.click(ui.getByRole('button',{name:'恢复指令重试'}));assert.equal(ui.getByLabelText('建模指令').value,'重新创建')});
 await test('follow-up includes previous reference and shows thumbnail',async()=>{reset();store.setState({messages:[{id:'photo',role:'user',text:'参考图',images:['data:image/jpeg;base64,test'],createdAt:Date.now()}]});handler=async()=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({summary:'请提供尺寸',operations:[]})}}]}));const ui=mount();send(ui,'保持比例');await waitFor(()=>assert.equal(store.getState().aiStatus,'idle'));const body=JSON.parse(requests[0][1].body);assert.ok(body.messages.at(-1).content.some(p=>p.type==='image_url'));assert.ok(ui.getByAltText('参考图 1'));assert.equal(store.getState().doc.nodes.length,0)});
 await test('timeout aborts transport and allows explicit retry; late replies cannot create preview',async()=>{reset();let release;handler=()=>new Promise(r=>release=r);const realSet=globalThis.setTimeout;globalThis.setTimeout=(fn,ms,...args)=>realSet(fn,ms===180000?20:ms,...args);try{const ui=mount();send(ui);await waitFor(()=>assert.equal(store.getState().aiStatus,'error'));assert.match(store.getState().aiError,/3 分钟/);assert.equal(requests[0][1].signal.aborted,true);await act(async()=>release(new Response(JSON.stringify({choices:[{message:{content:output}}]}))));assert.equal(store.getState().pendingBatch,null);}finally{globalThis.setTimeout=realSet}});
 await test('reference reuse can be disabled and non-stream mode is explicitly sent',async()=>{reset();store.setState({aiConfig:{...config,stream:false},messages:[{id:'photo',role:'user',text:'old',images:['data:image/jpeg;base64,test'],createdAt:Date.now()}]});handler=async()=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({summary:'ok',operations:[]})}}]}));const ui=mount();fireEvent.click(ui.getByRole('checkbox',{name:/沿用最近参考图/}));send(ui,'独立任务');await waitFor(()=>assert.equal(requests.length,1));const body=JSON.parse(requests[0][1].body);assert.equal(body.stream,false);assert.equal(typeof body.messages.at(-1).content,'string');await waitFor(()=>assert.equal(store.getState().aiStatus,'idle'))});
 await test('ChatPanel integrates the production Pi loop and keeps draft separate until user confirms',async()=>{
   reset();store.setState({aiConfig:{...config,agentMode:'pi',stream:true}});
   const {registerSceneCapture}=await server.ssrLoadModule('/src/scene/capture.ts');const unregister=registerSceneCapture(async()=> 'data:image/jpeg;base64,YWJj');
   let n=0;handler=async()=>{n++;const actions=n===1?[['plan_model',{steps:['建主体','检查'],assumptions:'估算'}],['edit_scene',{summary:'create',operations:JSON.parse(output).operations}],['capture_view',{view:'perspective'}]]:[['review_model',{observations:'已经查看外形比例',issues:[]}],['submit_preview',{summary:'Pi生成预览',remainingIssues:[]}]];const tc=actions.map(([name,args],i)=>({index:i,id:`ui_${n}_${i}`,type:'function',function:{name,arguments:JSON.stringify(args)}}));return new Response('data: '+JSON.stringify({choices:[{index:0,delta:{role:'assistant',tool_calls:tc},finish_reason:null}]})+'\n\ndata: '+JSON.stringify({choices:[{index:0,delta:{},finish_reason:'tool_calls'}]})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})};
   try{const ui=mount();send(ui);await waitFor(()=>assert.ok(ui.getByRole('button',{name:'确认应用'})),{timeout:5000});assert.equal(n,2);assert.equal(store.getState().doc.nodes.length,0);assert.equal(store.getState().previewDoc.nodes.length,1);assert.ok(ui.getByText(/Pi 执行记录/));fireEvent.click(ui.getByRole('button',{name:'确认应用'}));assert.equal(store.getState().doc.nodes.length,1);}finally{unregister()}
 });
 const firstDraftResponse=()=>{const actions=[['plan_model',{steps:['主要设备布局','复核'],assumptions:'按阶段完成',design:{flow:['加工'],layout:'设备沿操作通道依次安排',equipment:[{name:'加工设备',count:1,features:['加工空间']}],checks:['比例与通道'],composition:{zones:[{name:'生产区',purpose:'加工'}],connections:[],support:[],palette:['灰蓝'],presentation:'统一比例和材质层次'}} }],['edit_scene',{summary:'阶段主体',operations:JSON.parse(output).operations}]];const tool_calls=actions.map(([name,args],i)=>({index:i,id:`checkpoint_${i}`,type:'function',function:{name,arguments:JSON.stringify(args)}}));return new Response('data: '+JSON.stringify({choices:[{index:0,delta:{role:'assistant',tool_calls},finish_reason:null}]})+'\n\ndata: '+JSON.stringify({choices:[{index:0,delta:{},finish_reason:'tool_calls'}]})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})};
 await test('unfinished Pi draft remains visible, explicitly retained then continued without automatic calls',async()=>{
  reset();store.setState({aiConfig:{...config,agentMode:'pi',stream:true}});let n=0;handler=async()=>++n===1?firstDraftResponse():new Response('data: '+JSON.stringify({choices:[{index:0,delta:{content:'稍后完善'},finish_reason:null}]})+'\n\ndata: '+JSON.stringify({choices:[{index:0,delta:{},finish_reason:'stop'}]})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}});
  const ui=mount();send(ui,'创建完整车间');await waitFor(()=>assert.ok(ui.getByRole('button',{name:'保留此阶段'})),{timeout:5000});assert.equal(store.getState().doc.nodes.length,0);assert.equal(store.getState().previewDoc.nodes.length,1);assert.equal(store.getState().pendingBatch.incomplete,true);fireEvent.click(ui.getByRole('button',{name:'保留此阶段'}));assert.equal(store.getState().doc.nodes.length,1);assert.match(ui.getByLabelText('建模指令').value,/继续完成原任务：创建完整车间/);assert.equal(n,5);act(()=>store.getState().undo());assert.equal(store.getState().doc.nodes.length,0);
 });
 for(const mode of ['stop','timeout'])await test(`Pi ${mode} preserves successful checkpoint and ignores late reply`,async()=>{
  reset();store.setState({aiConfig:{...config,agentMode:'pi',stream:true}});let n=0,release;handler=async()=>++n===1?firstDraftResponse():new Promise(r=>release=r);
  const realSet=globalThis.setTimeout;if(mode==='timeout')globalThis.setTimeout=(fn,ms,...args)=>realSet(fn,ms===180000?100:ms,...args);
  try{const ui=mount();send(ui);await waitFor(()=>assert.ok(release));if(mode==='stop')fireEvent.click(ui.getByRole('button',{name:'停止生成'}));await waitFor(()=>assert.ok(ui.getByRole('button',{name:'保留此阶段'})));assert.equal(store.getState().doc.nodes.length,0);assert.equal(store.getState().previewDoc.nodes.length,1);const requestId=store.getState().pendingBatch.requestId;await act(async()=>release(new Response('data: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})));assert.equal(store.getState().pendingBatch.requestId,requestId);fireEvent.click(ui.getByRole('button',{name:'放弃预览'}));assert.equal(store.getState().pendingBatch,null);assert.equal(store.getState().doc.nodes.length,0);}finally{globalThis.setTimeout=realSet}
 });
 await test('Pi active stream outlives the idle window, then pauses only when activity stops',async()=>{
  reset();store.setState({aiConfig:{...config,agentMode:'pi',stream:true}});
  let n=0,body;handler=async()=>++n===1?firstDraftResponse():new Response(new ReadableStream({start(c){body=c}}),{headers:{'content-type':'text/event-stream'}});
  const realSet=globalThis.setTimeout;globalThis.setTimeout=(fn,ms,...args)=>realSet(fn,ms===180000?180:ms,...args);
  try{
   const ui=mount();send(ui);await waitFor(()=>assert.ok(body));
   for(let i=0;i<8;i++)await act(async()=>{body.enqueue(new TextEncoder().encode('data: '+JSON.stringify({choices:[{index:0,delta:{content:'继续细化'},finish_reason:null}]})+'\n\n'));await new Promise(r=>realSet(r,60));});
   assert.equal(store.getState().aiStatus,'generating');assert.equal(store.getState().pendingBatch.incomplete,true);
   await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));assert.match(store.getState().pendingBatch.summary,/连续3分钟/);assert.equal(store.getState().previewDoc.nodes.length,1);
   assert.equal(requests.at(-1)[1].signal.aborted,true);
  }finally{globalThis.setTimeout=realSet}
 });
 await test('preview comparison switches displayed document only and requires after-view before apply',async()=>{
  reset();handler=async()=>new Response(JSON.stringify({choices:[{message:{content:output}}]}));const ui=mount();send(ui);await waitFor(()=>assert.equal(store.getState().aiStatus,'previewing'));
  assert.ok(ui.getByText(/修改对比：新增 1/));const pending=store.getState().pendingResult.doc;fireEvent.click(ui.getByRole('button',{name:'查看修改前'}));assert.equal(store.getState().previewDoc.nodes.length,0);assert.equal(store.getState().pendingResult.doc,pending);assert.equal(ui.getByRole('button',{name:'确认应用'}).disabled,true);fireEvent.click(ui.getByRole('button',{name:'查看修改后'}));assert.equal(store.getState().previewDoc.nodes.length,1);fireEvent.click(ui.getByRole('button',{name:'确认应用'}));assert.equal(store.getState().doc.nodes.length,1);
 });
 await test('selected-object guard also protects single-call compatibility mode',async()=>{
  reset();const {applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts');const {parseModelResponse}=await server.ssrLoadModule('/src/ai/provider.ts');const d=applyBatch(createInitialDoc(),parseModelResponse(output)).doc;store.setState({doc:d,selection:[d.nodes[0].id]});handler=async()=>new Response(JSON.stringify({choices:[{message:{content:output}}]}));const ui=mount();assert.equal(ui.getByRole('checkbox',{name:/仅修改选中对象/}).checked,true);send(ui,'把选中设备变蓝');await waitFor(()=>assert.equal(store.getState().aiStatus,'error'));assert.match(store.getState().aiError,/不允许新增/);assert.deepEqual(store.getState().doc,d);
 });
 await test('preset preview entry points are absent',async()=>{reset();const ui=mount();assert.equal(ui.queryByRole('button',{name:/预览.*无需模型/}),null);assert.equal(requests.length,0)});
 await test('machining request does not populate a preset before model output',async()=>{reset();store.setState({aiConfig:{...config,agentMode:'pi',stream:true}});let release;handler=()=>new Promise(r=>release=r);const ui=mount();send(ui,'做一个机加工产线车间沙盘');await waitFor(()=>assert.ok(release));assert.equal(store.getState().previewDoc,null);assert.equal(store.getState().doc.nodes.length,0);fireEvent.click(ui.getByRole('button',{name:'停止生成'}));await act(async()=>release(new Response('data: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}})));assert.equal(store.getState().pendingBatch,null);});
 console.log(`${passed} chat component checks passed; all API calls mocked`);
} finally {cleanup();await server.close();dom.window.close()}
