import assert from 'node:assert/strict';import {createServer} from 'vite';
const server=await createServer({server:{middlewareMode:true},appType:'custom'});let passed=0;const test=(n,f)=>{f();passed++;console.log('PASS',n)};
try{const {checkEditScope,sceneChanges}=await server.ssrLoadModule('/src/domain/editScope.ts');const {createInitialDoc}=await server.ssrLoadModule('/src/store.ts');const {applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts');const t={position:[0,.5,0],scale:[1,1,1],rotationQuaternion:[0,0,0,1]};const op={op:'createPrimitive',name:'A',geometry:{type:'box',params:{width:1,height:1,depth:1}},transform:t,parentId:null,materialId:'mat_white'};const before=applyBatch(createInitialDoc(),{operations:[op,{...op,name:'B'}]}).doc;
test('scope guard protects unselected nodes, global materials, additions, and invalid selections',()=>{const after=structuredClone(before);after.nodes[1].name='changed';assert.ok(checkEditScope(before,after,{nodeIds:[before.nodes[0].id]}).length);const material=structuredClone(before);material.materials.find(m=>m.id==='mat_white').baseColor='#123456';assert.ok(checkEditScope(before,material,{nodeIds:[before.nodes[0].id]}).length);assert.ok(checkEditScope(before,applyBatch(before,{operations:[op]}).doc,{nodeIds:[before.nodes[0].id]}).length);assert.ok(checkEditScope(before,before,{nodeIds:[]}).length)});
test('placement lock rejects position and orientation changes but permits scale and appearance',()=>{for(const key of ['position','rotationQuaternion']){const after=structuredClone(before);after.nodes[0].transform[key][0]=1;assert.ok(checkEditScope(before,after,{lockPlacement:true}).length)}const after=structuredClone(before);after.nodes[0].transform.scale=[2,1,1];assert.equal(checkEditScope(before,after,{lockPlacement:true}).length,0)});
test('diff reports additions, material and geometry edits, removals, and unchanged-node exclusion',()=>{const after=structuredClone(before);after.nodes[0].geometry.params.width=2;after.nodes[0].materialId='mat_blue';after.nodes.splice(1,1);after.nodes.push({...structuredClone(before.nodes[1]),id:'new-node',name:'C'});const changes=sceneChanges(before,after);assert.equal(changes.length,3);assert.ok(changes.find(c=>c.kind==='modified').fields.includes('颜色/材质'));assert.ok(changes.find(c=>c.kind==='modified').fields.includes('形状/尺寸'));assert.equal(sceneChanges(before,before).length,0)});
const {conversationScope}=await server.ssrLoadModule('/src/domain/conversationScope.ts');
test('conversation scope is global by default and narrows only for an explicit selected-object instruction',()=>{const selected=[before.nodes[0].id];assert.deepEqual(conversationScope('给人物补动作',before,selected),{});assert.deepEqual(conversationScope('开始',before,selected),{});assert.deepEqual(conversationScope('只修改选中对象的颜色',before,selected).nodeIds,selected);assert.equal(conversationScope('不要只修改选中对象，其他也要改',before,selected).nodeIds,undefined);assert.equal(conversationScope('只修改选中对象以外的设备',before,selected).nodeIds,undefined);assert.equal(conversationScope('开始',before,selected,true).lockPlacement,true);});
test('explicit motion overrides an older placement toggle but negative and local instructions remain respected',()=>{const selected=[before.nodes[0].id];assert.equal(conversationScope('移动这台设备到左边',before,selected,true).lockPlacement,undefined);assert.equal(conversationScope('不要移动设备，只改颜色',before,selected,true).lockPlacement,true);const local=conversationScope('只移动选中对象',before,selected,true);assert.deepEqual(local.nodeIds,selected);assert.equal(local.lockPlacement,undefined);const continued=conversationScope('开始吧',before,selected,true,[{role:'user',text:'只移动选中对象'}]);assert.deepEqual(continued,local);});
test('colloquial explicit movement unlocks while negatives quotes questions and unrelated current turns stay locked',()=>{
 for(const text of ['向左挪两米','往右移两米','把设备挪到右边','旋转90度'])assert.equal(conversationScope(text,before,[],true).lockPlacement,undefined,text);
 for(const text of ['创建挪威风格的车间','不要向左挪两米','保持位置，只改颜色','是否向左挪两米？','标注“向左挪两米”','只改颜色'])assert.equal(conversationScope(text,before,[],true,[{role:'user',text:'向左挪两米'}]).lockPlacement,true,text);
 const scope=conversationScope('只挪选中对象向左两米',before,[before.nodes[0].id],true);assert.deepEqual(scope.nodeIds,[before.nodes[0].id]);assert.equal(scope.lockPlacement,undefined);
});
 const {userEditScope}=await server.ssrLoadModule('/src/domain/conversationScope.ts');
 test('explicit UI selection boundary cannot be widened by prompt or inferred component expansion',()=>{const selected=[before.nodes[0].id];for(const text of ['修改全场景','不要只修改选中对象，其他也要改','只修改这台设备'])assert.deepEqual(userEditScope(text,before,selected,'selection').nodeIds,selected);});
 test('empty or stale explicit selection fails closed instead of reverting to whole scene',()=>{assert.throws(()=>userEditScope('创建模型',before,[],'selection'),/选择/);assert.throws(()=>userEditScope('改颜色',before,['stale'],'selection'),/选择/);});
 test('whole-scene mode keeps literal user restrictions and selected edits retain placement intent',()=>{assert.deepEqual(userEditScope('改全部',before,[],'scene'),{});assert.deepEqual(userEditScope('只修改选中对象',before,[before.nodes[0].id],'scene').nodeIds,[before.nodes[0].id]);assert.equal(userEditScope('不要移动，只改颜色',before,[before.nodes[0].id],'selection',true).lockPlacement,true);});
 console.log(`${passed} scope and diff checks passed`);
}finally{await server.close()}
