import assert from 'node:assert/strict';import fs from 'node:fs';import {createServer} from 'vite';
const s=await createServer({server:{middlewareMode:true},appType:'custom'});let count=0;const test=async(n,f)=>{await f();console.log('PASS',n);count++};
try{
const {buildHandPose,HAND_POSES}=await s.ssrLoadModule('/src/scene/handPose.ts');const {validateGeometry}=await s.ssrLoadModule('/src/domain/types.ts');const {createInitialDoc}=await s.ssrLoadModule('/src/store.ts');const {applyBatch}=await s.ssrLoadModule('/src/domain/commands.ts');const {interactionTargets}=await s.ssrLoadModule('/src/domain/interactionQuality.ts');const {validateDetailReview,DETAIL_CRITERIA}=await s.ssrLoadModule('/src/domain/detailAcceptance.ts');const args={wrist:[0,1,0],forward:[0,0,-1],dorsal:[0,1,0],handedness:'right',pose:'power'};
await test('all hand poses expose five connected digits, mesh normals and UVs',()=>{for(const pose of HAND_POSES){const h=buildHandPose({...args,pose});assert.deepEqual(validateGeometry(h.geometry),[]);assert.equal(h.joints.length,5);assert.equal(new Set(h.joints.map(x=>x.digit)).size,5);assert.ok(h.geometry.params.uvs.length);assert.ok(h.joints.every(x=>x.points.every(p=>p.every(Number.isFinite))));}});
await test('hand placement and scale equivariance retain exact grip anchors',()=>{const a=buildHandPose(args),b=buildHandPose({...args,wrist:[2,3,4],scale:2});for(let i=0;i<3;i++)assert.ok(Math.abs(b.gripCenter[i]-([2,3,4][i]+2*(a.gripCenter[i]-args.wrist[i])))<1e-9)});
await test('left and right hands mirror thumb and digit ordering',()=>{const a=buildHandPose(args),b=buildHandPose({...args,handedness:'left'});a.joints.forEach((j,i)=>j.points.forEach((p,k)=>{assert.equal(p[0],-b.joints[i].points[k][0]);assert.equal(p[1],b.joints[i].points[k][1]);assert.equal(p[2],b.joints[i].points[k][2])}))});
await test('invalid or parallel axes and implausible grip sizes reject',()=>{for(const x of [{forward:[0,0,0]},{dorsal:[0,0,1]},{scale:0},{gripDiameter:.5},{pose:'invented'},{wrist:[Infinity,0,0]}])assert.throws(()=>buildHandPose({...args,...x}));});
let d=createInitialDoc();const h=buildHandPose(args);const created=applyBatch(d,{operations:[{op:'createAssembly',name:'任意角色',sceneRole:'person',parts:[{name:'hand',geometry:h.geometry,materialId:'mat_gray',transform:{position:[0,0,0],scale:[1,1,1],rotationQuaternion:[0,0,0,1]}}]}]});assert.deepEqual(created.errors,[]);d=created.doc;
await test('pose replacement keeps assembly membership and unrelated geometry',()=>{const n=d.nodes[0];const next=applyBatch(d,{operations:[{op:'replaceAssemblyParts',targetId:n.id,partIds:[n.id],parts:[{name:'articulated hand',geometry:buildHandPose({...args,pose:'point'}).geometry,materialId:n.materialId,transform:n.transform}]}]});assert.deepEqual(next.errors,[]);assert.equal(next.doc.nodes[0].assemblyId,n.assemblyId);assert.equal(next.doc.nodes[0].sceneRole,'person')});
await test('any person requires hand-specific evidence; full-body screenshots are insufficient',()=>{const n=d.nodes[0],r={componentId:n.assemblyId,revision:d.revision,visualEvidence:true,checks:DETAIL_CRITERIA.map(c=>({criterion:c.key,status:'pass',evidence:'实际画面和部件检查依据',nodeIds:[n.id]}))};assert.ok(validateDetailReview(d,r).some(x=>x.includes('两个局部视角')));assert.deepEqual(validateDetailReview(d,{...r,interactionEvidence:true}),[]);const t=interactionTargets(d);assert.equal(t.length,1);assert.equal(t[0].accepted,false);assert.ok(t[0].nodeIds.includes(n.id));});
console.log(count+' hand interaction checks passed');
}finally{await s.close()}
