import assert from 'node:assert/strict';import fs from 'node:fs';import {createServer} from 'vite';
const server=await createServer({server:{middlewareMode:true},appType:'custom'});let n=0;const test=async(name,f)=>{await f();n++;console.log('PASS',name)};
try{const {inspectGlbBytes,importGlb}=await server.ssrLoadModule('/src/scene/importGlb.ts');const {validateGeometry}=await server.ssrLoadModule('/src/domain/types.ts');const {createInitialDoc}=await server.ssrLoadModule('/src/store.ts');const {buildSceneContext}=await server.ssrLoadModule('/src/ai/provider.ts');const {serializeProject,parseProject}=await server.ssrLoadModule('/src/domain/project.ts');const {buildExportScene,exportGlb}=await server.ssrLoadModule('/src/scene/export.ts');const {applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts');
const pack=j=>{let s=JSON.stringify(j);s+=' '.repeat((4-s.length%4)%4);const b=new ArrayBuffer(20+s.length),v=new DataView(b);v.setUint32(0,0x46546c67,true);v.setUint32(4,2,true);v.setUint32(8,b.byteLength,true);v.setUint32(12,s.length,true);v.setUint32(16,0x4e4f534a,true);new Uint8Array(b,20).set(new TextEncoder().encode(s));return b};
await test('GLB preflight rejects external buffers textures skins compression and corrupt lengths',()=>{for(const j of [{buffers:[{uri:'https://x.test/secret'}]},{textures:[{}]},{images:[{}]},{skins:[{}]},{extensionsRequired:['KHR_draco_mesh_compression']}])assert.throws(()=>inspectGlbBytes(pack({asset:{version:'2.0'},...j})));assert.throws(()=>inspectGlbBytes(new ArrayBuffer(8)));});
await test('mesh data enforces indices numbers and budgets',()=>{const g={type:'mesh',params:{positions:[0,0,0,1,0,0,0,1,0],indices:[0,1,2]}};assert.equal(validateGeometry(g).length,0);for(const p of [{positions:[NaN,0,0]},{indices:[0,1,300]},{normals:[0,0,0]},{indices:[0,1]}])assert.ok(validateGeometry({...g,params:{...g.params,...p}}).length);});
const initial=createInitialDoc();let d=applyBatch(initial,{operations:[{op:'createPrimitive',name:'mesh proof',geometry:{type:'profile',params:{points:[[0,0],[1,0],[.8,1],[.2,1]],depth:.4}},parentId:null,materialId:'mat_gray',transform:{position:[1,2,3],rotationQuaternion:[0,0,0,1],scale:[1,1,1]}}]}).doc;
globalThis.FileReader=class{readAsArrayBuffer(b){b.arrayBuffer().then(r=>{this.result=r;this.onloadend?.()})}};
await test('actual GLB roundtrip imports static triangle geometry and transforms',async()=>{const bytes=await exportGlb(d);const result=await importGlb(bytes,'proof.glb');assert.ok(result.doc.nodes.length);const node=result.doc.nodes[0];assert.equal(node.geometry.type,'mesh');assert.deepEqual(node.transform.position,[1,2,3]);assert.deepEqual(node.transform.scale,[1,1,1]);d=result.doc;const round=parseProject(serializeProject(d));assert.equal(round.nodes[0].geometry.params.indices.length,node.geometry.params.indices.length);});
await test('AI scene context never sends mesh vertex arrays',()=>{const context=buildSceneContext(d,[]);assert.match(context.nodes[0].desc,/导入网格/);assert.ok(!JSON.stringify(context).includes('indices'));assert.ok(JSON.stringify(context).length<2000);});
await test('imported mesh supports color transform and reexport',async()=>{const r=applyBatch(d,{operations:[{op:'setAppearance',targetId:d.nodes[0].id,baseColor:'#334455'},{op:'translate',targetId:d.nodes[0].id,space:'world',mode:'delta',value:[2,0,0]}]});assert.equal(r.errors.length,0);assert.equal(r.doc.nodes[0].transform.position[0],3);const out=await exportGlb(r.doc);assert.ok(out.byteLength>100);});
if(process.env.MESH_QA){const b=fs.readFileSync(process.env.MESH_QA);const result=await importGlb(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'machining-cell.glb');fs.writeFileSync('/workspace/scratch/25da00f7a020/mesh-quality-prototype/imported.chat3d.json',serializeProject(result.doc));console.log('QA imported',result.doc.nodes.length,'parts in',new Set(result.doc.nodes.map(x=>x.assemblyId)).size,'groups');}
console.log(n+' mesh import checks passed');}finally{await server.close()}
