import assert from 'node:assert/strict';import {createAssistantMessageEventStream} from '@earendil-works/pi-ai';import {createServer} from 'vite';import {CylinderGeometry} from 'three';
const server=await createServer({server:{middlewareMode:true},appType:'custom'});let count=0;const test=async(n,f)=>{await f();console.log('PASS',n);count++};
try{const {bendExistingMesh}=await server.ssrLoadModule('/src/domain/meshBend.ts'),{createInitialDoc}=await server.ssrLoadModule('/src/store.ts'),{applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts'),{assertPreservedAssetShape,hasAssetPoseChange}=await server.ssrLoadModule('/src/domain/preservedPose.ts');
const g=new CylinderGeometry(.05,.05,1,12,20,true);const geometry={type:'mesh',params:{positions:Array.from(g.attributes.position.array),indices:Array.from(g.index.array),uvs:Array.from(g.attributes.uv.array),normals:Array.from(g.attributes.normal.array)}};g.dispose();const transform={position:[0,0,0],rotationQuaternion:[0,0,0,1],scale:[1,1,1]};const doc=applyBatch(createInitialDoc(),{operations:[{op:'createAssembly',name:'人员',parts:[{name:'连续袖管',geometry,transform,materialId:'mat_gray'},{name:'手',geometry:{type:'box',params:{width:.1,height:.1,depth:.1}},transform:{...transform,position:[0,.55,0]},materialId:'mat_gray'}]}]}).doc;for(const n of doc.nodes)n.modelAsset={id:'asset',version:1,instanceId:'instance',sourceNodeId:n.id};const sleeve=doc.nodes[0],hand=doc.nodes[1],args={assemblyId:sleeve.assemblyId,nodeId:sleeve.id,pivot:[0,0,0],axis:[0,0,1],movingDirection:[0,1,0],blendWidth:.3,angle:20,followNodeIds:[hand.id]};
await test('continuous mesh bends with identical topology UVs IDs and fixed-end vertices',()=>{const before=JSON.stringify(doc),p=bendExistingMesh(doc,args),r=applyBatch(doc,{operations:p.commands});assert.equal(r.errors.length,0);const n=r.doc.nodes[0];assert.deepEqual(n.geometry.params.indices,geometry.params.indices);assert.deepEqual(n.geometry.params.uvs,geometry.params.uvs);assert.equal(n.geometry.params.positions.length,geometry.params.positions.length);for(let i=0;i<geometry.params.positions.length;i+=3)if(geometry.params.positions[i+1]<=-.15)assert.deepEqual(n.geometry.params.positions.slice(i,i+3),geometry.params.positions.slice(i,i+3));assert.equal(n.id,sleeve.id);assert.equal(n.materialId,sleeve.materialId);assert.equal(JSON.stringify(doc),before);assert.equal(hasAssetPoseChange(doc,r.doc,true),true);assert.equal(assertPreservedAssetShape(p.preservationBaseline,r.doc),2);assert.throws(()=>assertPreservedAssetShape(doc,r.doc));});
await test('downstream hand rotates with endpoint while unrelated geometry remains intact',()=>{const p=bendExistingMesh(doc,args),r=applyBatch(doc,{operations:p.commands});const h=r.doc.nodes[1];assert.deepEqual(h.geometry,hand.geometry);assert.ok(Math.abs(h.transform.position[0]+.55*Math.sin(Math.PI/9))<1e-9);});
await test('bad calibration foreign followers and excessive distortion reject without source changes',()=>{const before=JSON.stringify(doc);for(const patch of [{pivot:[0,10,0]},{axis:[0,1,0]},{blendWidth:0},{angle:180},{followNodeIds:[sleeve.id]},{followNodeIds:['foreign']},{blendWidth:.005,angle:90}])assert.throws(()=>bendExistingMesh(doc,{...args,...patch}));assert.equal(JSON.stringify(doc),before);});
await test('internally derived baseline still rejects material changes and overlays',()=>{const p=bendExistingMesh(doc,args),r=applyBatch(doc,{operations:p.commands});const corrupt=structuredClone(r.doc);corrupt.nodes[0].visible=false;assert.throws(()=>assertPreservedAssetShape(p.preservationBaseline,corrupt));});
const {runModelingAgent}=await server.ssrLoadModule('/src/ai/modelingAgent.ts');const stream=()=>{let i=0;return async()=>{const content=i++===0?[{type:'toolCall',id:'bend-call',name:'bend_existing_mesh',arguments:args}]:[{type:'text',text:'已弯曲，仍需外观检查'}];const message={role:'assistant',content,api:'openai-completions',provider:'mock',model:'mock',stopReason:i===1?'toolUse':'stop',timestamp:Date.now(),usage:{input:1,output:1,cacheRead:0,cacheWrite:0,totalTokens:2,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}}};const out=createAssistantMessageEventStream();queueMicrotask(()=>{out.push({type:'start',partial:message});out.push({type:'done',reason:message.stopReason,message})});return out}};
await test('agent applies derived bend through normal scope and preservation checks without visual acceptance',async()=>{const r=await runModelingAgent({text:'依据已标定肘部调整人员手臂姿态',document:doc,selection:[],config:{baseURL:'https://mock.invalid/v1',apiKey:'mock',model:'mock'},captureAvailable:()=>false,streamFn:stream()});assert.notDeepEqual(r.result.doc.nodes[0].geometry,doc.nodes[0].geometry);assert.deepEqual(r.result.doc.nodes[0].geometry.params.indices,geometry.params.indices);assert.equal(r.batch.incomplete,true);assert.equal(r.activity.toolCalls,1);});
console.log(count+' controlled mesh bend checks passed; not a visual or collision acceptance');
}finally{await server.close()}
