import {tmpdir} from 'node:os';import path from 'node:path';
import assert from 'node:assert/strict';import fs from 'node:fs';import {createServer} from 'vite';
const server=await createServer({server:{middlewareMode:true},appType:'custom'});let count=0;const test=async(n,f)=>{await f();console.log('PASS',n);count++};
try{
 const {MESH_CATALOG,loadMeshComponent}=await server.ssrLoadModule('/src/scene/meshCatalog.ts');const {createInitialDoc,useEditorStore:editor}=await server.ssrLoadModule('/src/store.ts');const {applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts');const {validateDocument}=await server.ssrLoadModule('/src/domain/types.ts');const {serializeProject,parseProject,MAX_PROJECT_BYTES}=await server.ssrLoadModule('/src/domain/project.ts');const {buildSceneContext}=await server.ssrLoadModule('/src/ai/provider.ts');const {checkEditScope}=await server.ssrLoadModule('/src/domain/editScope.ts');
 const fetcher=async url=>{assert.match(url,/^\/model-assets\/[a-z-]+\.glb$/);const b=fs.readFileSync('public'+url);return new Response(b,{status:200})};let doc=createInitialDoc();const place={vmc:[-9,0,-4],hmc:[-3.5,0,-4],gantry:[4.6,0,-4.7],cmm:[-9,0,4.3],cleaning:[-3.5,0,4.3],grinding:[2.2,0,4.3],packing:[8.3,0,4.3],rack:[11.2,0,-4],'production-worker':[-7.55,0,-2.5],'quality-worker':[-7.5,0,5.45],'warehouse-worker':[10.4,0,-2.1],'packing-worker':[8.6,0,5.35]};
 await test('all 12 detailed assets load, have real mesh parts and metadata, and form valid scene',async()=>{for(const entry of MESH_CATALOG){const a=await loadMeshComponent({key:entry.key,name:entry.name,position:place[entry.key]},undefined,fetcher);assert.equal(a.nodes.length,entry.parts);assert.ok(a.nodes.every(n=>n.geometry.type==='mesh'));assert.equal(new Set(a.nodes.map(n=>n.assemblyId)).size,1);const r=applyBatch(doc,{operations:[{op:'importMeshComponent',...a}]});assert.deepEqual(r.errors,[]);doc=r.doc;}assert.deepEqual(validateDocument(doc),[]);assert.equal(new Set(doc.nodes.map(n=>n.assemblyId)).size,12);assert.ok(doc.nodes.some(n=>n.name.includes('cable chain')));assert.ok(doc.nodes.some(n=>n.name.includes('carousel tool')));});
 await test('all catalogue meshes provide UVs and worker hems meet boot collars',async()=>{const {boundsFor}=await server.ssrLoadModule('/src/domain/sceneQuality.ts');const {Matrix4,Quaternion,Vector3}=await import('three');for(const entry of MESH_CATALOG){const d=await loadMeshComponent({key:entry.key,name:entry.name,position:[0,0,0]},undefined,fetcher);assert.ok(d.nodes.every(n=>n.geometry.params.uvs?.length===n.geometry.params.positions.length/3*2));if(entry.key.endsWith('worker')){const bounds=n=>boundsFor(n.geometry).applyMatrix4(new Matrix4().compose(new Vector3(...n.transform.position),new Quaternion(...n.transform.rotationQuaternion),new Vector3(...n.transform.scale)));const boots=d.nodes.filter(n=>n.name.includes('safety boot')).map(bounds),legs=d.nodes.filter(n=>n.name.includes('trouser leg')).map(bounds);assert.equal(legs.length,2);for(const leg of legs)assert.ok(boots.some(boot=>leg.intersectsBox(boot)));}}});
 await test('catalog rejects arbitrary URLs, missing keys and invalid transforms',async()=>{for(const args of [{key:'https://evil.test/x.glb'},{key:'vmc',scaleFactor:0},{key:'vmc',position:[NaN,0,0]}])await assert.rejects(()=>loadMeshComponent({key:'vmc',name:'x',position:[0,0,0],...args},undefined,fetcher));const ac=new AbortController();ac.abort();await assert.rejects(()=>loadMeshComponent({key:'vmc',name:'x',position:[0,0,0]},ac.signal,fetcher));});
 await test('full detailed scene remains portable under 20 MB and compact AI context omits triangles',()=>{const json=serializeProject(doc);const bytes=new TextEncoder().encode(json).length;assert.ok(bytes<MAX_PROJECT_BYTES);assert.equal(parseProject(json).nodes.length,doc.nodes.length);const context=JSON.stringify(buildSceneContext(doc,[]));assert.ok(!context.includes('positions'));assert.ok(!context.includes('indices'));console.log('Project bytes',bytes,'vertices',doc.nodes.reduce((sum,n)=>sum+n.geometry.params.positions.length/3,0));});
 await test('mesh import transaction rejects malformed data atomically and scope blocks unrelated additions',()=>{const a={nodes:[structuredClone(doc.nodes[0])],materials:doc.materials};a.nodes[0].geometry.params.indices=[99999999,0,1];const r=applyBatch(doc,{operations:[{op:'importMeshComponent',...a}]});assert.ok(r.errors.length);assert.equal(r.doc,doc);assert.ok(checkEditScope({...doc,nodes:doc.nodes.slice(0,1)},doc,{nodeIds:[doc.nodes[0].id]}).length);});
 await test('detailed assemblies support edits without replacing mesh, and full export roundtrips',async()=>{const target=doc.nodes[0];const r=applyBatch(doc,{operations:[{op:'translateAssembly',targetId:target.id,mode:'delta',value:[1,0,0]},{op:'setAppearance',targetId:target.id,baseColor:'#556677'}]});assert.deepEqual(r.errors,[]);assert.equal(r.doc.nodes[0].geometry.type,'mesh');globalThis.FileReader=class{readAsArrayBuffer(b){b.arrayBuffer().then(x=>{this.result=x;this.onloadend?.()})}};const {exportGlb}=await server.ssrLoadModule('/src/scene/export.ts');const glb=await exportGlb(doc);assert.ok(glb.byteLength>1000000);const output=process.env.MESH_BENCHMARK_DIR??path.join(tmpdir(),'chat3d-mesh-benchmark');fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'chat3d-generated.glb'),Buffer.from(glb));fs.writeFileSync(path.join(output,'chat3d-generated.json'),serializeProject(doc));});
 console.log(count+' mesh catalog checks passed');
}finally{await server.close()}
