import assert from 'node:assert/strict';
import {createServer as httpServer} from 'node:http';
import {createServer} from 'vite';
import {handleModelProxy,MAX_BODY} from '../server/model-proxy.mjs';
import {modelProxyMiddleware} from '../server/node-adapter.mjs';
let passed=0;const test=async(name,fn)=>{await fn();console.log('PASS',name);passed++;};
const root='https://discovery-api.intern-ai.org.cn/v1';
const request=(path='/models',patch={})=>new Request('https://app.test/api/model'+path,{method:path==='/models'?'GET':'POST',headers:{authorization:'Bearer test-only',origin:'https://app.test','x-chat3d-upstream':root,...(path==='/models'?{}:{'content-type':'application/json'}),...patch.headers},...(path==='/models'?{}:{body:'{"model":"test"}'}),...Object.fromEntries(Object.entries(patch).filter(([k])=>k!=='headers'))});
await test('proxy sends only approved endpoint and credential headers to upstream',async()=>{let seen;const r=await handleModelProxy(request('/models',{headers:{cookie:'private=do-not-forward','x-extra':'secret'}}),{fetchImpl:async(url,init)=>{seen={url,init};return new Response('{"data":[]}',{headers:{'content-type':'application/json','set-cookie':'do-not-propagate'}})}});assert.equal(r.status,200);assert.equal(r.headers.get('x-chat3d-proxy'),'1');assert.equal(r.headers.get('set-cookie'),null);assert.equal(seen.url,root+'/models');assert.equal(seen.init.headers.Authorization,'Bearer test-only');assert.equal(seen.init.headers.cookie,undefined);assert.equal(seen.init.headers.Origin,undefined);assert.equal(seen.init.redirect,'manual');await r.text();});
await test('proxy rejects unapproved targets, wrong methods, cross origin and missing keys without fetch',async()=>{let calls=0;const opts={fetchImpl:async()=>{calls++;throw Error()}};for(const req of [request('/models',{headers:{'x-chat3d-upstream':'http://127.0.0.1/v1'}}),request('/models',{headers:{origin:'https://evil.test'}}),request('/models',{headers:{authorization:''}}),request('/models',{method:'DELETE'}),request('/models?target=other'),request('/models',{headers:{'x-chat3d-upstream':root+'/../admin'}})])assert.ok((await handleModelProxy(req,opts)).status>=400);assert.equal(calls,0);});
await test('redirects never forward the key to another host and status401 stays401',async()=>{const r=await handleModelProxy(request(),{fetchImpl:async()=>new Response(null,{status:302,headers:{location:'https://evil.test'}})});assert.equal(r.status,502);assert.equal((await r.json()).error.code,'PROXY_REDIRECT_BLOCKED');const denied=await handleModelProxy(request(),{fetchImpl:async()=>new Response('{"error":"bad key"}',{status:401})});assert.equal(denied.status,401);await denied.text();});
await test('SSE chunks arrive incrementally and downstream cancel aborts upstream',async()=>{let source,signal;const r=await handleModelProxy(request('/chat/completions'),{fetchImpl:async(_u,init)=>{signal=init.signal;return new Response(new ReadableStream({start(c){source=c;c.enqueue(new TextEncoder().encode('data: first\n\n'));}}),{headers:{'content-type':'text/event-stream'}})}});const reader=r.body.getReader();assert.match(new TextDecoder().decode((await reader.read()).value),/first/);source.enqueue(new TextEncoder().encode('data: second\n\n'));assert.match(new TextDecoder().decode((await reader.read()).value),/second/);await reader.cancel();assert.equal(signal.aborted,true);});
await test('request limits reject oversized payload and slow upstream times out safely',async()=>{const big=await handleModelProxy(request('/chat/completions',{headers:{'content-length':String(MAX_BODY+1)}}));assert.equal(big.status,413);const timeout=await handleModelProxy(request(),{idleMs:10,fetchImpl:async(_u,{signal})=>new Promise((_r,reject)=>signal.addEventListener('abort',()=>reject(Error('abort'))))});assert.equal(timeout.status,504);});
await test('Node adapter serves real same-origin HTTP without exposing response cookies',async()=>{const middleware=modelProxyMiddleware({fetchImpl:async()=>new Response('{"data":[{"id":"test"}]}')});const server=httpServer((req,res)=>middleware(req,res,()=>res.writeHead(404).end()));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{const base='http://127.0.0.1:'+server.address().port;const r=await fetch(base+'/api/model/models',{headers:{authorization:'Bearer test-only','x-chat3d-upstream':root,origin:base}});assert.equal(r.status,200);assert.equal((await r.json()).data[0].id,'test');}finally{await new Promise(resolve=>server.close(resolve));}});
const vite=await createServer({server:{middlewareMode:true},appType:'custom'});
try{
 const {createBrowserProxyFetch}=await vite.ssrLoadModule('/src/ai/transport.ts');
 await test('web models and generation are always same-origin, preserving abort and body',async()=>{const calls=[];const proxy=createBrowserProxyFetch(async(...a)=>{calls.push(a);return new Response('{}',{headers:{'x-chat3d-proxy':'1'}})});const signal=new AbortController().signal;await proxy(root+'/models',{headers:{Authorization:'Bearer test-only'},signal});await proxy(root+'/chat/completions',{method:'POST',headers:{Authorization:'Bearer test-only','Content-Type':'application/json'},body:'{}',signal});assert.deepEqual(calls.map(c=>c[0]),['/api/model/models','/api/model/chat/completions']);assert.equal(calls[1][1].body,'{}');assert.equal(calls[1][1].signal,signal);assert.equal(calls[0][1].headers.get('X-Chat3d-Upstream'),root);});
 await test('static-only deployment and disallowed upstream return actionable errors without direct fallback',async()=>{let n=0;const proxy=createBrowserProxyFetch(async()=>{n++;return new Response('<html>')});await assert.rejects(()=>proxy(root+'/models'),/未接入模型代理/);assert.equal(n,1);const denied=createBrowserProxyFetch(async()=>new Response(JSON.stringify({error:{code:'PROXY_UPSTREAM_DENIED',message:'部署管理员配置一次'}}),{status:403,headers:{'x-chat3d-proxy':'1'}}));await assert.rejects(()=>denied(root+'/models'),/配置一次/);});
}finally{await vite.close();}
console.log(`${passed} model proxy checks passed with mock upstream and real local HTTP`);
