import assert from 'node:assert/strict';
import {createServer} from 'vite';
import {createAssistantMessageEventStream} from '@earendil-works/pi-ai';
const server=await createServer({server:{middlewareMode:true},appType:'custom'});
let passed=0;let forceTransportError=false;
const test=async(name,fn)=>{await fn();passed++;console.log('PASS',name)};
try{
 const {runModelingAgent,compactAgentContext}=await server.ssrLoadModule('/src/ai/modelingAgent.ts');
 const {normalizeModelingRequestText,normalizeModelingRequestMessages}=await server.ssrLoadModule('/src/ai/modelingRequest.ts');
 const {createInitialDoc,useEditorStore:store}=await server.ssrLoadModule('/src/store.ts');
 const {applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts');
 const cfg={baseURL:'https://mock.invalid/v1',apiKey:'mock-only',model:'mock-vision-tools',useMock:false};
 const create={op:'createPrimitive',parentId:null,transform:{position:[0,0,0],rotationQuaternion:[0,0,0,1],scale:[1,1,1]},name:'body',tempId:'body',geometry:{type:'roundedPlate',params:{width:1.1,height:.25,depth:.8,cornerRadius:.2}},materialId:'mat_white'};
 const design={flow:['加工','检测'],layout:'设备面向操作通道，人员与物料流向明确',equipment:[{name:'按需求设计的设备',count:2,features:['有独立加工空间','明确操作面']}],checks:['检查通道连续性','检查设备近景'],composition:{zones:[{name:'生产区',purpose:'加工与检测'}],connections:[],support:[],palette:['灰蓝'],presentation:'设备与地面区分，完整沙盘取景'}};
 const plan={name:'plan_model',args:{steps:['主体','截图检查'],assumptions:'尺寸按图估算',design}};
 const edit={name:'edit_scene',args:{summary:'创建主体',operations:[create]}};
 const capture={name:'capture_view',args:{view:'perspective'}};
 const review={name:'review_model',args:{observations:'检查了外形比例与部件关系',issues:[]}};
 const inspect={name:'inspect_scene',args:{}};
 const submit={name:'submit_preview',args:{summary:'主体预览',remainingIssues:[]}};
 const picture='data:image/jpeg;base64,YWJj';
 const fake=(steps)=>{let n=0;const contexts=[];const fn=async(model,context)=>{contexts.push(structuredClone(context));const step=steps[n++]??'done';const actions=typeof step==='function'?step(context):step;const content=Array.isArray(actions)?actions.map((a,i)=>({type:'toolCall',id:`call_${n}_${i}`,name:a.name,arguments:a.args})):[{type:'text',text:actions}];const message={role:'assistant',content,api:'openai-completions',provider:'mock',model:'mock',stopReason:Array.isArray(actions)?'toolUse':'stop',timestamp:Date.now(),usage:{input:20,output:10,cacheRead:0,cacheWrite:0,totalTokens:30,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}}};const stream=createAssistantMessageEventStream();queueMicrotask(()=>{stream.push({type:'start',partial:message});stream.push({type:'done',reason:message.stopReason,message})});return stream};return {fn,contexts,get calls(){return n}}};
 const opts=(transport,document=createInitialDoc())=>({text:'按参考图建模',config:cfg,document,selection:[],images:[picture],streamFn:transport.fn,capture:async()=>picture});
 await test('real Pi loop plans, edits, receives screenshot, reviews on later turn and submits only preview',async()=>{const f=fake([[plan,edit,capture],[review,submit]]);const o=opts(f);let previews=0;o.onPreview=()=>previews++;const before=JSON.stringify(o.document);const result=await runModelingAgent(o);assert.equal(f.calls,2);assert.equal(previews,1);assert.equal(result.result.doc.nodes.length,1);assert.equal(JSON.stringify(o.document),before);assert.equal(result.activity.timings.filter(t=>t.kind==='model').length,2);assert.ok(result.activity.timings.every(t=>t.endedAt>=t.startedAt));assert.equal(result.activity.inputTokens,40);assert.equal(result.activity.outputTokens,20);assert.ok(f.contexts[1].messages.some(m=>m.role==='toolResult'&&m.content.some(c=>c.type==='image')));assert.ok(result.activity.events.some(e=>e.includes('等待你确认')))});
 await test('steering skips stale tool calls and delivers text plus reference before next model turn',async()=>{
   let control,received=[];
   const f=fake([()=>{assert.ok(control.steer('guide-1','先不要创建，请回答高度问题',[picture]));return [edit];},context=>{assert.ok(context.messages.some(m=>m.role==='user'&&JSON.stringify(m.content).includes('高度问题')));assert.ok(context.messages.some(m=>m.role==='user'&&JSON.stringify(m.content).includes('YWJj')));return '建议高度八米';}]);
   const o=opts(f);o.onControl=c=>control=c;o.onSteeringApplied=id=>received.push(id);
   const r=await runModelingAgent(o);assert.equal(r.result.doc.nodes.length,0);assert.deepEqual(received,['guide-1']);assert.equal(control,null);assert.match(r.batch.summary,/八米/);
 });
 await test('steering after an applied edit preserves draft and bypasses stale submit',async()=>{
   let control,queued=false;
   const f=fake([[edit,capture],context=>{const id=JSON.parse(context.messages.find(m=>m.role==='toolResult'&&m.toolName==='edit_scene').content[0].text).scene.nodes[0].id;return [{name:'edit_scene',args:{summary:'按新要求改名',operations:[{op:'rename',targetId:id,name:'用户新名称'}]}},capture];},[review,submit]]);
   const o=opts(f);o.onControl=c=>control=c;o.onPreview=()=>{if(!queued){queued=true;assert.ok(control.steer('guide-2','改名为用户新名称'));}};
   const r=await runModelingAgent(o);assert.equal(r.result.doc.nodes.length,1);assert.equal(r.result.doc.nodes[0].name,'用户新名称');assert.equal(r.batch.incomplete,undefined);
 });
 await test('a question during modeling can get an answer without looping away or losing the draft',async()=>{
   let control;const f=fake([[edit,capture],'建议高度八米，分四层']);const o=opts(f);o.onControl=c=>control=c;o.onPreview=()=>control.steer('question','先回答货架多高合适，不要继续建模');const r=await runModelingAgent(o);assert.equal(f.calls,2);assert.equal(r.result.doc.nodes.length,1);assert.equal(r.batch.incomplete,true);assert.match(r.batch.summary,/建议高度八米/);
 });
 await test('multiple steering messages are delivered in order without dropping the newer request',async()=>{
   let control;const received=[];const f=fake([()=>{control.steer('one','高度八米');control.steer('two','纠正，高度九米');return '旧回答';},'收到八米',context=>{assert.match(JSON.stringify(context.messages),/高度九米/);return '按九米';}]);const o=opts(f);o.onControl=c=>control=c;o.onSteeringApplied=id=>received.push(id);const r=await runModelingAgent(o);assert.deepEqual(received,['one','two']);assert.match(r.batch.summary,/九米/);assert.equal(f.calls,3);
 });
 await test('explicit question mode blocks model edits and preserves the prior checkpoint',async()=>{
   let control,once=false;const f=fake([[edit,capture],[edit],'可以分四层']);const o=opts(f);o.onControl=c=>control=c;o.onPreview=()=>{if(!once){once=true;control.steer('q','应该分几层',[],'question');}};const r=await runModelingAgent(o);assert.equal(r.result.doc.nodes.length,1);assert.match(r.batch.summary,/分四层/);assert.ok(f.contexts[2].messages.some(m=>m.role==='toolResult'&&m.isError&&JSON.stringify(m.content).includes('只提问')));
 });
 await test('measurable unmet user requirements remain visible and make preview incomplete without blocking retention',async()=>{
   const req={name:'check_requirements',args:{items:[{quote:'六个货架',target:'货架',kind:'count',expected:'6'}]}};
   const f=fake([[req,{name:'edit_scene',args:{summary:'一组货架',operations:[{...create,name:'货架1'}]}},capture],[review,submit]]);const o=opts(f);o.text='六个货架';const r=await runModelingAgent(o);assert.equal(r.result.doc.nodes.length,1);assert.equal(r.activity.requirements.items[0].status,'mismatch');assert.equal(r.batch.incomplete,true);assert.match(r.batch.summary,/需求不符/);
 });
 await test('complex plans accept more than six steps and equipment features without losing detail',async()=>{const complex={...plan,args:{...plan.args,steps:Array.from({length:12},(_,i)=>'步骤'+i),design:{...design,equipment:[{name:'设备',count:20,features:Array.from({length:14},(_,i)=>'结构特征'+i)}]}}};const f=fake([[complex,edit,capture],[review,submit]]);const r=await runModelingAgent(opts(f));assert.equal(r.activity.plan.length,12);assert.equal(r.activity.design.equipment[0].features.length,14);assert.equal(r.result.doc.nodes.length,1);assert.equal(r.batch.incomplete,undefined)});
 await test('oversized plan gets concise corrective feedback then can recover with a valid plan',async()=>{const invalid={...plan,args:{...plan.args,steps:Array(25).fill('过多步骤')}};const f=fake([[invalid],context=>{const err=context.messages.find(m=>m.role==='toolResult'&&m.isError);assert.match(JSON.stringify(err.content),/最多24/);assert.ok(!JSON.stringify(err.content).includes('Received arguments'));return [plan,edit,capture];},[review,submit]]);const r=await runModelingAgent(opts(f));assert.equal(r.batch.incomplete,undefined);assert.equal(r.result.doc.nodes.length,1)});
 await test('failed planning reports actual validation cause rather than unsupported-model speculation',async()=>{const invalid={...plan,args:{...plan.args,steps:Array(25).fill('过多步骤')}};const f=fake(Array(8).fill([invalid]));await assert.rejects(()=>runModelingAgent(opts(f)),/plan_model.*Validation/);assert.ok(f.calls<=4)});
 await test('conversation animation config previews sampled motion then submits an undoable program',async()=>{const d=applyBatch(createInitialDoc(),{operations:[create]}).doc;const animation={version:1,name:'物料输送',duration:8,loop:true,tracks:[{id:'move',name:'移动',targetIds:[d.nodes[0].id],channel:'position',keyframes:[{time:0,value:[0,0,0]},{time:4,value:[2,0,0]},{time:8,value:[0,0,0]}]}]};const f=fake([[plan,{name:'edit_scene',args:{summary:'让物料移动',operations:[{op:'setAnimation',animation}]}},{name:'preview_animation',args:{}}],[review,submit]]);const o=opts(f,d);const times=[];o.capture=async(_d,_v,_ids,time)=>{times.push(time);return picture};const r=await runModelingAgent(o);assert.equal(r.batch.incomplete,undefined);assert.deepEqual(r.result.doc.nodes,d.nodes);assert.ok(r.result.doc.animation);assert.equal(times.length,3);assert.ok(times.some(t=>t>0));assert.equal(d.animation,undefined)});
 await test('animation submit requires motion samples and animated targets obey selected scope',async()=>{const d=applyBatch(createInitialDoc(),{operations:[create,{...create,name:'other'}]}).doc;const animation={version:1,name:'运动',duration:2,loop:true,tracks:[{id:'move',name:'移动',targetIds:[d.nodes[1].id],channel:'position',keyframes:[{time:0,value:[0,0,0]},{time:2,value:[1,0,0]}]}]};const f=fake([[plan,{name:'edit_scene',args:{summary:'move',operations:[{op:'setAnimation',animation}]}}],'范围不足']);const o=opts(f,d);o.editScope={nodeIds:[d.nodes[0].id]};const r=await runModelingAgent(o);assert.equal(r.result.doc.animation,undefined);assert.ok(JSON.stringify(f.contexts[1]).includes('选中范围'));const f2=fake([[plan,{name:'edit_scene',args:{summary:'move',operations:[{op:'setAnimation',animation}]}},capture],[review,submit],'结束']);const r2=await runModelingAgent(opts(f2,d));assert.equal(r2.batch.incomplete,true);assert.ok(f2.contexts.some(c=>JSON.stringify(c).includes('preview_animation检查')))});
 await test('native animation tool is discoverable and completes after explicit recovery guidance',async()=>{const d=applyBatch(createInitialDoc(),{operations:[create]}).doc;const animation={summary:'让物料移动',name:'输送',duration:4,loop:true,tracks:[{id:'move',name:'移动',channel:'position',targetIds:[d.nodes[0].id],keyframes:[{time:0,value:[0,0,0]},{time:4,value:[2,0,0]}]}]};const f=fake([[plan,{name:'read_scene',args:{}}],[{name:'read_scene',args:{}}],[{name:'read_scene',args:{}}],context=>{assert.ok(JSON.stringify(context).includes('下一步应configure_animation'));assert.ok(JSON.stringify(context).includes('历史助手关于不支持动画'));return [{name:'configure_animation',args:animation},{name:'preview_animation',args:{}}];},[review,submit]]);const o=opts(f,d);o.text='让这个沙盘动起来';o.history=[{role:'assistant',text:'以前这个版本不支持动画，只能静态'}];const r=await runModelingAgent(o);assert.equal(r.batch.incomplete,undefined);assert.ok(r.result.doc.animation);assert.deepEqual(r.result.doc.nodes,d.nodes);assert.ok(r.activity.events.some(e=>e.includes('configure_animation')))});
 await test('stalled animation request retains exact per-turn tool trace rather than opaque four-round error',async()=>{const f=fake(Array(10).fill([{name:'read_scene',args:{}}]));const o=opts(f);o.text='让场景动起来';await assert.rejects(()=>runModelingAgent(o),error=>error.message.includes('最近执行')&&error.message.includes('read_scene')&&error.message.includes('尚无动画配置'));assert.equal(f.calls,4)});
 await test('all-scene animation is permitted despite an unrelated highlighted object and stale scope history',async()=>{const d=applyBatch(createInitialDoc(),{operations:[{...create,name:'地面'}, {...create,name:'人物'}]}).doc;const animation={summary:'给人物增加动作',name:'人物动作',duration:4,loop:true,tracks:[{id:'person',name:'动作',channel:'rotation',targetIds:[d.nodes[1].id],axis:[0,0,1],pivot:[0,0,0],keyframes:[{time:0,value:0},{time:2,value:15},{time:4,value:0}]}]};const f=fake([[plan,{name:'read_scene',args:{}}],context=>{const scene=JSON.parse(context.messages.filter(m=>m.role==='toolResult'&&m.toolName==='read_scene').at(-1).content[0].text);assert.equal(scene.editingScope.mode,'all-scene');assert.ok(JSON.stringify(context).includes('高亮地面或其他对象不限制修改人物'));assert.ok(!JSON.stringify(context).includes('不能给未选中设备加动画'));assert.ok(!JSON.stringify(context).includes('禁止新建其他组件或修改未选中对象'));return [{name:'configure_animation',args:animation},{name:'preview_animation',args:{}}];},[review,submit]]);const o=opts(f,d);o.selection=[d.nodes[0].id];o.editScope={};o.text='开始给人物补动作';o.history=[{role:'assistant',text:'当前选中地面，必须切换范围才能改人物'}];const r=await runModelingAgent(o);assert.equal(r.batch.incomplete,undefined);assert.deepEqual(r.result.doc.animation.tracks[0].targetIds,[d.nodes[1].id]);assert.deepEqual(r.result.doc.nodes,d.nodes);});
 await test('component detail reads remain available together and count as bounded preparation progress',async()=>{const d=applyBatch(createInitialDoc(),{operations:Array.from({length:6},(_,i)=>({op:'createAssembly',name:'人物'+i,parts:[{name:'手臂'+i,geometry:create.geometry,transform:create.transform}]}))}).doc;const ids=d.nodes.map(n=>n.assemblyId);const f=fake([[plan],...ids.map(assemblyId=>[{name:'read_scene',args:{assemblyId}}]),context=>{const reads=context.messages.filter(m=>m.role==='toolResult'&&m.toolName==='read_scene'&&!m.isError);assert.equal(reads.length,6);for(const r of reads)assert.equal(JSON.parse(r.content[0].text).nodes.length,1);assert.ok(JSON.stringify(context).includes('本轮继续此前用户需求'));return [{name:'configure_animation',args:{summary:'补充全部人物动作',name:'人物动作',duration:4,loop:true,tracks:[{id:'move',name:'move',targetIds:d.nodes.map(n=>n.id),channel:'position',keyframes:[{time:0,value:[0,0,0]},{time:4,value:[0,.1,0]}]}]}},{name:'preview_animation',args:{}}];},[review,submit]]);const o=opts(f,d);o.text='开始吧';o.history=[{role:'user',text:'人物怎么没有动，给他们补上手臂动作'},{role:'assistant',text:'可以补充人物动作'}];const r=await runModelingAgent(o);assert.equal(r.batch.incomplete,undefined);assert.equal(f.calls,9);assert.ok(r.activity.events.some(e=>e.includes('read_scene(组件:')))});
 await test('context compaction keeps distinct current-revision scopes and expires them only after a real edit',()=>{const result=(id,scope,revision,snapshot=true)=>({role:'toolResult',toolName:'read_scene',toolCallId:id,isError:false,details:{scopeKey:scope,revision,snapshot},content:[{type:'text',text:JSON.stringify(snapshot?{nodes:[{id:scope+'-part'}]}:{repeated:true})}],timestamp:0});const messages=[result('a','person-A',3),result('b','person-B',3),result('a2','person-A',3,false)];let compact=compactAgentContext(messages);assert.ok(compact[0].content[0].text.includes('person-A-part'));assert.ok(compact[1].content[0].text.includes('person-B-part'));compact=compactAgentContext([...messages,{role:'toolResult',toolName:'configure_animation',toolCallId:'edit',isError:false,details:{revision:4},content:[{type:'text',text:'new scene'}],timestamp:0}]);assert.ok(!compact[0].content[0].text.includes('person-A-part'));assert.ok(!compact[1].content[0].text.includes('person-B-part'));});
 await test('read_scene unions assembly and explicit nodes instead of rejecting valid combined selectors',async()=>{const d=applyBatch(createInitialDoc(),{operations:['A','B'].map(name=>({op:'createAssembly',name,parts:[{name:'body',geometry:create.geometry,transform:create.transform},{name:'arm',geometry:create.geometry,transform:create.transform}]}))}).doc;const assemblyId=d.nodes[0].assemblyId;const f=fake([[plan,{name:'read_scene',args:{assemblyId,nodeIds:[d.nodes[0].id,d.nodes[2].id]}}],context=>{const result=context.messages.find(m=>m.role==='toolResult'&&m.toolName==='read_scene');assert.equal(result.isError,false);const data=JSON.parse(result.content[0].text);assert.equal(data.nodes.length,3);assert.equal(new Set(data.nodes.map(n=>n.id)).size,3);return '已读取组件及额外节点';}]);const r=await runModelingAgent(opts(f,d));assert.equal(r.batch.operations.length,0);assert.deepEqual(r.result.doc,d);});
 await test('several read errors in one turn allow a correction turn instead of immediate circuit break',async()=>{const d=applyBatch(createInitialDoc(),{operations:[create]}).doc;const invalid={name:'read_scene',args:{assemblyId:'missing'}};const f=fake([[plan],[invalid,invalid,invalid],context=>{assert.equal(context.messages.filter(m=>m.role==='toolResult'&&m.isError).length,3);return [{name:'read_scene',args:{nodeIds:[d.nodes[0].id]}},{name:'configure_animation',args:{summary:'移动',name:'move',duration:4,loop:true,tracks:[{id:'move',name:'move',targetIds:[d.nodes[0].id],channel:'position',keyframes:[{time:0,value:[0,0,0]},{time:4,value:[1,0,0]}]}]}},{name:'preview_animation',args:{}}];},[review,submit]]);const r=await runModelingAgent(opts(f,d));assert.equal(r.batch.incomplete,undefined);assert.equal(r.activity.timings.filter(t=>t.failed).length,3);assert.ok(r.result.doc.animation);});
 await test('multi-turn correction retains IDs and all steps undo as one transaction',async()=>{let current;const f=fake([[plan,edit,capture],()=>[{...review,args:{...review.args,issues:['主体偏高']}},{name:'edit_scene',args:{summary:'降低主体',operations:[{op:'setTransform',targetId:current.nodes[0].id,transform:{scale:[1,.8,1]}}]}},capture],[review,submit]]);const o=opts(f);o.onPreview=d=>current=d;const result=await runModelingAgent(o);assert.equal(result.result.doc.nodes[0].transform.scale[1],.8);store.setState({doc:o.document,past:[],future:[],aiStatus:'previewing',pendingBatch:result.batch,pendingResult:result.result,previewDoc:result.result.doc,messages:[]});store.getState().confirmPending();assert.equal(store.getState().past.length,1);const id=store.getState().doc.nodes[0].id;store.getState().undo();assert.equal(store.getState().doc.nodes.length,0);store.getState().redo();assert.equal(store.getState().doc.nodes[0].id,id);assert.equal(store.getState().doc.nodes[0].transform.scale[1],.8)});
 await test('same-turn invented visual review is rejected',async()=>{const f=fake([[plan,edit,capture,review,submit],'finished']);const r=await runModelingAgent(opts(f));assert.equal(r.batch.incomplete,true);assert.equal(r.result.doc.nodes.length,1);const failures=f.contexts[1].messages.filter(m=>m.role==='toolResult'&&m.isError);assert.ok(failures.some(m=>JSON.stringify(m.content).includes('下一轮')))});
 await test('editing after review requires fresh screenshot and review',async()=>{let current;const f=fake([[plan,edit,capture],()=>[review,{name:'edit_scene',args:{summary:'move',operations:[{op:'translate',targetId:current.nodes[0].id,space:'world',mode:'delta',value:[1,0,0]}]}},submit],'done']);const o=opts(f);o.onPreview=d=>current=d;const r=await runModelingAgent(o);assert.equal(r.batch.incomplete,true);assert.equal(r.result.doc.nodes.length,1)});
 await test('capture failure cannot claim a visually checked preview',async()=>{const f=fake([[plan,edit,capture],[review,submit],'done']);const o=opts(f);o.capture=async()=>{throw new Error('webgl unavailable')};const r=await runModelingAgent(o);assert.equal(r.batch.incomplete,true);assert.equal(r.result.doc.nodes.length,1)});
 await test('latest review problems cannot silently disappear from submitted summary',async()=>{const f=fake([[plan,edit,capture],[{...review,args:{...review.args,issues:['背面未还原']}},submit]]);const r=await runModelingAgent(opts(f));assert.match(r.batch.summary,/背面未还原/)});
 await test('clarification makes no scene changes',async()=>{const f=fake(['请提供实际宽度']);const r=await runModelingAgent(opts(f));assert.equal(r.batch.operations.length,0);assert.equal(r.batch.summary,'请提供实际宽度')});
 await test('repeated scene reads stop after four no-progress turns',async()=>{const f=fake(Array(20).fill([{name:'read_scene',args:{}}]));await assert.rejects(()=>runModelingAgent(opts(f)));assert.equal(f.calls,4)});
 await test('invalid command in group refuses entire group and leaves base untouched',async()=>{const f=fake([[plan,{name:'edit_scene',args:{summary:'invalid',operations:[create,{op:'execute_shell',command:'bad'}]}}],'不支持该命令']);const o=opts(f);const r=await runModelingAgent(o);assert.equal(r.result.doc.nodes.length,0);assert.ok(f.contexts[1].messages.some(m=>m.role==='toolResult'&&m.isError))});
 await test('cancellation during capture prevents completion and later draft callbacks',async()=>{const f=fake([[plan,edit,capture],[review,submit]]);const ctrl=new AbortController();let release;const o=opts(f);o.signal=ctrl.signal;o.capture=()=>new Promise(r=>release=r);const promise=runModelingAgent(o);while(!release)await new Promise(r=>setTimeout(r,1));ctrl.abort();release(picture);await assert.rejects(()=>promise,/停止/);assert.equal(o.document.nodes.length,0);assert.equal(f.calls,1)});
 await test('production Pi OpenAI adapter sends native tool schema and returns screenshot for the next request',async()=>{
   let wire=[];globalThis.fetch=async(url,init)=>{if(forceTransportError)throw new Error('本站模型代理响应异常（HTTP 403）。访问会话已失效');const body=JSON.parse(init.body);wire.push(body);const actions=wire.length===1?[plan,edit,capture]:[review,submit];const tc=actions.map((a,i)=>({index:i,id:`wire_${wire.length}_${i}`,type:'function',function:{name:a.name,arguments:JSON.stringify(a.args)}}));const raw='data: '+JSON.stringify({id:'test',object:'chat.completion.chunk',choices:[{index:0,delta:{role:'assistant',tool_calls:tc},finish_reason:null}]})+'\n\ndata: '+JSON.stringify({id:'test',object:'chat.completion.chunk',choices:[{index:0,delta:{},finish_reason:'tool_calls'}],usage:{prompt_tokens:30,completion_tokens:20,total_tokens:50}})+'\n\ndata: [DONE]\n\n';return new Response(raw,{headers:{'content-type':'text/event-stream'}})};
   const o=opts(fake([]));delete o.streamFn;const r=await runModelingAgent(o);assert.equal(wire.length,2);assert.ok(wire[0].tools.some(t=>t.function.name==='edit_scene'));assert.ok(wire.every(body=>body.tools.every(tool=>tool.type==='function')));assert.equal(wire[0].stream,true);assert.equal(wire[0].max_tokens,8192);assert.ok(JSON.stringify(wire[1].messages).includes('data:image/jpeg;base64,YWJj'));assert.equal(r.result.doc.nodes.length,1);assert.equal(r.activity.outputTokens,40);
 });
 await test('draw-workshop wording is normalized only for outbound modeling messages',async()=>{
   const f=fake(['请确认车间的实际宽度']);const fn=f.fn;let seen=0;
   f.fn=async(model,context,options)=>{const users=JSON.stringify(context.messages.filter(m=>m.role==='user'));assert.match(users,/帮我构建一个金刚石选型车间的沙盘/);assert.doesNotMatch(users,/画一/);seen++;return fn(model,context,options);};
   const o=opts(f);o.text='帮我画一个金刚石选型车间的沙盘，车间内有20台金刚石选型器';const original=o.text;
   const r=await runModelingAgent(o);assert.equal(seen,1);assert.equal(o.text,original);assert.equal(r.result.doc.nodes.length,0);assert.equal(r.batch.summary,'请确认车间的实际宽度');
 });
 await test('modeling wording normalization preserves requirements, explicit raster intent and non-user data',()=>{
   const original='帮我画一个三维车间沙盘，20台设备，红色机器人，高度8米';
   const expected='帮我构建一个三维车间沙盘，20台设备，红色机器人，高度8米';
   assert.equal(normalizeModelingRequestText(original),expected);assert.equal(normalizeModelingRequestText(expected),expected);
   assert.equal(normalizeModelingRequestText('Draw a 3D workshop scene with 20 machines'),'build a 3D workshop scene with 20 machines');
   for(const text of ['画一张车间图片','draw an image of a workshop','帮我画一个小猫','把20台设备改成蓝色'])assert.equal(normalizeModelingRequestText(text),text);
   const image={type:'image',data:'original-image-data',mimeType:'image/jpeg'};
   const messages=[{role:'user',content:[{type:'text',text:original},image],timestamp:1},{role:'user',content:original,timestamp:2},{role:'assistant',content:[{type:'text',text:original}],timestamp:3}];
   const before=JSON.stringify(messages);const normalized=normalizeModelingRequestMessages(messages);
   assert.equal(JSON.stringify(messages),before);assert.equal(normalized[0].content[0].text,expected);assert.equal(normalized[0].content[1],image);assert.equal(normalized[1].content,expected);assert.equal(normalized[2],messages[2]);
 });
 await test('real SDK serializes the normalized scene instruction, preserving reference images and original input',async()=>{
   const {stream}=await import('@earendil-works/pi-ai/api/openai-completions');const wire=[];
   const fetch=async(url,init)=>{wire.push(JSON.parse(init.body));const raw='data: '+JSON.stringify({id:'normalized',object:'chat.completion.chunk',choices:[{index:0,delta:{role:'assistant',content:'请确认车间实际宽度'},finish_reason:null}]})+'\n\ndata: '+JSON.stringify({id:'normalized',object:'chat.completion.chunk',choices:[{index:0,delta:{},finish_reason:'stop'}]})+'\n\ndata: [DONE]\n\n';return new Response(raw,{headers:{'content-type':'text/event-stream'}});};
   const o=opts(fake([]));o.streamFn=(model,context,options)=>stream(model,context,{...options,apiKey:cfg.apiKey,fetch,maxTokens:8192});o.text='帮我画一个金刚石选型车间的沙盘，车间内有20台金刚石选型器';const original=o.text;await runModelingAgent(o);
   assert.equal(wire.length,1);const users=wire[0].messages.filter(m=>m.role==='user');assert.match(JSON.stringify(users),/帮我构建一个金刚石选型车间的沙盘/);assert.doesNotMatch(JSON.stringify(users),/画一/);assert.match(JSON.stringify(users),/20台金刚石选型器/);assert.match(JSON.stringify(users),/data:image\/jpeg;base64,YWJj/);assert.ok(wire[0].tools.some(t=>t.function.name==='edit_scene'));assert.equal(o.text,original);
 });
 await test('Pi preserves actionable transport error instead of generic SDK connection error',async()=>{
   forceTransportError=true;
   const o=opts(fake([]));delete o.streamFn;await assert.rejects(()=>runModelingAgent(o),/HTTP 403.*访问会话已失效/);forceTransportError=false;
 });
 await test('context pruning removes obsolete snapshots and images but preserves current scene, reference and errors',()=>{
   const result=(toolName,content,isError=false)=>({role:'toolResult',toolName,toolCallId:Math.random().toString(),content,isError,timestamp:0});
   const ref={role:'user',content:[{type:'image',data:'original-reference',mimeType:'image/jpeg'}],timestamp:0};
   const oldScene=result('edit_scene',[{type:'text',text:'old'.repeat(10000)}]);const latest=result('read_scene',[{type:'text',text:'current-ids-and-geometry'}]);
   const oldImage=result('capture_view',[{type:'text',text:'revision=1'},{type:'image',data:'old-image'.repeat(10000),mimeType:'image/jpeg'}]);
   const newImage=result('capture_view',[{type:'text',text:'revision=2'},{type:'image',data:'new-image',mimeType:'image/jpeg'}]);const err=result('edit_scene',[{type:'text',text:'important-error'}],true);
   const messages=[ref,oldScene,oldImage,latest,newImage,err];const before=JSON.stringify(messages);const pruned=compactAgentContext(messages);assert.equal(JSON.stringify(messages),before);assert.equal(pruned[0],ref);assert.equal(pruned[3],latest);assert.equal(pruned[4],newImage);assert.equal(pruned[5],err);assert.equal(pruned[1],oldScene);assert.ok(JSON.stringify(pruned).length<before.length/2);
 });
 await test('no-progress pause retains valid work without changing official scene',async()=>{const f=fake([[plan,edit],...Array(5).fill([{name:'read_scene',args:{}}])]);const o=opts(f);let checkpoint;o.onCheckpoint=r=>checkpoint=r;const r=await runModelingAgent(o);assert.equal(f.calls,5);assert.equal(r.batch.incomplete,true);assert.equal(r.batch.operations.length,1);assert.equal(o.document.nodes.length,0);assert.equal(checkpoint.result.doc.nodes.length,1);assert.ok(r.batch.continuation.includes('继续完成原任务'));});
 await test('productive generation continues beyond six rounds and edits past round five',async()=>{
   const edits=Array.from({length:8},(_,i)=>[{name:'edit_scene',args:{summary:'结构细化'+i,operations:[{...create,name:'部件'+i}]}}]);
   const f=fake([[plan,...edits[0]],...edits.slice(1),[capture],[review,submit]]);const r=await runModelingAgent(opts(f));
   assert.equal(f.calls,10);assert.equal(r.result.doc.nodes.length,8);assert.equal(r.batch.incomplete,undefined);assert.ok(!JSON.stringify(f.contexts[5]).includes('禁止编辑'));assert.match(JSON.stringify(f.contexts[5].messages[0]),/当前第6轮/);
 });
 await test('three failed tool turns pause with exact errors and retain successful draft',async()=>{
   const bad={name:'edit_scene',args:{summary:'bad',operations:[{op:'unsupported'}]}};
   const f=fake([[plan,edit],[bad],[bad],[bad],[edit]]);const r=await runModelingAgent(opts(f));
   assert.equal(f.calls,4);assert.equal(r.batch.incomplete,true);assert.match(r.batch.summary,/连续3轮/);assert.ok(r.activity.events.some(e=>/工具失败：edit_scene：.+/.test(e)),JSON.stringify(r.activity.events));
 });
 await test('more than three captures and eighteen tools remain possible with real progress',async()=>{
   const steps=[[plan,edit,capture]];for(let i=0;i<6;i++)steps.push([review,edit,capture]);steps.push([review,submit]);
   const f=fake(steps);const r=await runModelingAgent(opts(f));assert.equal(f.calls,8);assert.ok(r.activity.toolCalls>18);assert.equal(r.result.doc.nodes.length,7);assert.equal(r.batch.incomplete,undefined);
 });
 await test('plain premature completion continues toward review without asking user to resend',async()=>{
   const f=fake([[plan,edit],'稍后继续',[capture],[review,submit]]);const r=await runModelingAgent(opts(f));assert.equal(f.calls,4);assert.equal(r.batch.incomplete,undefined);
 });
 await test('network error after successful edit returns explicitly unfinished checkpoint',async()=>{const f=fake([[plan,edit]]);const o=opts(f);let calls=0;o.streamFn=async(...args)=>{if(calls++)throw new Error('gateway disconnected');return f.fn(...args)};const r=await runModelingAgent(o);assert.equal(r.batch.incomplete,true);assert.match(r.batch.summary,/gateway disconnected/);assert.equal(o.document.nodes.length,0);});
 await test('existing legacy assembly context stays compact and detailed read remains editable',async()=>{const doc=applyBatch(createInitialDoc(),{operations:[{op:'createTemplate',templateId:'smt_mounter',parameters:{}}]}).doc;const f=fake([[{name:'read_scene',args:{}}],[{name:'read_scene',args:{assemblyId:doc.nodes[0].assemblyId}}],'现有组件可以继续编辑']);const r=await runModelingAgent(opts(f,doc));assert.equal(r.batch.operations.length,0);assert.equal(JSON.parse(f.contexts[1].messages.find(m=>m.role==='toolResult').content[0].text).nodes.length,1);assert.equal(JSON.parse(f.contexts[2].messages.filter(m=>m.role==='toolResult').at(-1).content[0].text).nodes.length,doc.nodes.length);});
 await test('AI template creation is refused without any scene side effects',async()=>{const f=fake([[plan,{name:'edit_scene',args:{summary:'preset',operations:[{op:'createTemplate',templateId:'smt_workshop',parameters:{}}]}}],'需要按描述规划工艺']);const r=await runModelingAgent(opts(f));assert.equal(r.result.doc.nodes.length,0);assert.equal(r.batch.operations.length,0);assert.ok(f.contexts[1].messages.some(m=>m.role==='toolResult'&&m.isError));});
 await test('generic and machining requests never create an automatic SMT baseline',async()=>{for(const text of ['做一个车间沙盘，有产线有设备操作人员','做一个机加工产线车间沙盘','生成一个 SMT 车间']){const f=fake(['需要按描述规划工艺']);const o=opts(f);o.text=text;o.images=[];let preview;o.onPreview=d=>preview=d;const r=await runModelingAgent(o);assert.equal(preview,undefined);assert.equal(r.result.doc.nodes.length,0);assert.equal(r.batch.operations.length,0);assert.ok(!JSON.stringify(f.contexts[0]).includes('A-04'));}});
 await test('free geometry path still works without injecting any preset',async()=>{const f=fake([[plan,edit,inspect,capture],[review,submit]]);const o=opts(f);o.text='做一个机加工产线车间沙盘';o.images=[];const r=await runModelingAgent(o);assert.equal(r.result.doc.nodes.length,1);assert.equal(r.batch.operations[0].op,'createPrimitive');assert.ok(!r.batch.summary.includes('以 SMT 示意车间为起点'));});
 await test('agent can generate a custom repeated assembly then review it without presets',async()=>{const f=fake([[plan,{name:'edit_scene',args:{summary:'自定义输送支架',operations:[{op:'createAssembly',name:'用户要求的支架',parts:[{name:'立柱',geometry:{type:'box',params:{width:.1,height:1,depth:.1}},transform:{position:[0,.5,0]},repeat:{count:8,step:[.5,0,0]}}]}]}},capture],[review,submit]]);const r=await runModelingAgent(opts(f));assert.equal(r.result.doc.nodes.length,8);assert.equal(r.batch.operations[0].op,'createAssembly');assert.equal(f.calls,2);assert.ok(JSON.stringify(f.contexts[0]).includes('自由组合与阵列建模'));assert.ok(JSON.stringify(f.contexts[0]).includes('duplicateAssembly'));});
 await test('older successful edit payloads are compacted with paired results, latest edits and failed calls preserved',()=>{
   const assistant=(id)=>({role:'assistant',content:[{type:'toolCall',id,name:'edit_scene',arguments:{summary:'主体细化',operations:Array(100).fill({op:'createPrimitive',name:'历史结构'.repeat(100)})}}],timestamp:0});
   const result=(id,isError=false)=>({role:'toolResult',toolName:'edit_scene',toolCallId:id,isError,content:[{type:'text',text:'真实ID与场景'}],timestamp:0});
   const messages=[assistant('old'),result('old'),assistant('failed'),result('failed',true),assistant('latest'),result('latest')];const before=JSON.stringify(messages),pruned=compactAgentContext(messages);
   assert.equal(JSON.stringify(messages),before);assert.ok(pruned[0].content[0].text.includes('已成功'));assert.ok(!pruned.some(m=>m.role==='toolResult'&&m.toolCallId==='old'));assert.ok(pruned.some(m=>m.role==='toolResult'&&m.toolCallId==='failed'));assert.ok(pruned.some(m=>m.role==='assistant'&&m.content.some(c=>c.type==='toolCall'&&c.id==='latest')));assert.ok(JSON.stringify(pruned).length<before.length*.75);
 });
 await test('focused capture uses real assembly IDs and cannot replace final whole-scene review',async()=>{
   const document=applyBatch(createInitialDoc(),{operations:[{op:'createAssembly',name:'自定义架体',parts:[{name:'框',geometry:{type:'frame',params:{width:1,height:1,depth:.1,thickness:.05}},transform:{position:[0,.5,0],scale:[1,1,1],rotationQuaternion:[0,0,0,1]}}]}]}).doc;
   const assemblyId=document.nodes[0].assemblyId;let focus;
   const f=fake([[plan,edit,{name:'capture_view',args:{view:'perspective',assemblyId}}],[review,submit,capture],[review,submit]]);const o=opts(f,document);o.capture=async(_d,_v,ids)=>{if(ids)focus=ids;return picture};const r=await runModelingAgent(o);
   assert.deepEqual(focus,[document.nodes[0].id]);assert.equal(r.batch.incomplete,undefined);assert.ok(f.contexts[2].messages.some(m=>m.role==='toolResult'&&m.isError&&JSON.stringify(m.content).includes('全场景')));
 });
 await test('fresh view reviews each count as progress, allowing near-to-whole final review and submission',async()=>{
 const d=applyBatch(createInitialDoc(),{operations:[{op:'createAssembly',name:'设备',parts:[{name:'body',geometry:{type:'box',params:{width:1,height:1,depth:1}},transform:{position:[0,.5,0],scale:[1,1,1],rotationQuaternion:[0,0,0,1]}}]}]}).doc;const assemblyId=d.nodes[0].assemblyId;
 const near={name:'capture_view',args:{view:'perspective',scope:'assembly',assemblyId}},whole={name:'capture_view',args:{view:'perspective',scope:'scene'}},top={name:'capture_view',args:{view:'top',scope:'scene'}};
 const f=fake([[plan,edit,near],[review],[whole],[{name:'read_scene',args:{}}],[{name:'read_scene',args:{assemblyId}}],[review],[{name:'read_scene',args:{}}],[top],[review],[submit]]);const r=await runModelingAgent(opts(f,d));assert.equal(f.calls,10);assert.equal(r.batch.incomplete,undefined);assert.ok(r.activity.events.some(e=>e.includes('全场景 / perspective')));
 });
 await test('focused-only submit failure gives explicit scene capture recovery and then succeeds',async()=>{
 const d=applyBatch(createInitialDoc(),{operations:[{op:'createAssembly',name:'设备',parts:[{name:'body',geometry:{type:'box',params:{width:1,height:1,depth:1}},transform:{position:[0,.5,0],scale:[1,1,1],rotationQuaternion:[0,0,0,1]}}]}]}).doc;const assemblyId=d.nodes[0].assemblyId;
 const f=fake([[plan,edit,{name:'capture_view',args:{view:'perspective',assemblyId}}],[review,submit],context=>{const error=context.messages.filter(m=>m.role==='toolResult'&&m.isError).at(-1);assert.match(JSON.stringify(error.content),/scope/);assert.match(JSON.stringify(error.content),/设备近景/);return [{name:'capture_view',args:{view:'top',scope:'scene'}}];},[review,submit]]);const r=await runModelingAgent(opts(f,d));assert.equal(r.batch.incomplete,undefined);
 });
 await test('repeated reviews of the same version scope and view still stop without progress',async()=>{
 const f=fake([[plan,edit,capture],...Array(10).fill([review])]);const r=await runModelingAgent(opts(f));assert.equal(r.batch.incomplete,true);assert.ok(f.calls<=7);assert.match(r.batch.summary,/连续4轮/);
 });
 await test('whole-scene creation requires a design brief before any edit',async()=>{
   const basic={name:'plan_model',args:{steps:['建立车间'],assumptions:'未规划'}};
   const f=fake([[basic,edit],'需要补全设计方案']);const o=opts(f);o.text='做一个机加工车间';const r=await runModelingAgent(o);assert.equal(r.result.doc.nodes.length,0);assert.ok(f.contexts[1].messages.some(m=>m.role==='toolResult'&&m.isError&&JSON.stringify(m.content).includes('design')));
 });
 await test('selection scope rejects an entire mixed-target edit batch without leaking partial changes',async()=>{
   const d=applyBatch(createInitialDoc(),{operations:[create,{...create,name:'other'}]}).doc;const wrong={name:'edit_scene',args:{summary:'改色',operations:[{op:'setAppearance',targetId:d.nodes[0].id,baseColor:'#123456'},{op:'setAppearance',targetId:d.nodes[1].id,baseColor:'#123456'}]}};
   const f=fake([[plan,wrong],'请扩大范围']);const o=opts(f,d);o.editScope={nodeIds:[d.nodes[0].id]};const r=await runModelingAgent(o);assert.deepEqual(r.result.doc,d);assert.ok(f.contexts[1].messages.some(m=>m.role==='toolResult'&&m.isError&&JSON.stringify(m.content).includes('超出修改范围')));
 });
 await test('local color change respects frozen placement and preserves other objects',async()=>{
   const d=applyBatch(createInitialDoc(),{operations:[create,{...create,name:'other'}]}).doc;const f=fake([[plan,{name:'edit_scene',args:{summary:'改选中外壳颜色',operations:[{op:'setAppearance',targetId:d.nodes[0].id,baseColor:'#123456'}]}},capture],[review,submit]]);const o=opts(f,d);o.editScope={nodeIds:[d.nodes[0].id],lockPlacement:true};const r=await runModelingAgent(o);assert.equal(r.batch.incomplete,undefined);assert.deepEqual(r.result.doc.nodes[1],d.nodes[1]);assert.deepEqual(r.result.doc.nodes[0].transform,d.nodes[0].transform);assert.deepEqual(r.batch.editScope,o.editScope);
 });
 await test('representative equipment can be duplicated before consolidated final review',async()=>{
   let preview;const assembly={name:'edit_scene',args:{summary:'代表设备',operations:[{op:'createAssembly',name:'自设计设备',parts:[{name:'结构',geometry:{type:'frame',params:{width:1,height:1,depth:.1,thickness:.05}}}]}]}};
   const f=fake([[plan,assembly],()=>[{name:'edit_scene',args:{summary:'布置同类',operations:[{op:'duplicateAssembly',targetId:preview.nodes[0].id,offset:[2,0,0]}]}},inspect,capture],[review,submit]]);const o=opts(f);o.text='做一个机加工车间';o.onPreview=d=>preview=d;const r=await runModelingAgent(o);assert.equal(r.result.doc.nodes.length,2);assert.equal(r.batch.incomplete,undefined);assert.equal(f.calls,3);assert.deepEqual(r.activity.design,design);
 });
 await test('whole scene cannot submit without checking the latest composition and shows inspection findings',async()=>{
   const f=fake([[plan,edit,capture],[review,submit,inspect],[submit]]);const o=opts(f);o.text='做一个机加工车间';const r=await runModelingAgent(o);assert.equal(r.batch.incomplete,undefined);assert.ok(f.contexts[2].messages.some(m=>m.role==='toolResult'&&m.isError&&JSON.stringify(m.content).includes('inspect_scene')));assert.equal(r.activity.quality.revision,r.result.doc.revision);assert.ok(r.batch.summary.includes('设计清单未满足'));
 });
 await test('selected assembly accepts append then modification of the new part across model turns',async()=>{
  const d=applyBatch(createInitialDoc(),{operations:[{op:'createAssembly',name:'基准组件',parts:[{name:'主体',geometry:{type:'box',params:{width:1,height:1,depth:1}},transform:{position:[0,.5,0],scale:[1,1,1],rotationQuaternion:[0,0,0,1]}}]}]}).doc;let current;
  const append={name:'edit_scene',args:{summary:'追加部件',operations:[{op:'appendAssemblyParts',targetId:d.nodes[0].id,parts:[{name:'把手',geometry:{type:'capsule',params:{radius:.02,length:.3}},transform:{position:[.4,.7,.6]}}]}]}};
  const f=fake([[plan,append],()=>[{name:'edit_scene',args:{summary:'新部件改色',operations:[{op:'setAppearance',targetId:current.nodes.at(-1).id,baseColor:'#123456'}]}},capture],[review,submit]]);const o=opts(f,d);o.selection=[d.nodes[0].id];o.editScope={nodeIds:o.selection,allowAssemblyAdditions:true,lockPlacement:true};o.onPreview=v=>current=v;const r=await runModelingAgent(o);assert.equal(r.batch.incomplete,undefined);assert.equal(r.result.doc.nodes.length,2);assert.equal(r.result.doc.nodes[1].assemblyId,d.nodes[0].assemblyId);assert.deepEqual(r.result.doc.nodes[0].transform,d.nodes[0].transform);
 });
 await test('whole-equipment selections stay compact while detailed part reads remain available',async()=>{
  const doc=applyBatch(createInitialDoc(),{operations:[{op:'createTemplate',templateId:'smt_mounter',parameters:{}}]}).doc;
  const f=fake([[{name:'read_scene',args:{}}],[{name:'read_scene',args:{assemblyId:doc.nodes[0].assemblyId}}],'已读取组件']);const o=opts(f,doc);o.selection=doc.nodes.map(n=>n.id);o.editScope={nodeIds:o.selection,allowAssemblyAdditions:true};await runModelingAgent(o);
  const overview=JSON.parse(f.contexts[1].messages.find(m=>m.role==='toolResult').content[0].text);assert.equal(overview.nodes.length,1);assert.equal(overview.selection.length,0);assert.equal(overview.selectedAssemblies.length,1);const detail=JSON.parse(f.contexts[2].messages.filter(m=>m.role==='toolResult').at(-1).content[0].text);assert.equal(detail.nodes.length,doc.nodes.length);
 });
 await test('metadata-only rename submits without mandatory plan or screenshots',async()=>{
  const d=applyBatch(createInitialDoc(),{operations:[create]}).doc;const f=fake([[{name:'edit_scene',args:{summary:'重命名',operations:[{op:'rename',targetId:d.nodes[0].id,name:'新名称'}]}},submit]]);const o=opts(f,d);o.capture=async()=>{throw new Error('unnecessary capture')};const r=await runModelingAgent(o);assert.equal(r.batch.incomplete,undefined);assert.equal(f.calls,1);assert.equal(r.result.doc.nodes[0].name,'新名称');assert.match(r.batch.summary,/非视觉修改/);
 });
 await test('single assembly appearance can submit after a focused review',async()=>{
  const d=applyBatch(createInitialDoc(),{operations:[{op:'createAssembly',name:'设备',parts:[{name:'body',geometry:create.geometry,transform:create.transform}]}]}).doc;const f=fake([[{name:'edit_scene',args:{summary:'改色',operations:[{op:'setAppearance',targetId:d.nodes[0].id,baseColor:'#123456'}]}},{name:'capture_view',args:{view:'perspective',assemblyId:d.nodes[0].assemblyId}}],[review,submit]]);const r=await runModelingAgent(opts(f,d));assert.equal(r.batch.incomplete,undefined);assert.equal(f.calls,2);
 });
 await test('metadata after visual review does not invalidate already reviewed pixels',async()=>{
  let current;const f=fake([[plan,edit,capture],()=>[review,{name:'edit_scene',args:{summary:'改名',operations:[{op:'rename',targetId:current.nodes[0].id,name:'最终名称'}]}},submit]]);const o=opts(f);o.onPreview=d=>current=d;const r=await runModelingAgent(o);assert.equal(r.batch.incomplete,undefined);assert.equal(f.calls,2);assert.equal(r.result.doc.nodes[0].name,'最终名称');
 });
 await test('review policy distinguishes labels, shared materials, metadata and structural changes',async()=>{
  const {reviewRequirement}=await server.ssrLoadModule('/src/domain/reviewPolicy.ts');const d=applyBatch(createInitialDoc(),{operations:['A','B'].map(name=>({op:'createAssembly',name,parts:[{name:'body',geometry:create.geometry,materialId:'mat_white',transform:create.transform}]}))}).doc;
  const metadata=structuredClone(d);metadata.nodes[0].name='new';metadata.nodes[0].zone='zone';assert.equal(reviewRequirement(d,metadata).kind,'none');
  const label=structuredClone(d);label.nodes[0].label='display';assert.equal(reviewRequirement(d,label).kind,'local');
  const shared=structuredClone(d);shared.materials.find(m=>m.id==='mat_white').baseColor='#111111';assert.equal(reviewRequirement(d,shared).kind,'whole');
  const moved=structuredClone(d);moved.nodes[0].transform.position[0]+=1;assert.equal(reviewRequirement(d,moved).kind,'whole');
 });
 console.log(`${passed} Pi agent loop checks passed; model and rendering mocked`);
}finally{await server.close()}
