import {createAssistantMessageEventStream} from '@earendil-works/pi-ai';
import assert from 'node:assert/strict';import {createServer} from 'vite';import 'fake-indexeddb/auto';
const server=await createServer({server:{middlewareMode:true},appType:'custom'});let count=0;const test=async(name,fn)=>{await fn();console.log('PASS',name);count++;};
try{
 const {createInitialDoc}=await server.ssrLoadModule('/src/store.ts'),{applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts');
 const {createModelAsset,instantiateAsset,parseModelAsset,validateModelAsset,assetDocument,assetVersionSourceIssue}=await server.ssrLoadModule('/src/domain/modelAssets.ts');const {saveModelAsset,readModelAsset,listModelAssets}=await server.ssrLoadModule('/src/domain/modelAssetStorage.ts');
 const part=(name,x,y)=>({name,geometry:{type:'box',params:{width:1,height:1,depth:1}},materialId:'mat_gray',transform:{position:[x,y,3],rotationQuaternion:[0,0,0,1],scale:[1,1,1]}});
 const original=applyBatch(createInitialDoc(),{operations:[{op:'createAssembly',name:'source',parts:[part('a',4,.5),part('b',5,.5)]},{op:'createAssembly',name:'other',parts:[part('external',6,.5)]}]}).doc;
 const a=original.nodes[0],b=original.nodes[1],external=original.nodes[2];a.connection={targetId:b.id,sourcePoint:[.5,0,0],targetPoint:[-.5,0,0],maxDistance:.01,purpose:'internal'};b.connection={targetId:external.id,sourcePoint:[.5,0,0],targetPoint:[-.5,0,0],maxDistance:.01,purpose:'external'};
 const before=JSON.stringify(original);let asset;
 await test('selection expands a component, grounds origin and preserves only internal contacts',()=>{asset=createModelAsset(original,[a.id],{name:'通用设备',category:'设备'});assert.equal(asset.nodes.length,2);assert.equal(asset.externalConnectionsRemoved,1);assert.equal(asset.nodes[0].connection.targetId,b.id);assert.equal(asset.nodes[1].connection,undefined);assert.deepEqual(asset.size,[2,1,1]);assert.deepEqual(asset.nodes[0].transform.position,[-.5,.5,0]);assert.equal(JSON.stringify(original),before);assert.equal(asset.quality,'unreviewed');assert.equal(asset.nodes[0].planKey,undefined);});
 await test('an independent saved copy accepts its actual source nodes but not unrelated foreign instances',()=>{const instance=applyBatch(createInitialDoc(),{operations:[instantiateAsset(asset,[0,0,0])]}).doc;const copy=createModelAsset(instance,instance.nodes.map(n=>n.id),{name:'copy',category:'设备'});assert.equal(assetVersionSourceIssue(instance.nodes,copy),undefined);assert.equal(assetVersionSourceIssue(instance.nodes,asset),undefined);const another=applyBatch(createInitialDoc(),{operations:[instantiateAsset(asset,[3,0,0])]}).doc;assert.match(assetVersionSourceIssue(another.nodes,copy),/另一资产/);});
 await test('versioned instancing has isolated geometry, materials and remapped contact IDs',()=>{const one=applyBatch(createInitialDoc(),{operations:[instantiateAsset(asset,[10,0,0],90)]});assert.deepEqual(one.errors,[]);const n=one.doc.nodes[0],other=one.doc.nodes[1];assert.equal(n.connection.targetId,other.id);assert.notEqual(n.id,asset.nodes[0].id);assert.notEqual(n.materialId,asset.nodes[0].materialId);assert.equal(n.modelAsset.version,1);assert.equal(n.modelAsset.id,asset.id);const two=applyBatch(one.doc,{operations:[instantiateAsset(asset,[20,0,0])]});assert.equal(two.doc.nodes.length,4);assert.notEqual(two.doc.nodes[0].modelAsset.instanceId,two.doc.nodes[2].modelAsset.instanceId);one.doc.nodes[0].geometry.params.width=9;assert.equal(asset.nodes[0].geometry.params.width,1);assert.equal(assetDocument(asset).nodes[0].geometry.params.width,1);});
 await test('library persists immutable revisions and rejects stale concurrent replacement',async()=>{await saveModelAsset(asset);const v2={...structuredClone(asset),version:2,name:'新版本'};const outcomes=await Promise.allSettled([saveModelAsset(v2,1),saveModelAsset({...v2,name:'竞争版本'},1)]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);assert.equal((await readModelAsset(asset.id,1)).name,'通用设备');assert.equal((await readModelAsset(asset.id,2)).version,2);assert.equal((await listModelAssets())[0].version,2);await assert.rejects(()=>saveModelAsset(asset),/更新/);assert.equal((await readModelAsset(asset.id,1)).name,'通用设备');});
 await test('asset file roundtrip rejects false quality stamps, dangling references and bad metadata',()=>{const parsed=parseModelAsset(JSON.stringify(asset));assert.deepEqual(parsed,asset);assert.throws(()=>parseModelAsset(JSON.stringify({...asset,quality:'approved'})),/元数据/);assert.throws(()=>validateModelAsset({...asset,size:[999,1,1]}),/尺寸/);assert.throws(()=>validateModelAsset({...asset,nodes:[asset.nodes[0]]}),/连接|悬空/);assert.throws(()=>instantiateAsset(asset,[NaN,0,0]),/位置/);assert.throws(()=>createModelAsset(original,[],{name:'none',category:'其他'}),/请选择/);});
 await test('latest asset changes never alter a scene instance pinned to an older version',async()=>{const old=await readModelAsset(asset.id,1),current=await readModelAsset(asset.id,2);const scene=applyBatch(createInitialDoc(),{operations:[instantiateAsset(old,[0,0,0])]});assert.equal(scene.doc.nodes[0].modelAsset.version,1);assert.equal(current.version,2);assert.equal(scene.doc.nodes[0].modelAsset.version,1);});
 await test('duplicating an asset instance remaps internal contacts and creates a distinct instance identity',()=>{const first=applyBatch(createInitialDoc(),{operations:[instantiateAsset(asset,[0,0,0])]});const copy=applyBatch(first.doc,{operations:[{op:'duplicateAssembly',targetId:first.doc.nodes[0].id,offset:[3,0,0]}]});assert.deepEqual(copy.errors,[]);assert.equal(copy.doc.nodes[2].connection.targetId,copy.doc.nodes[3].id);assert.notEqual(copy.doc.nodes[2].modelAsset.instanceId,copy.doc.nodes[0].modelAsset.instanceId);assert.equal(copy.doc.nodes[2].modelAsset.version,1);});
 const fake=(steps)=>{let n=0;const contexts=[];const fn=async(model,context)=>{contexts.push(structuredClone(context));const step=steps[n++]??'done';const actions=typeof step==='function'?step(context):step;const content=Array.isArray(actions)?actions.map((a,i)=>({type:'toolCall',id:`call_${n}_${i}`,name:a.name,arguments:a.args})):[{type:'text',text:actions}];const message={role:'assistant',content,api:'openai-completions',provider:'mock',model:'mock',stopReason:Array.isArray(actions)?'toolUse':'stop',timestamp:Date.now(),usage:{input:20,output:10,cacheRead:0,cacheWrite:0,totalTokens:30,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}}};const stream=createAssistantMessageEventStream();queueMicrotask(()=>{stream.push({type:'start',partial:message});stream.push({type:'done',reason:message.stopReason,message})});return stream};return {fn,contexts,get calls(){return n}}};
 await test('agent retrieves compact asset metadata and inserts a fixed version without claiming quality',async()=>{
  const {runModelingAgent}=await server.ssrLoadModule('/src/ai/modelingAgent.ts');const f=fake([[{name:'list_saved_assets',args:{query:'通用'}}],ctx=>{const result=ctx.messages.find(m=>m.role==='toolResult'&&m.toolName==='list_saved_assets');assert.ok(result);assert.ok(!JSON.stringify(result).includes('positions'));assert.ok(!JSON.stringify(result).includes('thumbnail'));return [{name:'add_saved_assets',args:{items:[{id:asset.id,version:1,name:'复用设备',position:[4,0,0]}]}}];},[{name:'submit_data_preview',args:{summary:'已插入固定版本实例，质量待验收'}}]]);const r=await runModelingAgent({text:'复用保存的单体设备',config:{baseURL:'https://mock.invalid/v1',apiKey:'mock',model:'mock'},document:createInitialDoc(),selection:[],streamFn:f.fn,captureAvailable:()=>false});assert.equal(r.result.doc.nodes.length,2);assert.equal(r.result.doc.nodes[0].modelAsset.version,1);assert.equal(r.result.doc.nodes[0].assemblyName,'复用设备');assert.equal(r.batch.incomplete,true);
 });
 await test('one missing library version prevents an entire multi-asset insertion batch',async()=>{
  const {runModelingAgent}=await server.ssrLoadModule('/src/ai/modelingAgent.ts');const f=fake([[{name:'add_saved_assets',args:{items:[{id:asset.id,version:1,position:[0,0,0]},{id:asset.id,version:99,position:[3,0,0]}]}}],'未能找到版本，未插入任何对象']);const r=await runModelingAgent({text:'插入两个保存模型',config:{baseURL:'https://mock.invalid/v1',apiKey:'mock',model:'mock'},document:createInitialDoc(),selection:[],streamFn:f.fn,captureAvailable:()=>false});assert.equal(r.result.doc.nodes.length,0);assert.ok(r.activity.events.some(x=>x.includes('未找到该资产版本')));
 });
 await test('agent reads compact contract and reports unchanged instance geometry',async()=>{
 const {runModelingAgent}=await server.ssrLoadModule('/src/ai/modelingAgent.ts');const scene=applyBatch(createInitialDoc(),{operations:[instantiateAsset(asset,[0,0,0])]}).doc;const instance=scene.nodes[0].modelAsset.instanceId;
 const f=fake([[{name:'read_saved_asset',args:{id:asset.id,version:1}},{name:'inspect_asset_instances',args:{instanceIds:[instance]}}],ctx=>{const results=ctx.messages.filter(m=>m.role==='toolResult');assert.ok(results.some(m=>JSON.stringify(m).includes('intrinsicUnchanged')));assert.ok(!JSON.stringify(results).includes('positions'));return '实例几何未改动，场景关系待验收';}]);const result=await runModelingAgent({text:'检查已保存资产的连接点和实例，不修改',config:{baseURL:'https://mock.invalid/v1',apiKey:'mock',model:'mock'},document:scene,selection:[],streamFn:f.fn,captureAvailable:()=>false});assert.equal(result.result.doc.nodes.length,scene.nodes.length);assert.ok(f.calls>=2);
 });
 console.log(count+' model asset checks passed');
}finally{await server.close();}
