import assert from 'node:assert/strict';import {createServer} from 'vite';
const server=await createServer({server:{middlewareMode:true},appType:'custom'});let passed=0;const test=async(n,f)=>{await f();passed++;console.log('PASS',n)};
try{
const {isolatedDocument,componentDraftCommand,runBoundedJobs}=await server.ssrLoadModule('/src/ai/parallelDrafts.ts');const {createInitialDoc}=await server.ssrLoadModule('/src/store.ts');const {applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts');const {validateDocument}=await server.ssrLoadModule('/src/domain/types.ts');const {detailTargets}=await server.ssrLoadModule('/src/domain/detailAcceptance.ts');
const base=createInitialDoc(),shape={op:'createPrimitive',name:'独立主体',parentId:null,geometry:{type:'box',params:{width:1,height:1,depth:1}},transform:{position:[0,.5,0],rotationQuaternion:[0,0,0,1],scale:[1,1,1]}};const jobs=['A','B','C','D'].map((name,i)=>({name,brief:'只生成这个组件',position:[i*2,0,0]}));
await test('isolated child receives no parent geometry, assets, animation or embedded maps',()=>{const d=structuredClone(applyBatch(base,{operations:[shape]}).doc);d.assets=[{id:'secret-shape'}];d.materials[0].maps={normal:{dataUrl:'private-map'}};const child=isolatedDocument(d);assert.equal(child.nodes.length,0);assert.equal(child.assets.length,0);assert.equal(child.animation,undefined);assert.ok(child.materials.every(m=>!m.maps));assert.notEqual(child.projectId,d.projectId);child.materials[0].baseColor='#000000';assert.notEqual(d.materials[0].baseColor,'#000000')});
await test('scheduler limits concurrency to two and preserves job order despite completion order',async()=>{let active=0,peak=0;const results=await runBoundedJobs(jobs,async(job,i)=>{active++;peak=Math.max(peak,active);await new Promise(r=>setTimeout(r,(4-i)*5));active--;return job.name});assert.equal(peak,2);assert.deepEqual(results.map(x=>x.value),['A','B','C','D'])});
await test('one failed child retains successful sibling data without silent success',async()=>{const r=await runBoundedJobs(jobs.slice(0,2),async(_,i)=>{if(i)throw Error('failed');return 'draft'});assert.equal(r[0].status,'fulfilled');assert.equal(r[1].status,'rejected')});
await test('abort prevents queued work and rejects late child results',async()=>{const c=new AbortController();let started=0;await assert.rejects(()=>runBoundedJobs(jobs,async()=>{started++;await new Promise(r=>setTimeout(r,5));c.abort();return 'late'},c.signal),/停止/);assert.equal(started,2)});
await test('component merge remaps IDs, materials and internal connections atomically and preserves parent',()=>{let child=applyBatch(base,{operations:[shape,{...shape,name:'接口'}]}).doc;const [a,b]=child.nodes.map(n=>n.id);child=applyBatch(child,{operations:[{op:'setConnection',targetId:a,connection:{targetId:b,sourcePoint:[0,0,0],targetPoint:[0,0,0],maxDistance:.01,purpose:'内部连接'}}]}).doc;const ops=jobs.slice(0,2).map(job=>componentDraftCommand(child,job)),r=applyBatch(base,{operations:ops});assert.deepEqual(r.errors,[]);assert.equal(r.doc.nodes.length,4);assert.equal(new Set(r.doc.nodes.map(n=>n.id)).size,4);assert.equal(new Set(r.doc.nodes.map(n=>n.assemblyId)).size,2);assert.equal(r.doc.nodes[0].connection.targetId,r.doc.nodes[1].id);assert.equal(r.doc.nodes[2].connection.targetId,r.doc.nodes[3].id);assert.equal(r.doc.nodes[2].transform.position[0],2);assert.equal(base.nodes.length,0);assert.deepEqual(validateDocument(r.doc),[]);assert.equal(detailTargets(base,r.doc).length,2)});
await test('empty or animated child cannot be merged and duplicate job names rejected',async()=>{assert.throws(()=>componentDraftCommand(base,jobs[0]));await assert.rejects(()=>runBoundedJobs([jobs[0],jobs[0]],async()=>null));});
await test('model review clipboard payload roundtrips and excludes configuration/history',async()=>{const {encodeReviewProject}=await server.ssrLoadModule('/src/domain/reviewExport.ts');const {gunzipSync}=await import('node:zlib');const doc=applyBatch(base,{operations:[shape]}).doc;const text=await encodeReviewProject(doc);assert.ok(text.startsWith('CHAT3D-REVIEW-1:'));const {parseProject}=await server.ssrLoadModule('/src/domain/project.ts');const restored=parseProject(gunzipSync(Buffer.from(text.slice('CHAT3D-REVIEW-1:'.length),'base64')).toString());assert.equal(restored.nodes.length,1);assert.equal(restored.nodes[0].id,doc.nodes[0].id);assert.equal(restored.apiKey,undefined);assert.equal(restored.messages,undefined)});
console.log(passed+' parallel draft checks passed');
}finally{await server.close()}
