import assert from 'node:assert/strict';
import {createServer} from 'vite';
import {createAssistantMessageEventStream} from '@earendil-works/pi-ai';
const server=await createServer({server:{middlewareMode:true},appType:'custom'});let count=0;
const test=async(n,f)=>{await f();console.log('PASS',n);count++};
try{
 const p=await server.ssrLoadModule('/src/domain/preservedPose.ts'),{applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts'),{createInitialDoc}=await server.ssrLoadModule('/src/store.ts'),{runModelingAgent,compactAgentContext}=await server.ssrLoadModule('/src/ai/modelingAgent.ts');
 const transform={position:[1,0,0],scale:[1,1,1],rotationQuaternion:[0,0,0,1]};const base=applyBatch(createInitialDoc(),{operations:[{op:'createAssembly',name:'原资产人员',sceneRole:'person',parts:['衣袖','手掌'].map(name=>({name,geometry:{type:'box',params:{width:.1,height:.3,depth:.1}},transform,materialId:'mat_gray'}))}]}).doc;
 const assetId=crypto.randomUUID(),instanceId=crypto.randomUUID();for(const n of base.nodes)n.modelAsset={id:assetId,version:1,instanceId,sourceNodeId:n.id};const id=base.nodes[0].assemblyId,ids=base.nodes.map(n=>n.id);
 await test('mixed legacy asset assemblies retain existing generated parts and detect their articulation',()=>{const mixed=structuredClone(base);const extra={...structuredClone(mixed.nodes[1]),id:crypto.randomUUID(),name:'旧流程生成的手'};delete extra.modelAsset;mixed.nodes.push(extra);assert.equal(p.assertPreservedAssetShape(mixed,mixed),3);const commands=p.existingPoseCommands(mixed,id,[{nodeIds:[extra.id],pivot:[0,0,0],axis:[0,0,1],angle:15}]);const changed=applyBatch(mixed,{operations:commands}).doc;assert.equal(p.hasAssetPoseChange(mixed,changed,true),true);assert.equal(p.assertPreservedAssetShape(mixed,changed),3);});
 await test('legacy generated geometry remains protected against deletion replacement and new overlays',()=>{const mixed=structuredClone(base);const extra={...structuredClone(mixed.nodes[1]),id:crypto.randomUUID()};delete extra.modelAsset;mixed.nodes.push(extra);for(const change of [d=>d.nodes.pop(),d=>d.nodes[2].geometry.params.width=2,d=>d.nodes.push({...structuredClone(extra),id:crypto.randomUUID()})]){const d=structuredClone(mixed);change(d);assert.throws(()=>p.assertPreservedAssetShape(mixed,d));}});
 await test('existing joints rotate original geometry with stable IDs materials and scale',()=>{const commands=p.existingPoseCommands(base,id,[{nodeIds:ids,pivot:[0,0,0],axis:[0,0,1],angle:90}]);const r=applyBatch(base,{operations:commands});assert.deepEqual(r.errors,[]);assert.equal(p.assertPreservedAssetShape(base,r.doc),2);for(const n of r.doc.nodes){assert.ok(Math.abs(n.transform.position[0])<1e-8);assert.ok(Math.abs(n.transform.position[1]-1)<1e-8);assert.deepEqual(n.geometry,base.nodes.find(x=>x.id===n.id).geometry);}assert.equal(base.nodes[0].transform.position[0],1);});
 await test('deletion replacement rescale hiding material changes and overlay parts cannot bypass asset protection',()=>{for(const change of [d=>d.nodes.pop(),d=>d.nodes[0].geometry.params.width=2,d=>d.nodes[0].transform.scale[0]=2,d=>d.nodes[0].visible=false,d=>d.materials.find(m=>m.id==='mat_gray').baseColor='#ff0000',d=>d.nodes.push({...structuredClone(d.nodes[0]),id:crypto.randomUUID()})]){const d=structuredClone(base);change(d);assert.throws(()=>p.assertPreservedAssetShape(base,d),/保形|原外形/);}});
 await test('renames and whole-asset motion cannot satisfy a hand articulation goal',()=>{const renamed=structuredClone(base);renamed.nodes[0].name='已握住';assert.equal(p.hasAssetPoseChange(base,renamed,true),false);const whole=applyBatch(base,{operations:p.existingPoseCommands(base,id,[{nodeIds:ids,pivot:[0,0,0],axis:[0,0,1],angle:90}])}).doc;assert.equal(p.hasAssetPoseChange(base,whole,true),false);assert.equal(p.hasAssetPoseChange(base,whole,false),true);const local=applyBatch(base,{operations:p.existingPoseCommands(base,id,[{nodeIds:[ids[1]],pivot:[0,0,0],axis:[0,0,1],angle:90}])}).doc;assert.equal(p.hasAssetPoseChange(base,local,true),true);});
 await test('invalid foreign and hierarchical joint targets fail before changes',()=>{for(const j of [{nodeIds:['foreign'],pivot:[0,0,0],axis:[0,1,0],angle:20},{nodeIds:ids,pivot:[0,0,0],axis:[0,0,0],angle:20}])assert.throws(()=>p.existingPoseCommands(base,id,[j]));const d=structuredClone(base);d.nodes[1].parentId=d.nodes[0].id;assert.throws(()=>p.existingPoseCommands(d,id,[{nodeIds:ids,pivot:[0,0,0],axis:[0,1,0],angle:20}]),/坐标/);});
 await test('brief approval retains pose preservation intent without making unrelated color edits pose tasks',()=>{assert.equal(p.preserveAssetShapeIntent('开始调整吧',[{role:'assistant',text:'调整手臂姿态，保持模型外观'}]),true);assert.equal(p.preserveAssetShapeIntent('把设备颜色改红',[{role:'user',text:'调整人物姿态'}]),false);assert.equal(p.preserveAssetShapeIntent('重新建模这个人物，然后调整姿态'),false);assert.equal(p.preserveAssetShapeIntent('不要重建人物，只调整姿态'),true);});
 function stream(script,inspect=()=>{}){let n=0;return async(_m,ctx)=>{inspect(ctx);const step=script[n++]??'done',content=Array.isArray(step)?step.map((x,i)=>({type:'toolCall',id:`c${n}_${i}`,name:x.name,arguments:x.args})):[{type:'text',text:step}],message={role:'assistant',content,api:'openai-completions',provider:'mock',model:'mock',stopReason:Array.isArray(step)?'toolUse':'stop',timestamp:Date.now(),usage:{input:20,output:10,cacheRead:0,cacheWrite:0,totalTokens:30,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0}}},out=createAssistantMessageEventStream();queueMicrotask(()=>{out.push({type:'start',partial:message});out.push({type:'done',reason:message.stopReason,message});});return out;};}
 const config={baseURL:'https://mock.invalid/v1',apiKey:'mock',model:'mock'};
 await test('agent uses preserving pose tool while irrelevant mesh generators stay out of request',async()=>{let names=[];const r=await runModelingAgent({text:'调整资产人员姿态，保留原外形',document:base,selection:[],config,captureAvailable:()=>false,streamFn:stream([[{name:'pose_existing_parts',args:{assemblyId:id,joints:[{nodeIds:ids,pivot:[0,0,0],axis:[0,0,1],angle:90}]}}],'未视觉验收'],ctx=>{names.push(...ctx.messages.flatMap(m=>(m.toolsAdded??[]).map(t=>t.name)));})});assert.equal(p.assertPreservedAssetShape(base,r.result.doc),2);assert.equal(r.batch.incomplete,true);assert.ok(names.includes('pose_existing_parts'));assert.equal(names.includes('build_structured_component'),false);assert.equal(names.includes('pose_bimanual_interaction'),false);});
 await test('generic edit cannot bypass preserving-pose guard by deleting an original part',async()=>{const r=await runModelingAgent({text:'调整人员姿态',document:base,selection:[],config,captureAvailable:()=>false,streamFn:stream([[{name:'edit_scene',args:{summary:'隐式删手',operations:[{op:'delete',targetId:ids[1]}]}}],'无法保形，原状保留'])});assert.deepEqual(r.result.doc,base);assert.ok(r.activity.events.some(e=>e.includes('保留资产原外形')));});
 await test('metadata-only work cannot be submitted as a completed hand pose',async()=>{const r=await runModelingAgent({text:'调整人员手臂姿态',document:base,selection:[],config,captureAvailable:()=>false,streamFn:stream([[{name:'edit_scene',args:{summary:'只改名称',operations:[{op:'rename',targetId:ids[0],name:'已完成扶箱'}]}}],[{name:'submit_data_preview',args:{summary:'姿态完成'}}],'保持未完成'])});assert.ok(r.activity.events.some(e=>e.includes('姿态目标尚未实现')));assert.notEqual(r.activity.dataDraftSubmitted,true);assert.equal(r.batch.incomplete,true);});
 await test('different lookup words cannot sustain a no-edit loop indefinitely',async()=>{let calls=0;await assert.rejects(runModelingAgent({text:'调整人员姿态',document:base,selection:[],config,captureAvailable:()=>false,streamFn:stream(Array.from({length:12},(_,i)=>[{name:'find_scene_parts',args:{terms:['词'+i]}}]),()=>calls++)}),/连续4轮/);assert.ok(calls<=6);});
 await test('batch query supplies several components in one call and preserves all relevant IDs',async()=>{const r=await runModelingAgent({text:'查看人员零件',document:base,selection:[],config,captureAvailable:()=>false,streamFn:stream([[{name:'find_scene_parts_batch',args:{queries:[{assemblyId:id,terms:['衣袖']},{assemblyId:id,terms:['手掌']}]}}],'已查看'])});assert.equal(r.activity.toolCalls,1);assert.deepEqual(r.result.doc,base);});
 await test('same-view duplicate images are pruned without losing reference images or other scopes',()=>{const ref={role:'user',content:[{type:'image',data:'reference',mimeType:'image/png'}]},cap=(call,scope)=>({role:'toolResult',toolCallId:call,toolName:'capture_multiview',isError:false,content:[{type:'text',text:`revision=4 scope=${scope} view=front`},{type:'image',data:call.repeat(20000),mimeType:'image/png'}]});const msgs=[ref,cap('old','a'),cap('other','b'),cap('new','a')],before=JSON.stringify(msgs),out=compactAgentContext(msgs);assert.equal(JSON.stringify(msgs),before);assert.equal(out[0],ref);assert.equal(out[1].content.some(c=>c.type==='image'),false);assert.equal(out[2].content.some(c=>c.type==='image'),true);assert.equal(out[3].content.some(c=>c.type==='image'),true);console.log('duplicate capture serialized bytes',before.length,'->',JSON.stringify(out).length);});
 await test('pose request exposes less tool schema than general editing without removing preservation tool',async()=>{const run=text=>runModelingAgent({text,document:base,selection:[],config,captureAvailable:()=>false,streamFn:stream(['需要核对关节'])});const generic=await run('查看这个场景'),pose=await run('调整人员姿态');const before=generic.activity.timings[0].requestFootprint,after=pose.activity.timings[0].requestFootprint;assert.ok(after.toolSchemaChars<before.toolSchemaChars);console.log('pose tool schema chars',before.toolSchemaChars,'->',after.toolSchemaChars,'tool count',before.toolCount,'->',after.toolCount);});
 console.log(count+' preserved pose and efficiency checks passed; no real model or visual acceptance');
}finally{await server.close()}
