import 'fake-indexeddb/auto';
import assert from 'node:assert/strict';import React from 'react';import {JSDOM} from 'jsdom';import {createServer} from 'vite';
const dom=new JSDOM('<html><body></body></html>',{url:'https://example.test'});for(const n of ['window','document','HTMLElement','Node','MutationObserver','Event','MouseEvent','localStorage'])Object.defineProperty(globalThis,n,{value:dom.window[n],configurable:true});Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const {render,fireEvent,waitFor,cleanup,act}=await import('@testing-library/react');const server=await createServer({server:{middlewareMode:true},appType:'custom'});let count=0;const test=async(n,f)=>{await f();count++;console.log('PASS '+n);cleanup();};
try{
 const {ProjectLibrary}=await server.ssrLoadModule('/src/ui/ProjectLibrary.tsx'),w=await server.ssrLoadModule('/src/workspace.ts'),{saveLibraryProject}=await server.ssrLoadModule('/src/domain/workspaceLibrary.ts'),{useEditorStore:s}=await server.ssrLoadModule('/src/store.ts'),storage=await server.ssrLoadModule('/src/domain/modelAssetStorage.ts'),{instantiateAsset}=await server.ssrLoadModule('/src/domain/modelAssets.ts');
 await w.initializeWorkspace();let opened=0,assetSession,asset;
 await test('asset module creates an independent named editor project and rejects empty asset saves',async()=>{const ui=render(React.createElement(ProjectLibrary,{kind:'asset',onOpen:()=>opened++,onManage:()=>{}}));await waitFor(()=>assert.ok(ui.getByText('还没有保存的资产')));fireEvent.click(ui.getByRole('button',{name:'新建资产',exact:true}));fireEvent.change(ui.getByLabelText('新资产名称'),{target:{value:'独立测试托盘'}});fireEvent.click(ui.getByRole('button',{name:'创建资产',exact:true}));assert.equal(opened,1);assetSession=w.useWorkspaceStore.getState().activeId;assert.equal(w.useWorkspaceStore.getState().sessions.find(x=>x.id===assetSession).moduleKind,'asset');assert.equal(s.getState().doc.nodes.length,0);await assert.rejects(saveLibraryProject(),/空的/);});
 await test('asset saves without requiring scene selection, retains immutable versions and blocks preview',async()=>{await act(async()=>{s.getState().applyCommandBatch([{op:'createPrimitive',name:'托盘主体',parentId:null,geometry:{type:'box',params:{width:1.2,height:.15,depth:1}},transform:{position:[0,.075,0],scale:[1,1,1],rotationQuaternion:[0,0,0,1]},materialId:'mat_blue'}],'fixture');});assert.equal(s.getState().selection.length,0);await act(async()=>assert.match(await saveLibraryProject(),/v1/));asset=(await storage.listModelAssets())[0];const first=await storage.readModelAsset(asset.id,1);await act(async()=>s.setState({aiStatus:'previewing'}));await assert.rejects(saveLibraryProject(),/应用或放弃/);await act(async()=>s.setState({aiStatus:'idle'}));await act(async()=>s.getState().applyCommandBatch([{op:'rename',targetId:s.getState().doc.nodes[0].id,name:'已修订托盘'}],'rename'));await act(async()=>assert.match(await saveLibraryProject(),/v2/));assert.deepEqual(await storage.readModelAsset(asset.id,1),first);});
 await test('scene module creates a scene, pins asset v2, and edits never mutate the saved asset',async()=>{const ui=render(React.createElement(ProjectLibrary,{kind:'scene',onOpen:()=>opened++,onManage:()=>{}}));fireEvent.click(ui.getByRole('button',{name:'新建场景',exact:true}));fireEvent.change(ui.getByLabelText('新场景名称'),{target:{value:'托盘场景'}});fireEvent.click(ui.getByRole('button',{name:'创建场景',exact:true}));const v2=await storage.readModelAsset(asset.id,2);await act(async()=>s.getState().applyCommandBatch([instantiateAsset(v2,[2,0,0])],'insert'));assert.equal(s.getState().doc.nodes[0].modelAsset.version,2);await act(async()=>s.getState().applyCommandBatch([{op:'rename',targetId:s.getState().doc.nodes[0].id,name:'场景实例'}],'rename'));await act(async()=>assert.match(await saveLibraryProject(),/场景已保存/));assert.deepEqual(await storage.readModelAsset(asset.id,2),v2);const current=w.useWorkspaceStore.getState();assert.equal(current.sessions.find(x=>x.id===current.activeId).moduleKind,'scene');assert.equal(current.sessions.find(x=>x.id===current.activeId).savedRevision,s.getState().doc.revision);});
 await test('library asset edit reuses its editor without replacing a scene',async()=>{const oldScene=s.getState().doc.projectId;const ui=render(React.createElement(ProjectLibrary,{kind:'asset',onOpen:()=>opened++,onManage:()=>{}}));await waitFor(()=>assert.ok(ui.getByRole('button',{name:'查看资产 独立测试托盘'})));fireEvent.click(ui.getByRole('button',{name:'查看资产 独立测试托盘'}));fireEvent.click(ui.getByRole('button',{name:'编辑资产'}));await waitFor(()=>assert.notEqual(s.getState().doc.projectId,oldScene));assert.equal(w.useWorkspaceStore.getState().sessions.find(x=>x.id===w.useWorkspaceStore.getState().activeId).assetSource.version,2);assert.ok(w.useWorkspaceStore.getState().sessions.some(x=>x.snapshot.doc.projectId===oldScene));});
 await test('workspace backup preserves module type but imports asset projects without write authority to originals',async()=>{await w.flushWorkspace();const backup=w.exportWorkspaceBackup();assert.ok(JSON.parse(backup).sessions.some(x=>x.moduleKind==='asset'));const before=w.useWorkspaceStore.getState().sessions.length;w.importWorkspaceBackup(backup);const added=w.useWorkspaceStore.getState().sessions.slice(0,w.useWorkspaceStore.getState().sessions.length-before);assert.ok(added.some(x=>x.moduleKind==='asset'));assert.ok(added.every(x=>!x.assetSource));await w.flushWorkspace();});
 console.log(count+' dedicated library workflow checks passed');
}finally{cleanup();await server.close();dom.window.close();}
