import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';import React from 'react';import {createServer} from 'vite';
const dom=new JSDOM('<html><body></body></html>',{url:'https://example.test'});for(const k of ['window','document','HTMLElement','Node','MutationObserver','Event','MouseEvent','localStorage','location'])Object.defineProperty(globalThis,k,{value:dom.window[k],configurable:true});Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});globalThis.IS_REACT_ACT_ENVIRONMENT=true;let alerts=[];window.alert=t=>alerts.push(t);
const {render,fireEvent,cleanup,act}=await import('@testing-library/react');const server=await createServer({server:{middlewareMode:true},appType:'custom'});let passed=0;const test=async(n,f)=>{await f();passed++;console.log('PASS',n);cleanup()};
try{
const {PropertiesPanel}=await server.ssrLoadModule('/src/ui/PropertiesPanel.tsx');const {createInitialDoc,useEditorStore:s}=await server.ssrLoadModule('/src/store.ts');const {applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts');const {parseProject,serializeProject}=await server.ssrLoadModule('/src/domain/project.ts');
const shape={type:'box',params:{width:1,height:1,depth:1}},transform={position:[0,.5,0],rotationQuaternion:[0,0,0,1],scale:[1,1,1]};
const fixture=()=>applyBatch(createInitialDoc(),{operations:[{op:'createAssembly',name:'设备A',parts:[{name:'外壳',geometry:shape,transform,materialId:'mat_paint'},{name:'窗',geometry:shape,transform:{...transform,position:[1,.5,0]},materialId:'mat_glass'}]},{op:'createPrimitive',name:'其他设备',geometry:shape,transform,parentId:null,materialId:'mat_paint'}]}).doc;
const reset=(selection)=>{const doc=fixture();s.setState({doc,selection:selection(doc),aiStatus:'idle',previewDoc:null,pendingBatch:null,pendingResult:null,past:[],future:[]});alerts=[];return doc};
const mount=()=>render(React.createElement(PropertiesPanel));const color=(ui,value)=>{fireEvent.change(ui.getByLabelText('颜色十六进制'),{target:{value}});fireEvent.click(ui.getByRole('button',{name:'应用颜色'}))};const mat=(doc,n)=>doc.materials.find(m=>m.id===n.materialId);
await test('whole equipment can change color, preserves surface parameters, does not recolor shared-material neighbors, and undo/redo works',()=>{
 const before=reset(d=>d.nodes.slice(0,2).map(n=>n.id));const ui=mount();color(ui,'#ec8042');let d=s.getState().doc;for(let i=0;i<2;i++){assert.equal(mat(d,d.nodes[i]).baseColor,'#ec8042');assert.equal(mat(d,d.nodes[i]).roughness,mat(before,before.nodes[i]).roughness);assert.equal(mat(d,d.nodes[i]).opacity,mat(before,before.nodes[i]).opacity)}assert.equal(d.nodes[2].materialId,before.nodes[2].materialId);assert.equal(s.getState().past.length,1);act(()=>s.getState().undo());assert.deepEqual(s.getState().doc.nodes,before.nodes);act(()=>s.getState().redo());assert.equal(mat(s.getState().doc,s.getState().doc.nodes[0]).baseColor,'#ec8042');assert.deepEqual(parseProject(serializeProject(d)).nodes,d.nodes);
});
await test('original-material filter changes only equipment shell and preserves glass',()=>{const before=reset(d=>d.nodes.slice(0,2).map(n=>n.id));const ui=mount();fireEvent.change(ui.getByLabelText('外观修改范围'),{target:{value:'mat_paint'}});color(ui,'#3377cc');const d=s.getState().doc;assert.equal(mat(d,d.nodes[0]).baseColor,'#3377cc');assert.equal(d.nodes[1].materialId,before.nodes[1].materialId);assert.equal(d.nodes[2].materialId,before.nodes[2].materialId)});
await test('single-part dimensions and material parameters are editable and invalid geometry rolls back',()=>{reset(d=>[d.nodes[0].id]);const ui=mount();const field=ui.getByLabelText('几何参数 width');fireEvent.change(field,{target:{value:'2'}});fireEvent.blur(field);assert.equal(s.getState().doc.nodes[0].geometry.params.width,2);const invalid=ui.getByLabelText('几何参数 width');fireEvent.change(invalid,{target:{value:'-1'}});fireEvent.blur(invalid);assert.equal(s.getState().doc.nodes[0].geometry.params.width,2);assert.ok(alerts.length);fireEvent.change(ui.getByLabelText('粗糙度'),{target:{value:'0.1'}});fireEvent.click(ui.getByRole('button',{name:'应用材质参数'}));const d=s.getState().doc;assert.equal(mat(d,d.nodes[0]).roughness,.1);assert.equal(s.getState().past.length,2)});
await test('preview lock explains confirmation and blocks property mutation',()=>{const before=reset(d=>d.nodes.slice(0,2).map(n=>n.id));s.setState({aiStatus:'previewing',previewDoc:before});const ui=mount();assert.ok(ui.getByText(/当前是待确认预览/));assert.equal(ui.getByRole('button',{name:'应用颜色'}).closest('fieldset').disabled,true);color(ui,'#123456');assert.deepEqual(s.getState().doc,before);assert.equal(s.getState().past.length,0)});
await test('invalid appearance and mixed-validity batch cannot partly change nodes or materials',()=>{const d=fixture(),before=JSON.stringify(d);for(const patch of [{baseColor:'red'},{roughness:2},{opacity:-1}]){const r=applyBatch(d,{operations:[{op:'setAppearance',targetId:d.nodes[0].id,baseColor:'#445566'},{op:'setAppearance',targetId:d.nodes[1].id,...patch}]});assert.ok(r.errors.length);assert.equal(JSON.stringify(r.doc),before);assert.equal(JSON.stringify(d),before)}});
await test('assembly appearance uses one command even beyond per-batch command count',()=>{const d=applyBatch(createInitialDoc(),{operations:[{op:'createAssembly',name:'长货架',parts:[{name:'A',geometry:shape,transform,repeat:{count:100,step:[1,0,0]}},{name:'B',geometry:shape,transform,repeat:{count:100,step:[1,0,1]}},{name:'C',geometry:shape,transform,repeat:{count:100,step:[1,0,2]}}]}]}).doc;const r=applyBatch(d,{operations:[{op:'setAppearance',targetId:d.nodes[0].id,scope:'assembly',baseColor:'#123456'}]});assert.equal(r.errors.length,0);assert.equal(r.applied[0].before.nodes.length,300);assert.ok(r.doc.nodes.every(n=>mat(r.doc,n).baseColor==='#123456'))});
await test('single selected part transform never expands into the rest of its assembly',()=>{const before=reset(d=>[d.nodes[0].id]);const ui=mount();fireEvent.change(ui.getByLabelText('整体等比缩放倍数'),{target:{value:'2'}});fireEvent.click(ui.getByRole('button',{name:'应用整体变换'}));const d=s.getState().doc;assert.deepEqual(d.nodes[0].transform.scale,[2,2,2]);assert.deepEqual(d.nodes[1],before.nodes[1]);assert.deepEqual(d.nodes[2],before.nodes[2])});
await test('whole selection exposes rotation and uniform scale for all and only its members',()=>{const before=reset(d=>d.nodes.slice(0,2).map(n=>n.id));const ui=mount();fireEvent.change(ui.getByLabelText('整体旋转 Y'),{target:{value:'90'}});fireEvent.change(ui.getByLabelText('整体等比缩放倍数'),{target:{value:'1.5'}});fireEvent.click(ui.getByRole('button',{name:'应用整体变换'}));const d=s.getState().doc;assert.deepEqual(d.nodes[0].transform.scale,[1.5,1.5,1.5]);assert.deepEqual(d.nodes[1].transform.scale,[1.5,1.5,1.5]);assert.deepEqual(d.nodes[2],before.nodes[2])});
console.log(`${passed} property editing checks passed`);
}finally{cleanup();await server.close();dom.window.close()}
