import assert from 'node:assert/strict';import {createServer} from 'vite';
const server=await createServer({server:{middlewareMode:true},appType:'custom'});let n=0;const test=(name,f)=>{f();n++;console.log('PASS',name)};
try{
const {validateGeometry}=await server.ssrLoadModule('/src/domain/types.ts');const {buildPrimitiveGeometry}=await server.ssrLoadModule('/src/scene/geometry.ts');const {inspectGeometryQuality}=await server.ssrLoadModule('/src/domain/geometryQuality.ts');const {createInitialDoc}=await server.ssrLoadModule('/src/store.ts');const {parseModelResponse}=await server.ssrLoadModule('/src/ai/provider.ts');const {applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts');const {serializeProject,parseProject}=await server.ssrLoadModule('/src/domain/project.ts');
const solid={type:'lathe',params:{points:[[.14,0],[.15,.01],[.14,.035],[.02,.045]],segments:64,capStart:true,capEnd:true}};
const shell={type:'lathe',params:{points:[[.08,0],[.07,.035],[.045,.08],[.018,.11]],segments:64,wallThickness:.002}};
const edgeCounts=g=>{const p=g.attributes.position,idx=g.index.array,map=new Map();const key=i=>[p.getX(i),p.getY(i),p.getZ(i)].map(x=>x.toFixed(6).replace('-0.000000','0.000000')).join(',');for(let i=0;i<idx.length;i+=3){const v=[key(idx[i]),key(idx[i+1]),key(idx[i+2])];if(new Set(v).size<3)continue;for(let j=0;j<3;j++){const k=[v[j],v[(j+1)%3]].sort().join('|');map.set(k,(map.get(k)??0)+1)}}return [...map.values()]};
test('solid caps and hollow wall generate closed manifold surfaces without sealing shell aperture',()=>{for(const shape of [solid,shell]){assert.deepEqual(validateGeometry(shape),[]);const g=buildPrimitiveGeometry(shape);assert.ok([...g.attributes.normal.array].every(Number.isFinite));assert.ok(edgeCounts(g).every(x=>x===2));if(shape===shell){const p=g.attributes.position;assert.ok(Array.from({length:p.count},(_,i)=>Math.hypot(p.getX(i),p.getZ(i))).every(r=>r>.015));}g.dispose()}});
test('wall and endpoint flags reject invalid or contradictory inputs',()=>{for(const params of [{...shell.params,wallThickness:0},{...shell.params,wallThickness:.02},{...shell.params,wallThickness:NaN},{...shell.params,capStart:true},{...solid.params,capEnd:'true'}])assert.ok(validateGeometry({type:'lathe',params}).length)});
test('legacy unsealed surfaces retain geometry while reporting a cautious opening clue',()=>{const base=createInitialDoc();const batch=parseModelResponse(JSON.stringify({summary:'models',operations:[solid,shell,{...solid,params:{points:solid.params.points,segments:64}}].map((geometry,i)=>({op:'createPrimitive',name:'part '+i,geometry}))}));assert.equal(batch.operations.length,3);const r=applyBatch(base,batch);assert.deepEqual(r.errors,[]);const restored=parseProject(serializeProject(r.doc));assert.equal(restored.nodes[0].geometry.params.capEnd,true);assert.equal(restored.nodes[1].geometry.params.wallThickness,.002);assert.equal(inspectGeometryQuality(restored).length,1);assert.match(inspectGeometryQuality(restored)[0],/不能据此断言缺陷/)});
test('hollow tube has smooth radial sides and finite UVs',()=>{const g=buildPrimitiveGeometry({type:'tube',params:{outerRadius:.08,innerRadius:.075,height:.1}});assert.ok(edgeCounts(g).every(x=>x===2));const p=g.attributes.position,normal=g.attributes.normal;for(let i=0;i<130;i++){assert.ok(Math.abs(normal.getY(i))<1e-5);assert.ok(p.getX(i)*normal.getX(i)+p.getZ(i)*normal.getZ(i)>0)}assert.ok([...g.attributes.uv.array].every(Number.isFinite));g.dispose()});
test('coplanar overlap clues distinguish intersection from normal adjacent contact',()=>{const base=createInitialDoc();const part=(name,y)=>({name,geometry:{type:'box',params:{width:.2,height:.2,depth:.2}},transform:{position:[0,y,0],rotationQuaternion:[0,0,0,1],scale:[1,1,1]}});const make=y=>applyBatch(base,{operations:[{op:'createAssembly',name:'frame',parts:[part('a',0),part('b',y)]}]}).doc;assert.ok(inspectGeometryQuality(make(.1)).some(s=>s.includes('重合外表面')));assert.equal(inspectGeometryQuality(make(.2)).length,0)});
console.log(n+' revolved quality checks passed');
}finally{await server.close()}
