import assert from 'node:assert/strict';import {createServer} from 'vite';import {Color} from 'three';
const server=await createServer({server:{middlewareMode:true},appType:'custom'});let passed=0;const test=async(n,f)=>{await f();passed++;console.log('PASS',n)};
try{
const {createInitialDoc}=await server.ssrLoadModule('/src/store.ts');const {parseModelResponse}=await server.ssrLoadModule('/src/ai/provider.ts');const {applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts');const {inspectSceneQuality}=await server.ssrLoadModule('/src/domain/sceneQuality.ts');const {serializeProject,parseProject}=await server.ssrLoadModule('/src/domain/project.ts');
const part={name:'主体',geometry:{type:'box',params:{width:2,height:2,depth:2}},transform:{position:[0,1,0]}};
const recipe=(name,role='equipment',position=[0,0,0])=>({op:'createAssembly',name,sceneRole:role,planKey:name,zone:'生产区',position,parts:[part]});
const build=operations=>{const r=applyBatch(createInitialDoc(),parseModelResponse(JSON.stringify({summary:'结构检查',operations})));assert.equal(r.errors.length,0);return r.doc};
const plan={equipment:[{name:'加工机',count:2,features:['加工空间']}],composition:{zones:[{name:'生产区',purpose:'加工'}],connections:[{from:'加工机',to:'检测台',via:'输送线'}],support:[{name:'检测台',role:'workstation',count:1,purpose:'检测'},{name:'输送线',role:'conveyor',count:1,purpose:'工位连接'},{name:'操作人员',role:'person',count:2,purpose:'操作设备'}],palette:['灰蓝'],presentation:'整体有分区与层次'}};
await test('composition metadata and labels survive parser, duplication and save without changing shapes',()=>{const op=recipe('加工机');op.parts=[{...part,label:'CNC-01'}];const doc=build([op]);assert.equal(doc.nodes[0].sceneRole,'equipment');assert.equal(doc.nodes[0].planKey,'加工机');assert.equal(doc.nodes[0].label,'CNC-01');assert.equal(doc.nodes[0].materialId,'mat_paint');const copied=applyBatch(doc,{operations:[{op:'duplicateAssembly',targetId:doc.nodes[0].id,offset:[3,0,0]}]}).doc;assert.equal(copied.nodes[1].planKey,'加工机');assert.deepEqual(parseProject(serializeProject(copied)).nodes,copied.nodes);assert.equal(build([recipe('地板','floor')]).nodes[0].materialId,'mat_floor')});
await test('checklist finds missing support and links, while showing exact declared coverage',()=>{const doc=build([recipe('加工机'),recipe('加工机','equipment',[4,0,0]),recipe('检测台','workstation',[8,0,0])]);const r=inspectSceneQuality(doc,plan);assert.equal(r.coverage.find(v=>v.name==='加工机').actual,2);assert.equal(r.coverage.find(v=>v.name==='输送线').actual,0);assert.ok(r.issues.some(v=>v.includes('连接缺少')));assert.ok(r.issues.some(v=>v.includes('操作人员')));assert.ok(r.notes.some(v=>v.includes('不证明接口相接')))});
await test('geometric inspection distinguishes overlap candidates and unusual human scale without claiming exact collision',()=>{const doc=build([recipe('A'),recipe('B','equipment',[1,0,0]),{...recipe('人员','person',[5,0,0]),parts:[{...part,geometry:{type:'capsule',params:{radius:.05,length:.2}}}]}]);const r=inspectSceneQuality(doc);assert.ok(r.issues.some(v=>v.includes('包围盒交叠')));assert.ok(r.issues.some(v=>v.includes('高度约')));const moved=applyBatch(doc,{operations:[{op:'translateAssembly',targetId:doc.nodes[1].id,value:[4,0,0]}]}).doc;assert.ok(!inspectSceneQuality(moved).issues.some(v=>v.startsWith('设备包围盒交叠')))});
await test('existing assemblies can gain semantic tags atomically and invalid role is rejected',()=>{const doc=build([recipe('现有设备')]);const r=applyBatch(doc,parseModelResponse(JSON.stringify({summary:'补关联',operations:[{op:'setAssemblyMetadata',targetId:doc.nodes[0].id,sceneRole:'storage',planKey:'线边物料',zone:'暂存区'}]})));assert.equal(r.errors.length,0);assert.equal(r.doc.nodes[0].sceneRole,'storage');assert.deepEqual(r.doc.nodes[0].transform,doc.nodes[0].transform);assert.throws(()=>parseModelResponse(JSON.stringify({summary:'bad',operations:[{...recipe('bad'),sceneRole:'invented'}]})))});
await test('display backdrop changes presentation surfaces only and has a reversible light option',async()=>{const {Viewport}=await server.ssrLoadModule('/src/scene/Viewport.ts');const fake={scene:{},floorMaterial:{color:new Color()},markDirty(){this.dirty=true}};Viewport.prototype.setBackdrop.call(fake,'slate');assert.equal(fake.scene.background.getHexString(),'465b69');assert.equal(fake.floorMaterial.color.getHexString(),'536a77');Viewport.prototype.setBackdrop.call(fake,'light');assert.equal(fake.scene.background.getHexString(),'e8edef');assert.equal(fake.floorMaterial.color.getHexString(),'e0e7e9')});
await test('conveyor spacing reports measurable gaps and clears after moving the connection next to stations',()=>{const doc=build([recipe('加工机'),recipe('检测台','workstation',[3,0,0]),recipe('输送线','conveyor',[15,0,0])]);const r=inspectSceneQuality(doc,plan);assert.ok(r.issues.some(v=>v.includes('输送连接间距')));assert.equal(r.layout.length,3);const moved=applyBatch(doc,{operations:[{op:'translateAssembly',targetId:doc.nodes[2].id,value:[-13.5,0,0]}]}).doc;assert.ok(!inspectSceneQuality(moved,plan).issues.some(v=>v.includes('输送连接间距')))});
console.log(`${passed} scene composition checks passed`);
}finally{await server.close()}
