import 'fake-indexeddb/auto';
import assert from 'node:assert/strict';import React from 'react';import {JSDOM} from 'jsdom';import {createServer} from 'vite';
const dom=new JSDOM('<html><body></body></html>',{url:'https://example.test'});for(const n of ['window','document','HTMLElement','Node','MutationObserver','Event','MouseEvent','localStorage','Element','CustomEvent','HTMLInputElement','HTMLFormElement','NodeFilter','DocumentFragment'])Object.defineProperty(globalThis,n,{value:dom.window[n],configurable:true});Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});globalThis.IS_REACT_ACT_ENVIRONMENT=true;globalThis.getComputedStyle=dom.window.getComputedStyle;globalThis.requestAnimationFrame=fn=>setTimeout(fn,0);globalThis.cancelAnimationFrame=clearTimeout;window.requestAnimationFrame=globalThis.requestAnimationFrame;window.cancelAnimationFrame=clearTimeout;globalThis.ResizeObserver=class{observe(){} unobserve(){} disconnect(){}};
const {render:rtlRender,fireEvent,waitFor,cleanup,act}=await import('@testing-library/react');const {Theme}=await import('@radix-ui/themes');const render=ui=>rtlRender(ui,{wrapper:({children})=>React.createElement(Theme,null,children)});const server=await createServer({server:{middlewareMode:true},appType:'custom'});let count=0;const test=async(n,f)=>{await f();count++;console.log('PASS '+n);cleanup();};
try{
 const {StudioSettings}=await server.ssrLoadModule('/src/ui/StudioPages.tsx');const {WorkspaceTools}=await server.ssrLoadModule('/src/ui/WorkspaceTools.tsx');const w=await server.ssrLoadModule('/src/workspace.ts');await w.initializeWorkspace();
 await test('settings groups essential actions and removes duplicated asset migration',async()=>{let model=0,backup=0,history=0;const ui=render(React.createElement(StudioSettings,{onModel:()=>model++,onBackup:()=>backup++,onAssets:()=>{},onHistory:()=>history++}));assert.ok(ui.getByRole('heading',{name:'通用'}));assert.ok(ui.getByRole('heading',{name:'数据管理'}));assert.equal(ui.queryByRole('button',{name:'管理资产备份'}),null);fireEvent.click(ui.getByRole('button',{name:'模型配置'}));fireEvent.click(ui.getByRole('button',{name:'管理项目备份'}));fireEvent.click(ui.getByRole('button',{name:'管理项目',exact:true}));assert.deepEqual([model,backup,history],[1,1,1]);});
 await test('backup retains restore and privacy details without unrelated inspection tutorials',async()=>{let closed=0;const ui=render(React.createElement(WorkspaceTools,{onClose:()=>closed++}));assert.ok(ui.getByRole('heading',{name:'备份与恢复',exact:true}));assert.ok(ui.getByRole('button',{name:'下载工作台备份'}));assert.ok(ui.getByRole('button',{name:'导入备份为新会话'}));assert.equal(ui.queryByText('使用与验收'),null);assert.equal(ui.queryByText('运行状态'),null);assert.equal(ui.queryByText('场景检查'),null);assert.ok(ui.getByText(/不包含参考图、撤销历史或模型密钥/));fireEvent.click(ui.getByRole('button',{name:'关闭备份与恢复'}));assert.equal(closed,1);});
 await test('invalid restore is reported without changing existing projects',async()=>{const before=JSON.stringify(w.useWorkspaceStore.getState().sessions);const ui=render(React.createElement(WorkspaceTools,{onClose:()=>{}}));const input=document.querySelector('input[type=file]');fireEvent.change(input,{target:{files:[{size:3,text:async()=>'bad'}]}});await waitFor(()=>assert.ok(ui.getByRole('alert')));assert.equal(JSON.stringify(w.useWorkspaceStore.getState().sessions),before);assert.equal(ui.getByRole('button',{name:'下载工作台备份'}).disabled,false);});
 console.log(count+' settings refresh checks passed');
}finally{cleanup();await server.close();dom.window.close();}
