import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import React from 'react';
import { createServer } from 'vite';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'https://example.test'});
for(const name of ['window','document','HTMLElement','HTMLInputElement','Element','CustomEvent','Node','NodeFilter','MutationObserver','Event','MouseEvent','localStorage','location']) Object.defineProperty(globalThis,name,{value:dom.window[name],configurable:true});
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
globalThis.getComputedStyle=dom.window.getComputedStyle;globalThis.requestAnimationFrame=fn=>setTimeout(fn,0);globalThis.cancelAnimationFrame=clearTimeout;window.requestAnimationFrame=globalThis.requestAnimationFrame;window.cancelAnimationFrame=globalThis.cancelAnimationFrame;
globalThis.ResizeObserver=class{observe(){} unobserve(){} disconnect(){}};
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
let handler=async()=>new Response(JSON.stringify({data:[{id:'model-b'},{id:'model-a'}]}));
globalThis.fetch=(...args)=>handler(...args);
const {render,fireEvent,waitFor,cleanup,act}=await import('@testing-library/react');
const server=await createServer({server:{middlewareMode:true},appType:'custom'});
let passed=0;
try {
 const {SettingsDialog}=await server.ssrLoadModule('/src/ui/SettingsDialog.tsx');
 const {useEditorStore:store}=await server.ssrLoadModule('/src/store.ts');
 const mount=()=>{store.setState({aiConfig:null});return render(React.createElement(React.StrictMode,null,React.createElement(SettingsDialog,{onClose:()=>{}})))};
 const credentials=(ui)=>{fireEvent.change(ui.getByLabelText('API 根地址',{exact:false}),{target:{value:'https://provider.test/v1'}});fireEvent.change(ui.getByLabelText('API Key',{exact:true}),{target:{value:'test-key-only'}});fireEvent.blur(ui.getByLabelText('API Key',{exact:true}))};
 let ui=mount();credentials(ui);
 await waitFor(()=>assert.equal(ui.getByRole('combobox',{name:'选择模型'}).options.length,3));
 fireEvent.change(ui.getByRole('combobox',{name:'选择模型'}),{target:{value:'model-a'}});
 assert.equal(ui.getByRole('button',{name:'保存配置'}).disabled,false);
 fireEvent.click(ui.getByRole('button',{name:'保存配置'}));
 assert.equal(store.getState().aiConfig.model,'model-a');console.log('PASS URL/key discovers models and selection saves under StrictMode');passed++;cleanup();
 handler=async()=>new Response(JSON.stringify({error:'origin not allowed'}),{status:403});
 ui=mount();credentials(ui);await waitFor(()=>assert.ok(ui.getByRole('alert').textContent.includes('origin not allowed')));
 assert.equal(ui.queryByText('服务不提供列表？手动填写模型名'),null);assert.equal(ui.getByRole('button',{name:'保存配置'}).disabled,true);console.log('PASS origin rejection does not suggest manual bypass');passed++;cleanup();
 handler=async()=>new Response('missing',{status:404});ui=mount();credentials(ui);
 await waitFor(()=>assert.ok(ui.getByRole('alert')));fireEvent.click(ui.getByText('服务不提供列表？手动填写模型名'));
 fireEvent.change(ui.getByLabelText('手动模型名（请以服务文档为准）'),{target:{value:'custom-model'}});assert.equal(ui.getByRole('button',{name:'保存配置'}).disabled,false);console.log('PASS unsupported model list offers explicit manual fallback');passed++;cleanup();
 let releaseOld;handler=()=>new Promise(resolve=>{releaseOld=resolve});ui=mount();credentials(ui);await waitFor(()=>assert.ok(releaseOld));
 handler=async()=>new Response(JSON.stringify({data:[{id:'new-model'}]}));fireEvent.change(ui.getByLabelText('API 根地址',{exact:false}),{target:{value:'https://new-provider.test/v1'}});fireEvent.blur(ui.getByLabelText('API 根地址',{exact:false}));
 await waitFor(()=>assert.equal(ui.getByRole('combobox',{name:'选择模型'}).value,'new-model'));
 await act(async()=>releaseOld(new Response(JSON.stringify({data:[{id:'old-model'}]}))));assert.equal(ui.queryByRole('option',{name:'old-model'}),null);console.log('PASS changed endpoint ignores stale model response');passed++;cleanup();
 handler=async()=>new Response(JSON.stringify({data:[{id:'saved-model'}]}));store.setState({aiConfig:{baseURL:'https://provider.test/v1',apiKey:'test-only',model:'saved-model',useMock:false}});
 ui=render(React.createElement(React.StrictMode,null,React.createElement(SettingsDialog,{onClose:()=>{}})));await waitFor(()=>assert.equal(ui.getByRole('combobox',{name:'选择模型'}).value,'saved-model'));console.log('PASS reopened configuration loads and retains valid saved model');passed++;cleanup();
 handler=async()=>new Response(JSON.stringify({data:[{id:'compatible'}]}));ui=mount();credentials(ui);await waitFor(()=>assert.equal(ui.getByRole('combobox',{name:'选择模型'}).value,'compatible'));
 assert.equal(ui.getByRole('combobox',{name:'建模执行方式'}).value,'pi');
 fireEvent.change(ui.getByRole('combobox',{name:'建模执行方式'}),{target:{value:'single'}});fireEvent.click(ui.getByRole('checkbox',{name:/实时接收模型输出/}));fireEvent.click(ui.getByRole('button',{name:'保存配置'}));assert.equal(store.getState().aiConfig.agentMode,'single');assert.equal(store.getState().aiConfig.stream,false);console.log('PASS explicit compatibility mode and non-stream choice persist');passed++;cleanup();
 console.log(`${passed} simulated component checks passed; no real API requests`);
} finally {cleanup();await server.close();dom.window.close()}
