import assert from 'node:assert/strict';import fs from 'node:fs';import {gunzipSync} from 'node:zlib';import {createServer} from 'vite';
const server=await createServer({server:{middlewareMode:true},appType:'custom'});
try{
 const {parseProject,serializeProject}=await server.ssrLoadModule('/src/domain/project.ts'),{validateDocument}=await server.ssrLoadModule('/src/domain/types.ts'),{createModelAsset,parseModelAsset,instantiateAsset}=await server.ssrLoadModule('/src/domain/modelAssets.ts'),{applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts'),{inspectAssetInstance}=await server.ssrLoadModule('/src/domain/assetInstances.ts');
 const {restoreModelStructure,structureFrame}=await server.ssrLoadModule('/src/domain/structuredComponent.ts');
 const base=parseProject(gunzipSync(fs.readFileSync('tests/benchmarks/fixtures/singletons-v75.json.gz')).toString()),snapshot=JSON.stringify(base),groups=new Map(base.nodes.map(n=>[n.assemblyId,n]));assert.equal(base.nodes.length,102);assert.equal(groups.size,3);
 for(const [id,node] of groups){const members=base.nodes.filter(n=>n.assemblyId===id),blueprint={key:'replay-'+id,name:node.assemblyName,purpose:'检验真实数据的结构关联持久化，不认证质量',detailLevel:'closeup',detailReason:'固定数据回放',silhouette:'保留原始实测几何',features:[{key:'whole',name:'全部真实零件',role:'form',geometryApproach:'assembly'}],negativeSpaces:[],views:['front','side']},binding={blueprintKey:blueprint.key,componentId:id,features:[{key:'whole',nodeIds:members.map(n=>n.id)}]};const bound=applyBatch(base,{operations:[{op:'setAssemblyMetadata',targetId:node.id,structure:{blueprint,binding}}]});assert.deepEqual(bound.errors,[]);const saved=parseProject(serializeProject(bound.doc));assert.deepEqual(restoreModelStructure(saved).bindings,[binding]);assert.doesNotThrow(()=>structureFrame(saved.nodes.filter(n=>n.assemblyId===id)));assert.deepEqual(saved.nodes.filter(n=>n.assemblyId!==id),base.nodes.filter(n=>n.assemblyId!==id));const asset=parseModelAsset(JSON.stringify(createModelAsset(base,[node.id],{name:node.assemblyName,category:'其他'}))),assetSnapshot=JSON.stringify(asset);
 const first=applyBatch(base,{operations:[instantiateAsset(asset,[0,0,4],90)]});assert.deepEqual(first.errors,[]);const second=applyBatch(first.doc,{operations:[instantiateAsset(asset,[0,0,7],180)]});assert.deepEqual(second.errors,[]);assert.deepEqual(validateDocument(second.doc),[]);
 const instances=[...new Set(second.doc.nodes.filter(n=>n.modelAsset).map(n=>n.modelAsset.instanceId))];assert.equal(instances.length,2);for(const iid of instances)assert.equal(inspectAssetInstance(second.doc,asset,iid).intrinsicUnchanged,true);
 const target=second.doc.nodes.find(n=>n.modelAsset?.instanceId===instances[0]),position=[...target.transform.position];position[1]+=.025;
 const edited=applyBatch(second.doc,{operations:[{op:'setTransform',targetId:target.id,transform:{position}}]});assert.deepEqual(edited.errors,[]);assert.equal(inspectAssetInstance(edited.doc,asset,instances[0]).intrinsicUnchanged,false);assert.equal(inspectAssetInstance(edited.doc,asset,instances[1]).intrinsicUnchanged,true);
 assert.deepEqual(edited.doc.nodes.filter(n=>base.nodes.some(o=>o.id===n.id)),base.nodes);assert.equal(JSON.stringify(asset),assetSnapshot);assert.equal(JSON.stringify(base),snapshot);
 assert.deepEqual(parseProject(serializeProject(edited.doc)).nodes,edited.doc.nodes);console.log('PASS real singleton structure persistence, asset roundtrip, two rotated instances, isolated local edit and change detection: '+node.assemblyName+' ('+asset.nodes.length+' parts)');
 }
 const {targetedSceneContext}=await server.ssrLoadModule('/src/ai/modelingAgent.ts'),{buildSceneContext}=await server.ssrLoadModule('/src/ai/provider.ts');const ids=new Set([base.nodes[0].id]),old={...buildSceneContext(base,[]),nodes:buildSceneContext(base,[]).nodes.filter(n=>ids.has(n.id)),materials:base.materials},current=targetedSceneContext(base,[],ids);assert.deepEqual(current.nodes,old.nodes);assert.deepEqual(current.selection,old.selection);assert.ok(current.materials.every(m=>current.nodes.some(n=>n.materialId===m.id)));assert.equal(current.materials.length,1);assert.ok(JSON.stringify(current).length<JSON.stringify(old).length);console.log('PASS real-scene targeted read keeps exact target data and only relevant materials '+JSON.stringify({beforeChars:JSON.stringify(old).length,afterChars:JSON.stringify(current).length,beforeMaterials:old.materials.length,afterMaterials:current.materials.length,notTokenMeasurement:true}));
 console.log('4 real singleton replay checks passed; no model calls and no visual quality certification');
}finally{await server.close();}
