import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:http';
import {openTeam,teamMiddleware} from '../server/team/service.mjs';
import {validateTeamPayload} from '../dist-team/validator.mjs';
const dir=await mkdtemp(join(tmpdir(),'chat3d-team-'));let team=openTeam(join(dir,'test.sqlite'));let server;
const scene={format:'chat3d-project',version:1,scene:{schemaVersion:1,projectId:'test-scene',revision:0,unit:'m',upAxis:'Y',nodes:[],materials:[],assets:[]}};
const check=(label,fn)=>{fn();console.log('PASS '+label);};
try{
 const alice=team.provision('alice','isolated-test-password-a'),bob=team.provision('bob','isolated-test-password-b'),viewer=team.provision('viewer','isolated-test-password-v','viewer'),admin=team.provision('admin','isolated-test-password-x','admin');
 check('password hashes only, no plaintext',()=>{assert.notEqual(team.db.prepare('SELECT password FROM users WHERE id=?').get(alice.id).password,'isolated-test-password-a');});
 check('anonymous and invalid password denied',()=>{assert.throws(()=>team.authenticate('bad'),e=>e.status===401);assert.throws(()=>team.login('alice','incorrect'),e=>e.status===401);});
 const a=team.login('alice','isolated-test-password-a'),b=team.login('bob','isolated-test-password-b');
 const request={kind:'scene',name:'装配线',description:'测试场景',payload:scene,key:crypto.randomUUID(),expectedVersion:0};
 check('unpublished draft is invisible',()=>assert.deepEqual(team.list('scene'),[]));
 const first=team.publish(alice,request,validateTeamPayload);
 check('two members can read/search the same published scene',()=>{assert.equal(team.authenticate(b.token).id,bob.id);assert.equal(team.list('scene','装配')[0].id,first.id);assert.deepEqual(team.read(first.id,1).payload,scene);});
 check('duplicate clicks and lost-response retry are idempotent',()=>{assert.deepEqual(team.publish(alice,request,validateTeamPayload),first);assert.equal(team.list('scene').length,1);assert.throws(()=>team.publish(alice,{...request,name:'changed'},validateTeamPayload),e=>e.status===409);});
 const update={...request,itemId:first.id,expectedVersion:1,key:crypto.randomUUID(),name:'装配线新版'};
 check('non-owner and viewer writes denied',()=>{assert.throws(()=>team.publish(bob,update,validateTeamPayload),e=>e.status===403);assert.throws(()=>team.publish(viewer,{...request,key:crypto.randomUUID()},validateTeamPayload),e=>e.status===403);});
 const second=team.publish(alice,update,validateTeamPayload);
 check('immutable previous version and stale update conflict',()=>{assert.equal(second.version,2);assert.equal(team.read(first.id,1).name,request.name);assert.throws(()=>team.publish(alice,{...update,key:crypto.randomUUID()},validateTeamPayload),e=>e.status===409);});
 check('admin may append, never overwrite versions',()=>assert.equal(team.publish(admin,{...update,expectedVersion:2,key:crypto.randomUUID()},validateTeamPayload).version,3));
 check('invalid payload is rejected without partial publication',()=>{assert.throws(()=>team.publish(alice,{...request,key:crypto.randomUUID(),payload:{}},validateTeamPayload),e=>e.status===400);assert.equal(team.list('scene').length,1);});
 team.db.exec("CREATE TRIGGER simulated_failure BEFORE INSERT ON versions WHEN NEW.name='storage-failure' BEGIN SELECT RAISE(ABORT,'simulated storage failure'); END;");
 const retry={...request,name:'storage-failure',key:crypto.randomUUID()};const count=team.list('scene').length;
 assert.throws(()=>team.publish(alice,retry,validateTeamPayload),/simulated storage failure/);assert.equal(team.list('scene').length,count);
 team.db.exec('DROP TRIGGER simulated_failure');team.publish(alice,retry,validateTeamPayload);assert.equal(team.list('scene').length,count+1);console.log('PASS storage failure rolls back all writes and retry succeeds');
 team.close();team=openTeam(join(dir,'test.sqlite'));
 check('restart retains identities, sessions and immutable publications',()=>{assert.equal(team.authenticate(a.token).id,alice.id);assert.deepEqual(team.read(first.id,1).payload,scene);assert.equal(team.list('scene').find(x=>x.id===first.id).version,3);assert.deepEqual(team.publish(alice,request,validateTeamPayload),first);});
 const middleware=teamMiddleware(team,validateTeamPayload,{origins:['http://tauri.localhost']});server=createServer((req,res)=>middleware(req,res,()=>res.writeHead(404).end()));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}/api/team/`;
 const call=(path,options={})=>fetch(base+path,options);
 assert.equal((await call('items?kind=scene')).status,401);
 assert.equal((await call('items?kind=scene',{headers:{Origin:'https://evil.invalid',Authorization:`Bearer ${a.token}`}})).status,403);
 const cors=await call('publish',{method:'OPTIONS',headers:{Origin:'http://tauri.localhost'}});assert.equal(cors.status,204);assert.equal(cors.headers.get('access-control-allow-origin'),'http://tauri.localhost');
 assert.equal((await call('publish',{method:'POST',headers:{Authorization:`Bearer ${a.token}`,'Content-Type':'application/json'},body:'null'})).status,400);
 const result=await call('items?kind=scene',{headers:{Authorization:`Bearer ${b.token}`}});assert.equal(result.status,200);assert.equal((await result.json()).length,2);
 console.log('PASS HTTP auth, origin allowlist, preflight and malformed request checks');
 team.logout(a.token);assert.throws(()=>team.authenticate(a.token),e=>e.status===401);team.disable('bob');assert.throws(()=>team.authenticate(b.token),e=>e.status===401);console.log('PASS logout and account disable revoke access');
}finally{if(server)await new Promise(resolve=>server.close(resolve));team.close();await rm(dir,{recursive:true,force:true});}
