import 'fake-indexeddb/auto';
import assert from 'node:assert/strict';import React from 'react';import {JSDOM} from 'jsdom';import {createServer} from 'vite';
const dom=new JSDOM('<html><body></body></html>',{url:'https://example.test'});for(const n of ['window','document','HTMLElement','Node','MutationObserver','Event','MouseEvent','localStorage','Element','CustomEvent','HTMLInputElement','NodeFilter','DocumentFragment'])Object.defineProperty(globalThis,n,{value:dom.window[n],configurable:true});Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});globalThis.IS_REACT_ACT_ENVIRONMENT=true;globalThis.getComputedStyle=dom.window.getComputedStyle;globalThis.requestAnimationFrame=fn=>setTimeout(fn,0);globalThis.cancelAnimationFrame=clearTimeout;window.requestAnimationFrame=globalThis.requestAnimationFrame;window.cancelAnimationFrame=clearTimeout;globalThis.ResizeObserver=class{observe(){}unobserve(){}disconnect(){}};
const {render:renderUI,fireEvent,waitFor,cleanup,act}=await import('@testing-library/react');const {Theme}=await import('@radix-ui/themes');const render=ui=>renderUI(ui,{wrapper:({children})=>React.createElement(Theme,null,children)});const server=await createServer({server:{middlewareMode:true,hmr:false},appType:'custom'});let count=0;const test=async(n,f)=>{await f();count++;console.log('PASS '+n);cleanup();};
const originalFetch=globalThis.fetch;let calls=[],failNext=true;
globalThis.fetch=async(url,init)=>{
 const path=String(url);if(path.endsWith('/login'))return Response.json({token:'temporary-test-token',user:{id:'alice',name:'alice',role:'member'}});
 if(path.includes('/items?'))return Response.json([]);
 if(path.endsWith('/publish')){calls.push(JSON.parse(init.body));if(failNext){failNext=false;throw Error('测试网络故障');}return Response.json({id:'shared',version:1});}
 throw Error('Unexpected test request '+path);
};
try{
 const {TeamLibrary}=await server.ssrLoadModule('/src/ui/TeamLibrary.tsx'),w=await server.ssrLoadModule('/src/workspace.ts'),{useEditorStore:s}=await server.ssrLoadModule('/src/store.ts'),{saveLibraryProject}=await server.ssrLoadModule('/src/domain/workspaceLibrary.ts');
 await w.initializeWorkspace();w.createSession(undefined,{moduleKind:'asset',title:'隔离测试资产'});s.getState().applyCommandBatch([{op:'createPrimitive',name:'box',parentId:null,geometry:{type:'box',params:{width:1,height:1,depth:1}},transform:{position:[0,0,0],scale:[1,1,1],rotationQuaternion:[0,0,0,1]},materialId:'mat_blue'}],'fixture');await saveLibraryProject();
 const ui=render(React.createElement(TeamLibrary,{kind:'asset'}));fireEvent.click(ui.getByRole('button',{name:'打开团队资产库'}));
 fireEvent.change(ui.getByLabelText('团队服务地址'),{target:{value:'http://localhost:1420'}});fireEvent.change(ui.getByLabelText('团队账号'),{target:{value:'alice'}});fireEvent.change(ui.getByLabelText('团队密码'),{target:{value:'isolated-password'}});fireEvent.click(ui.getByRole('button',{name:'登录团队'}));
 await waitFor(()=>assert.ok(ui.getByRole('option',{name:/隔离测试资产/})));const option=ui.getByRole('option',{name:/隔离测试资产/});fireEvent.change(ui.getByLabelText('发布本地内容'),{target:{value:option.value}});fireEvent.click(ui.getByRole('button',{name:'准备发布'}));await waitFor(()=>assert.ok(ui.getByRole('button',{name:'确认发布'})));
 assert.equal(calls.length,0);fireEvent.click(ui.getByRole('button',{name:'取消',exact:true}));assert.equal(calls.length,0);assert.ok(ui.getByText('发布已取消，没有上传。'));console.log('PASS UI prepare and cancellation never upload local data');
 fireEvent.click(ui.getByRole('button',{name:'准备发布'}));await waitFor(()=>assert.ok(ui.getByRole('button',{name:'确认发布'})));const confirm=ui.getByRole('button',{name:'确认发布'});fireEvent.click(confirm);fireEvent.click(confirm);await waitFor(()=>assert.ok(ui.getByText('测试网络故障')));assert.equal(calls.length,1);
 fireEvent.click(ui.getByRole('button',{name:'重试同一次发布'}));await waitFor(()=>assert.ok(ui.getByText('已发布 v1')));assert.equal(calls.length,2);assert.deepEqual(calls[0],calls[1]);assert.equal(calls[0].payload.messages,undefined);assert.equal(calls[0].payload.apiKey,undefined);assert.equal(localStorage.getItem('chat3d.team.address'),'http://localhost:1420');assert.ok(!JSON.stringify(localStorage).includes('temporary-test-token'));console.log('PASS UI duplicate-click lock, failure retry snapshot/key and memory-only credentials');
}finally{globalThis.fetch=originalFetch;cleanup();await server.close();dom.window.close();}
