import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {createServer} from 'vite';
import * as THREE from 'three';
const server=await createServer({server:{middlewareMode:true},appType:'custom'});let count=0;
const test=async(name,fn)=>{await fn();count++;console.log('PASS',name)};
try{
 const {buildWorkshopNodes}=await server.ssrLoadModule('/src/workshop/adapter.ts');
 const {createWorkshop}=await server.ssrLoadModule('/src/workshop/model.ts');
 const {createInitialDoc,useEditorStore:store}=await server.ssrLoadModule('/src/store.ts');
 const {applyBatch,estimateCost}=await server.ssrLoadModule('/src/domain/commands.ts');
 const {parseModelResponse}=await server.ssrLoadModule('/src/ai/provider.ts');
 const {validateDocument}=await server.ssrLoadModule('/src/domain/types.ts');
 const {serializeProject,parseProject}=await server.ssrLoadModule('/src/domain/project.ts');
 const {buildExportScene,exportGlb}=await server.ssrLoadModule('/src/scene/export.ts');
 const base=createInitialDoc(),op={op:'createTemplate',templateId:'smt_workshop',parameters:{}},r=applyBatch(base,{operations:[op]});
 await test('whole-workshop command produces the reference layout as editable validated nodes',()=>{assert.equal(r.errors.length,0,r.errors.map(e=>e.message).join());assert.equal(validateDocument(r.doc).length,0);assert.ok(r.doc.nodes.length>1300);assert.ok(r.doc.nodes.length<estimateCost([op]).newNodes);const names=new Set(r.doc.nodes.map(n=>n.assemblyName));assert.equal([...names].filter(n=>/^A-/.test(n)).length,7);assert.equal([...names].filter(n=>/^B-/.test(n)).length,7);assert.ok(names.has('设备操作人员'));assert.ok(names.has('AGV-01 · 自主移动搬运车'));assert.ok(r.doc.nodes.some(n=>n.label?.includes('QUALITY')));assert.equal(base.nodes.length,0)});
 await test('conversion preserves every source mesh world matrix and material color',()=>{const source=createWorkshop({text:false});source.root.updateMatrixWorld(true);let i=0;source.root.traverse(mesh=>{if(!mesh.isMesh)return;const n=r.doc.nodes[i++];const matrix=new THREE.Matrix4().compose(new THREE.Vector3().fromArray(n.transform.position),new THREE.Quaternion().fromArray(n.transform.rotationQuaternion),new THREE.Vector3().fromArray(n.transform.scale));matrix.elements.forEach((v,j)=>assert.ok(Math.abs(v-mesh.matrixWorld.elements[j])<1e-6));if(!n.label){const mat=r.doc.materials.find(m=>m.id===n.materialId);assert.equal(mat.baseColor.toLowerCase(),'#'+mesh.material.color.getHexString());}});assert.equal(i,r.doc.nodes.length)});
 await test('line/people/zone parameters change content and malformed scope is rejected',()=>{const one=buildWorkshopNodes({lines:1,people:0,materialZone:0,qualityZone:0});assert.ok(one.length<r.doc.nodes.length);assert.ok(!one.some(n=>n.assemblyName.startsWith('B-')||n.assemblyName==='设备操作人员'||n.assemblyName.startsWith('WH-')||n.assemblyName.startsWith('QC-')));for(const p of [{lines:3},{people:2},{width:10},{lines:NaN}])assert.throws(()=>buildWorkshopNodes(p));assert.throws(()=>parseModelResponse(JSON.stringify({summary:'车间',operations:[op]})))});
 await test('existing workshop refuses a duplicate full scene instead of overlapping or replacing work',()=>{const second=applyBatch(r.doc,{operations:[op]});assert.equal(second.errors.length,1);assert.equal(second.doc,r.doc)});
 await test('assembly editing preserves other machines and undoes without losing identities',()=>{const node=r.doc.nodes.find(n=>n.assemblyName.startsWith('A-04'));const before=structuredClone(r.doc);const edit=applyBatch(r.doc,{operations:[{op:'translateAssembly',targetId:node.id,value:[0,0,1]}]});assert.equal(edit.errors.length,0);edit.doc.nodes.forEach((n,i)=>assert.ok(Math.abs(n.transform.position[2]-before.nodes[i].transform.position[2]-(n.assemblyId===node.assemblyId?1:0))<1e-8));store.setState({doc:r.doc,past:[],future:[],messages:[],aiStatus:'previewing',pendingBatch:{requestId:'workshop-edit',projectId:r.doc.projectId,baseRevision:r.doc.revision,selectedIds:[],summary:'move',operations:[]},pendingResult:edit});store.getState().confirmPending();store.getState().undo();assert.deepEqual(store.getState().doc.nodes,before.nodes);store.getState().redo();assert.deepEqual(store.getState().doc.nodes,edit.doc.nodes)});
 await test('project roundtrip and GLB scene retain labels, group metadata, colors and extents',()=>{const doc=parseProject(serializeProject(r.doc));assert.deepEqual(doc.nodes,r.doc.nodes);const scene=buildExportScene(doc),box=new THREE.Box3().setFromObject(scene);assert.ok(box.min.x>-16&&box.max.x<16);assert.ok(box.max.y<5);assert.equal(scene.children.length,doc.nodes.length);assert.ok(scene.children.some(n=>n.userData.label));scene.traverse(n=>{n.geometry?.dispose();n.material?.dispose()})});
 await test('app material renderer carries matching emission and glass depth behavior',async()=>{const {createSceneMaterial}=await server.ssrLoadModule('/src/scene/material.ts');const screen=createSceneMaterial(r.doc.materials.find(m=>m.id==='ws_screen'));assert.equal(screen.emissiveIntensity,.35);assert.equal(screen.emissive.getHexString(),'1f6468');screen.dispose();const glass=createSceneMaterial(r.doc.materials.find(m=>m.id==='ws_glass'));assert.equal(glass.depthWrite,false);assert.equal(glass.opacity,.67);glass.dispose()});
 if(process.env.EXPORT_WORKSHOP){globalThis.FileReader=class{readAsArrayBuffer(blob){blob.arrayBuffer().then(v=>{this.result=v;this.onloadend?.()})}};const doc={...r.doc,nodes:r.doc.nodes.filter(n=>!n.label)};await writeFile('/workspace/shared/chat3d-integrated-workshop.glb',Buffer.from(await exportGlb(doc)));}
 console.log(`${count} integrated workshop checks passed`);
}finally{await server.close()}
