import assert from 'node:assert/strict';
import {indexedDB} from 'fake-indexeddb';
import {createServer} from 'vite';
globalThis.indexedDB=indexedDB;
const server=await createServer({server:{middlewareMode:true},appType:'custom'});let count=0;
const test=async(name,fn)=>{await fn();count++;console.log('PASS',name)};
try{
 const {useEditorStore:editor,createInitialDoc}=await server.ssrLoadModule('/src/store.ts');
 const {applyBatch}=await server.ssrLoadModule('/src/domain/commands.ts');
 const w=await server.ssrLoadModule('/src/workspace.ts');
 const storage=await server.ssrLoadModule('/src/domain/workspaceStorage.ts');
 editor.setState({doc:createInitialDoc(),messages:[],composerText:'',composerImages:[],past:[],future:[],aiStatus:'idle',aiConfig:{baseURL:'https://example.test',apiKey:'MUST-NOT-PERSIST',model:'mock',useMock:true}});
 await test('progress saving is coalesced without delaying edits, user messages or checkpoints',async()=>{const {progressOnlyChange}=await server.ssrLoadModule('/src/domain/workspaceSavePolicy.ts');const msg={id:'a',text:'task',run:{status:'running',startedAt:1,activity:{turn:1}}};const old={aiStatus:'generating',doc:{},pendingBatch:null,pendingResult:null,past:[],future:[],dirty:false,composerText:'',composerImages:[],messages:[msg],lastRun:{turn:1}};
 assert.equal(progressOnlyChange({...old,lastRun:{turn:2}},old),true);assert.equal(progressOnlyChange({...old,messages:[{...msg,run:{...msg.run,activity:{turn:2}}}]},old),true);
 for(const patch of [{doc:{}},{pendingResult:{}},{composerText:'new instruction'},{messages:[msg,{id:'b',text:'change'}]},{messages:[{...msg,text:'changed'}]},{aiStatus:'previewing'},{messages:[{...msg,run:{...msg.run,status:'stopped'}}]}])assert.equal(progressOnlyChange({...old,...patch},old),false);
 });
 await test('workspace initialization preserves current scene and excludes credentials from durable data',async()=>{await w.initializeWorkspace();await w.flushWorkspace();const saved=await storage.readWorkspace();assert.ok(saved.sessions.length);assert.ok(!JSON.stringify(saved).includes('MUST-NOT-PERSIST'));assert.equal(w.useWorkspaceStore.getState().ready,true)});
 const first=w.useWorkspaceStore.getState().activeId;
 await test('sessions isolate conversation, reference image, composer draft and geometry',async()=>{
  editor.getState().addUserMessage('第一台设备',['data:image/jpeg;base64,YWJj']);editor.getState().setComposerText('继续修改轮子');editor.getState().setComposerImages(['data:image/jpeg;base64,YWJj']);
  editor.getState().applyCommandBatch([{op:'createPrimitive',name:'A',parentId:null,geometry:{type:'box',params:{width:1,height:1,depth:1}},transform:{position:[0,.5,0],scale:[1,1,1],rotationQuaternion:[0,0,0,1]},materialId:'mat_gray'}],'create');
  assert.equal(w.createSession(),true);assert.equal(editor.getState().doc.nodes.length,0);assert.equal(editor.getState().messages.length,0);assert.equal(editor.getState().composerText,'');
  const second=w.useWorkspaceStore.getState().activeId;editor.getState().addUserMessage('第二台设备');assert.equal(w.switchSession(first),true);assert.equal(editor.getState().doc.nodes[0].name,'A');assert.equal(editor.getState().messages[0].text,'第一台设备');assert.equal(editor.getState().composerText,'继续修改轮子');assert.equal(editor.getState().composerImages.length,1);assert.equal(editor.getState().past.length,1);assert.equal(w.switchSession(second),true);assert.equal(editor.getState().messages[0].text,'第二台设备');
 });
 await test('active generation allows new/switch but only locks its own trash action',async()=>{const origin=w.useWorkspaceStore.getState().activeId;for(const status of ['generating','capturing']){w.switchSession(origin);editor.setState({aiStatus:status});assert.equal(w.createSession(),true);assert.equal(w.switchSession(first),true);assert.equal(w.trashSession(origin),false);assert.equal(w.getSessionEditor(origin).getState().aiStatus,status);w.getSessionEditor(origin).setState({aiStatus:'idle'});}w.switchSession(origin)});
 await test('rename remains stable, trash is recoverable and never permanently deletes snapshots',async()=>{w.renameSession(first,'AGV 原型');assert.equal(w.useWorkspaceStore.getState().sessions.find(s=>s.id===first).title,'AGV 原型');assert.equal(w.trashSession(first),true);assert.ok(w.useWorkspaceStore.getState().sessions.find(s=>s.id===first).deletedAt);w.restoreSession(first);assert.equal(w.useWorkspaceStore.getState().sessions.find(s=>s.id===first).deletedAt,null);w.switchSession(first);assert.equal(editor.getState().doc.nodes[0].name,'A');await w.flushWorkspace();const stored=await storage.readWorkspace();assert.equal(stored.sessions.find(s=>s.id===first).snapshot.messages[0].images.length,1)});
 await test('pinned sessions survive storage and reject changes while generating',async()=>{assert.equal(w.toggleSessionPinned(first),true);await w.flushWorkspace();assert.equal((await storage.readWorkspace()).sessions.find(s=>s.id===first).pinned,true);editor.setState({aiStatus:'generating'});assert.equal(w.toggleSessionPinned(first),false);editor.setState({aiStatus:'idle'});assert.equal(w.useWorkspaceStore.getState().sessions.find(s=>s.id===first).pinned,true)});
 await test('running checkpoint is saved separately from the committed document',async()=>{const base=editor.getState().doc;const ops=[{op:'createPrimitive',name:'preview-only',parentId:null,geometry:{type:'box',params:{width:1,height:1,depth:1}},transform:{position:[2,.5,0],scale:[1,1,1],rotationQuaternion:[0,0,0,1]},materialId:'mat_gray'}];const result=applyBatch(base,{operations:ops});const batch={requestId:'preview-test',projectId:base.projectId,baseRevision:base.revision,selectedIds:[],summary:'未完成阶段草稿',incomplete:true,continuation:'继续原任务',operations:ops};editor.setState({pendingBatch:batch,pendingResult:result,previewDoc:result.doc,aiStatus:'generating'});await w.flushWorkspace();const saved=await storage.readWorkspace();const snap=saved.sessions.find(s=>s.id===first).snapshot;assert.equal(snap.doc.nodes.length,1);assert.equal(snap.pendingResult.doc.nodes.length,2);assert.equal(snap.wasRunning,true);assert.equal(snap.pendingBatch.incomplete,true)});
 await test('pending preview and per-turn execution survive session switching without applying',async()=>{
  editor.setState({aiStatus:'previewing'});const draft=structuredClone(editor.getState().pendingResult.doc);const id=editor.getState().addUserMessage('继续调整');editor.getState().updateMessageRun(id,{status:'preview',startedAt:100,endedAt:200});
  assert.equal(w.createSession(),true);assert.equal(editor.getState().pendingResult,null);assert.equal(w.switchSession(first),true);assert.deepEqual(editor.getState().pendingResult.doc,draft);assert.equal(editor.getState().doc.nodes.length,1);assert.equal(editor.getState().messages.find(m=>m.id===id).run.status,'preview');
  editor.setState(state=>({aiStatus:'generating',messages:[...state.messages,{id:'queued-guide',role:'user',text:'八米高',createdAt:Date.now(),steering:{runId:id,status:'queued'}}]}));editor.getState().updateMessageRun(id,{status:'running'});await w.flushWorkspace();
 });
 await test('stored data can hydrate in a fresh manager without losing references or draft',async()=>{await w.flushWorkspace();const fresh=await server.ssrLoadModule('/src/workspace.ts?reload-test');editor.setState({doc:createInitialDoc(),messages:[],composerText:'',composerImages:[]});await fresh.initializeWorkspace();assert.equal(editor.getState().messages[0].text,'第一台设备');assert.equal(editor.getState().composerText,'继续修改轮子');assert.equal(editor.getState().doc.nodes.length,1);assert.equal(editor.getState().aiStatus,'previewing');assert.equal(editor.getState().previewDoc.nodes.length,2);assert.equal(editor.getState().pendingBatch.incomplete,true);assert.match(editor.getState().messages.at(-1).text,/阶段草稿/);assert.equal(editor.getState().messages.find(m=>m.text==='继续调整').run.status,'stopped');assert.equal(editor.getState().messages.find(m=>m.id==='queued-guide').steering.status,'interrupted');editor.getState().discardPending();await fresh.flushWorkspace()});
 await test('atomic revision guard rejects stale tab writes instead of overwriting newer workspace',async()=>{const current=await storage.readWorkspace();await assert.rejects(()=>storage.writeWorkspace({version:1,activeId:current.activeId,sessions:[]},current.revision-1),/另一个标签页/);assert.equal((await storage.readWorkspace()).sessions.length,current.sessions.length)});
 await test('built-in module registry rejects duplicates and unknown module IDs',async()=>{const {createModuleRegistry}=await server.ssrLoadModule('/src/modules/registry.ts');const registry=createModuleRegistry();const module={id:'modeling',title:'建模',version:1,Viewport:()=>null,Objects:()=>null,Properties:()=>null,documentFormat:'chat3d-project'};registry.register(module);assert.equal(registry.get('modeling'),module);assert.throws(()=>registry.register(module));assert.throws(()=>registry.get('unknown'));assert.equal(registry.list().length,1)});
 console.log(`${count} workspace checks passed using fake IndexedDB`);
}finally{await server.close()}
