import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {indexedDB} from 'fake-indexeddb';
import {createServer} from 'vite';
import React from 'react';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'https://example.test'});
for(const name of ['window','document','HTMLElement','HTMLInputElement','Element','CustomEvent','Node','NodeFilter','MutationObserver','Event','MouseEvent','localStorage','location','DocumentFragment'])Object.defineProperty(globalThis,name,{value:dom.window[name],configurable:true});
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});globalThis.indexedDB=indexedDB;globalThis.getComputedStyle=dom.window.getComputedStyle;globalThis.requestAnimationFrame=fn=>setTimeout(fn,0);globalThis.cancelAnimationFrame=clearTimeout;window.requestAnimationFrame=globalThis.requestAnimationFrame;window.cancelAnimationFrame=globalThis.cancelAnimationFrame;globalThis.ResizeObserver=class{observe(){} unobserve(){} disconnect(){}};
globalThis.CSS={escape:value=>String(value).replace(/[^a-zA-Z0-9_-]/g,char=>'\\'+char)};globalThis.SVGElement=dom.window.SVGElement;globalThis.IS_REACT_ACT_ENVIRONMENT=true;
HTMLElement.prototype.scrollIntoView=()=>{};
const {render,fireEvent,waitFor,cleanup,act}=await import('@testing-library/react');
const {Theme}=await import('@radix-ui/themes');
const server=await createServer({plugins:[{name:'workbench-viewport-fixture',enforce:'pre',load(id){if(id.endsWith('/src/ui/ViewportPanel.tsx'))return "import React from 'react';export function ViewportPanel(){return React.createElement('div',{'data-testid':'viewport-fixture'});}";}}],server:{middlewareMode:true},appType:'custom'});let passed=0;
try{
 const {default:App}=await server.ssrLoadModule('/src/App.tsx');const w=await server.ssrLoadModule('/src/workspace.ts');const {useEditorStore:editor}=await server.ssrLoadModule('/src/store.ts');
 await w.initializeWorkspace();await w.flushWorkspace();
 const ui=render(React.createElement(App));fireEvent.click(ui.getByRole('button',{name:'建模工作台',exact:true}));assert.equal(ui.getByRole('separator',{name:'调整对话区宽度'}).getAttribute('aria-orientation'),'vertical');const input=ui.getByRole('textbox',{name:'建模指令'});fireEvent.change(input,{target:{value:'保留我的输入草稿'}});

 assert.ok(document.querySelector('.editor-workspace > .workbench-project-actions'));assert.ok(ui.getByRole('button',{name:'项目状态'}));assert.equal(document.querySelector('.workbench-project-actions > .canvas-project-title'),null);assert.equal(document.querySelector('.canvas-project-menu'),null);assert.equal(document.querySelector('.app-navigation > .studio-header'),null);assert.equal(document.querySelectorAll('.studio-header').length,1);console.log('PASS project actions remain inside the workbench, outside global navigation');passed++;
 fireEvent.click(ui.getByRole('tab',{name:'任务记录'}));assert.equal(ui.getByRole('tab',{name:'任务记录'}).getAttribute('aria-selected'),'true');assert.ok(ui.getByRole('heading',{name:'任务与执行记录'}));assert.equal(document.querySelector('[aria-label="建模指令"]'),input);assert.equal(input.value,'保留我的输入草稿');
 fireEvent.click(ui.getByRole('button',{name:'前往对话'}));assert.equal(ui.getByRole('textbox',{name:'建模指令'}),input);console.log('PASS switching task and chat panes retains the same mounted composer and draft');passed++;
 fireEvent.keyDown(ui.getByRole('tab',{name:'对话',exact:true}),{key:'ArrowRight'});assert.equal(document.activeElement.id,'task-tab');fireEvent.keyDown(ui.getByRole('tab',{name:'任务记录'}),{key:'Home'});assert.equal(document.activeElement.id,'chat-tab');console.log('PASS assistant tabs support keyboard navigation and selection');passed++;
 fireEvent.click(ui.getByRole('button',{name:'专注场景'}));assert.ok(document.querySelector('.studio.focus-scene'));assert.equal(document.querySelector('[aria-label="建模指令"]'),input);fireEvent.keyDown(window,{key:'Escape'});assert.ok(!document.querySelector('.studio.focus-scene'));assert.equal(input.value,'保留我的输入草稿');console.log('PASS scene focus is reversible and does not unmount live chat');passed++;
 await act(async()=>editor.setState({aiStatus:'generating'}));fireEvent.click(ui.getByRole('tab',{name:'任务记录'}));assert.ok(ui.getByRole('region',{name:'当前任务状态'}).textContent.includes('正在处理'));assert.equal(editor.getState().aiStatus,'generating');fireEvent.click(ui.getByRole('button',{name:'返回对话'}));assert.equal(editor.getState().aiStatus,'generating');console.log('PASS task pane navigation never cancels an active generation');passed++;

 await act(async()=>editor.setState({lastRun:{title:'调整设备',turn:2,toolCalls:3,characters:50,inputTokens:0,outputTokens:0,usageReported:false,lastEventAt:Date.now(),plan:['检查选中设备','修改外壳'],events:['已读取场景'],timings:[]}}));fireEvent.click(ui.getByRole('tab',{name:'任务记录'}));assert.ok(ui.getByText('—'));assert.ok(ui.getByText('计划不等于完成结果，实际状态以执行记录和预览为准'));assert.equal(editor.getState().doc.nodes.length,0);console.log('PASS task record uses actual reported data and does not fabricate cost or completion');passed++;
 await act(async()=>editor.setState({aiStatus:'idle',lastRun:null,messages:[{id:'demo-user',role:'user',text:'创建工作台',createdAt:1,run:{startedAt:1,endedAt:2,status:'completed',mode:'demo'}},{id:'demo-result',role:'assistant',text:'已完成离线演示',createdAt:2}]}));assert.equal(ui.queryByText('尚未开始任务'),null);assert.ok(ui.getByText('历史模拟记录已结束 · 当前无运行任务'));assert.ok(ui.getByRole('button',{name:'模型配置'}));console.log('PASS demo task history has consistent completed state and settings icon has a stable name');passed++;
 await act(async()=>editor.setState({aiStatus:'idle',dirty:true}));await act(async()=>w.flushWorkspace());fireEvent.click(ui.getByRole('button',{name:'项目状态'}));assert.ok(ui.getByRole('dialog',{name:'项目信息'}));assert.ok(ui.getByText('会话已自动保存到本浏览器'));assert.ok(ui.getByText('当前修改尚未导出备份'));assert.equal(ui.queryByText('项目有修改'),null);await act(async()=>editor.getState().markSaved());assert.ok(ui.getByText('项目文件无待导出修改'));fireEvent.keyDown(ui.getByRole('dialog',{name:'项目信息'}),{key:'Escape'});console.log('PASS automatic session save and manual export state remain distinct');passed++;
 await act(async()=>editor.setState({aiStatus:'idle'}));
 fireEvent.click(ui.getByRole('button',{name:'首页',exact:true}));assert.equal(ui.getAllByRole('navigation',{name:'主导航'}).length,1);assert.equal(ui.getAllByRole('button',{name:'切换外观，当前浅色'}).length,1);const homeInput=ui.getByRole('textbox',{name:'新项目描述'});fireEvent.change(homeInput,{target:{value:'从首页带入工作台的草稿'}});fireEvent.click(ui.getByRole('button',{name:'资产库',exact:true}));fireEvent.click(ui.getByRole('button',{name:'首页',exact:true}));assert.equal(ui.getByRole('textbox',{name:'新项目描述'}),homeInput);assert.equal(homeInput.value,'从首页带入工作台的草稿');let launchCalls=0;globalThis.fetch=async()=>{launchCalls++;return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({summary:'已收到需求',operations:[]})}}]}),{headers:{'x-chat3d-proxy':'1'}})};await act(async()=>editor.setState({aiConfig:{baseURL:'https://example.test/v1',apiKey:'mock-only',model:'fixture',useMock:false,agentMode:'single'}}));const before=w.useWorkspaceStore.getState().sessions.length;fireEvent.click(ui.getByRole('button',{name:'开始生成'}));assert.equal(w.useWorkspaceStore.getState().sessions.length,before+1);await waitFor(()=>assert.equal(launchCalls,1));await waitFor(()=>assert.equal(editor.getState().aiStatus,'idle'));assert.equal(editor.getState().messages.find(m=>m.role==='user').text,'从首页带入工作台的草稿');assert.equal(ui.getAllByRole('button',{name:'首页',exact:true}).length,1);assert.equal(ui.getAllByRole('button',{name:'设置',exact:true}).length,1);assert.equal(ui.getAllByRole('button',{name:'切换外观，当前浅色'}).length,1);assert.equal(editor.getState().aiStatus,'idle');console.log('PASS persistent navigation preserves drafts and explicit home submit starts generation once');passed++;
 await act(async()=>editor.setState({aiStatus:'previewing'}));assert.equal(ui.getByRole('button',{name:'首页',exact:true}).disabled,false);assert.equal(ui.getByRole('button',{name:'资产库',exact:true}).disabled,false);assert.equal(ui.getByRole('button',{name:'场景库',exact:true}).disabled,false);assert.equal(ui.getByRole('button',{name:'设置',exact:true}).disabled,false);assert.equal(ui.getByRole('button',{name:'任务',exact:true}).disabled,false);assert.equal(ui.getByRole('button',{name:'建模工作台',exact:true}).disabled,false);console.log('PASS top navigation permits other conversations while preview editing remains protected');passed++;
 const background=w.useWorkspaceStore.getState().activeId;await act(async()=>{editor.setState({aiStatus:'generating'});w.createSession();});await act(async()=>w.flushWorkspace());assert.equal(editor.getState().aiStatus,'idle');assert.equal(w.useWorkspaceStore.getState().saving,false);const warning=new Event('beforeunload',{cancelable:true});window.dispatchEvent(warning);assert.equal(warning.defaultPrevented,true);await act(async()=>w.getSessionEditor(background).setState({aiStatus:'idle'}));await act(async()=>w.flushWorkspace());const clear=new Event('beforeunload',{cancelable:true});window.dispatchEvent(clear);assert.equal(clear.defaultPrevented,false);console.log('PASS closing the page warns about hidden active conversations too');passed++;
 await act(async()=>w.createSession(undefined,{moduleKind:'asset',title:'未命名资产'}));fireEvent.click(ui.getByRole('button',{name:'保存资产',exact:true}));assert.equal(ui.queryByRole('dialog'),null);assert.ok(ui.getByText('还没有可保存的模型。请先创建或导入模型，再保存到资产库。'));assert.equal(ui.getByRole('tab',{name:'对话',exact:true}).getAttribute('aria-selected'),'true');assert.equal(editor.getState().doc.nodes.length,0);console.log('PASS empty asset save gives immediate guidance without opening a metadata form');passed++;
 await act(async()=>editor.setState({aiStatus:'idle'}));await act(async()=>w.flushWorkspace());console.log(`${passed} workbench interaction checks passed with a fixture viewport`);
}finally{cleanup();await server.close();dom.window.close()}
