import {manualAssetCommand} from '../domain/manualComposition';
import {CategoryPicker,useLibraryCategories} from './LibraryMetadataDialog';
import {categoryLabel} from '../domain/libraryCategories';
import {Button} from '@radix-ui/themes';
import {AssetInspection} from './AssetInspection';
import {Dialog} from '@radix-ui/themes';
import {useEffect,useRef,useState} from 'react';
import {useEditorStore} from '../store';
import {MAX_ASSET_BYTES,assetVersionSourceIssue,assetDocument,createModelAsset,parseModelAsset,selectedAssetNodes,type AssetCategory,type ModelAssetVersion,type ModelAssetSummary} from '../domain/modelAssets';
import {listModelAssets,readModelAsset,saveModelAsset,exportAssetLibrary,importAssetLibraryDetailed} from '../domain/modelAssetStorage';
import {captureLibraryThumbnail} from '../scene/libraryThumbnail';
import {makeId} from '../util/ids';
export function AssetLibrary({onClose,intent='manage',targetName}:{onClose:()=>void;intent?:'manage'|'insert';targetName?:string}){
 const doc=useEditorStore(s=>s.doc),selection=useEditorStore(s=>s.selection);
 const [mode,setMode]=useState<'use'|'save'>('use');
 const [versionAsset,setVersionAsset]=useState<ModelAssetVersion|null>(null);
 const [versionTarget,setVersionTarget]=useState(''),[confirmVersion,setConfirmVersion]=useState(false);
 const [items,setItems]=useState<ModelAssetSummary[]>([]),[selected,setSelected]=useState<ModelAssetVersion|null>(null);
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('全部'),[name,setName]=useState(''),[category,setCategory]=useState<AssetCategory>('其他'),[front,setFront]=useState<ModelAssetVersion['front']>('+Z');
 const [position,setPosition]=useState<[number,number,number]>([0,0,0]),[yaw,setYaw]=useState(0),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const {categories,error:categoryError}=useLibraryCategories(items.map(a=>a.category));
 const file=useRef<HTMLInputElement>(null),alive=useRef(true),busyRef=useRef(false),loadSequence=useRef(0);
 const picked=selectedAssetNodes(doc,selection),target=items.find(i=>i.id===versionTarget),sourceLabel=[...new Set(selectedAssetNodes(doc,selection).map(n=>n.assemblyName??n.name))].join('、'),latest=selected?items.find(i=>i.id===selected.id):undefined;
 useEffect(()=>{setConfirmVersion(false);},[doc.revision,selection.join('|'),versionTarget]);
 useEffect(()=>{let active=true;setVersionAsset(null);setConfirmVersion(false);if(target)void readModelAsset(target.id,target.version).then(asset=>{if(active)setVersionAsset(asset);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[target?.id,target?.version]);
 const versionIssue=versionAsset?assetVersionSourceIssue(picked,versionAsset):undefined;
 useEffect(()=>{alive.current=true;void listModelAssets().then(a=>{if(alive.current)setItems(a);}).catch(e=>{if(alive.current)setError(e.message);});return()=>{alive.current=false;loadSequence.current++;};},[]);
 async function run(action:()=>Promise<void>){if(busyRef.current)return;busyRef.current=true;loadSequence.current++;setBusy(true);setError('');setNotice('');try{await action();}catch(e){if(alive.current)setError(e instanceof Error?e.message:'操作失败');}finally{busyRef.current=false;if(alive.current)setBusy(false);}}
 async function choose(id:string,version:number){const seq=++loadSequence.current;setSelected(null);setError('');try{const a=await readModelAsset(id,version);if(alive.current&&seq===loadSequence.current){setSelected(a);}}catch(e){if(alive.current&&seq===loadSequence.current)setError(e instanceof Error?e.message:'读取失败');}}
 async function save(asVersion=false){await run(async()=>{
  const snapshot=structuredClone(useEditorStore.getState().doc),ids=[...useEditorStore.getState().selection];const current=asVersion?target:undefined;if(asVersion&&(!current||!confirmVersion||!versionAsset||versionAsset.id!==current.id||versionAsset.version!==current.version))throw Error('请明确选择目标资产并确认新版本');
  const source=selectedAssetNodes(snapshot,ids);if(asVersion){const issue=assetVersionSourceIssue(source,versionAsset!);if(issue)throw Error(issue);}
  const asset=createModelAsset(snapshot,ids,{name:current?current.name:name,category:current?current.category:category,front:current?versionAsset!.front:front,...(current?{id:current.id,version:current.version+1}:{})});let thumbnailMissing=false,thumbnailNotice='';
  try{const preview=await captureLibraryThumbnail(assetDocument(asset));asset.thumbnail=preview.image;thumbnailNotice=preview.notice;}catch{thumbnailMissing=true;}
  await saveModelAsset(asset,current?.version??0);const rows=await listModelAssets();if(!alive.current)return;setItems(rows);setSelected(asset);setMode('use');setVersionTarget('');setConfirmVersion(false);setNotice(`已保存 ${asset.name} v${asset.version}，未完成质量验收。${asset.externalConnectionsRemoved?`已移除 ${asset.externalConnectionsRemoved} 条库外连接，插入后需重新绑定。`:''}${thumbnailMissing?'缩略图暂不可用，几何数据已保留。':thumbnailNotice}`);
 });}
 function insert(){if(!selected)return;void run(async()=>{const s=useEditorStore.getState();if(['capturing','context','generating','validating','previewing','applying'].includes(s.aiStatus))throw Error('请先结束生成或处理预览');const result=s.applyCommandBatch([manualAssetCommand({...selected,name:latest?.name??selected.name},position,yaw)],`插入资产 ${selected.name} v${selected.version}`);if(!result.ok)throw Error(result.error||'插入失败');if(intent==='insert')onClose();setNotice(`已插入固定版本 v${selected.version}，可以撤销。资产原件不受场景编辑影响；接触、占位与画面仍需检查。`);});}
 async function importFile(f:File){await run(async()=>{if(f.size>50*1024*1024)throw Error('备份文件超过50MB');const text=await f.text();if(JSON.parse(text)?.format==='chat3d-asset-library'){const {count,categoryConflicts}=await importAssetLibraryDetailed(text);setItems(await listModelAssets());setNotice(`已恢复 ${count} 项资产及其版本，未覆盖原件；验收需重新确认。${categoryConflicts.length?` 分类名称存在差异：${categoryConflicts.join("；")}。`:""}`);return;}if(f.size>MAX_ASSET_BYTES)throw Error('资产文件超过20MB');const source=parseModelAsset(text);const asset={...source,id:makeId(),version:1,createdAt:new Date().toISOString()};await saveModelAsset(asset);const rows=await listModelAssets();if(!alive.current)return;setItems(rows);setSelected(asset);setName(asset.name);setCategory(asset.category);setFront(asset.front);setNotice('已导入为独立资产 v1，未覆盖已有资产，也未认证质量。');});}
 function download(){if(!selected)return;const url=URL.createObjectURL(new Blob([JSON.stringify(selected)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`${selected.name.replace(/[\\/:*?"<>|]/g,'_')}-v${selected.version}.chat3d-asset.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('已发起资产文件下载，请确认已保存；该文件不含模型服务密钥或聊天。');}
 const visible=items.filter(i=>(filter==='全部'||i.category===filter)&&`${i.name} ${categoryLabel(categories,i.category)} ${i.purpose??''}`.toLowerCase().includes(query.trim().toLowerCase()));
 const input='w-full rounded border border-white/15 bg-black/30 px-3 py-2 text-sm';
 return <Dialog.Root open onOpenChange={open=>{if(!open&&!busyRef.current)onClose();}}><Dialog.Content style={{maxWidth:1080,maxHeight:'90vh',overflow:'auto'}}><Dialog.Title>{intent==='insert'?'引用资产':'模型资产库'}</Dialog.Title><Dialog.Description>{intent==='insert'?`添加到：${targetName??'当前项目'}。选择固定版本，插入后可撤销。`:'版本、导入与备份。资产保存在当前浏览器，不会自动跨设备同步。'}</Dialog.Description>
  {intent==='manage'&&<div className="flex gap-2 mt-4" aria-label="资产操作"><Button variant="soft" color="gray" size="2" className="asset-button" aria-pressed={mode==='use'} onClick={()=>setMode('use')}>使用资产</Button><Button variant="soft" color="gray" size="2" className="asset-button" aria-pressed={mode==='save'} onClick={()=>{setMode('save');if(!name.trim())setName(sourceLabel.slice(0,80));}}>保存选中模型</Button></div>}
  <div className="asset-library-layout"><section className="space-y-3">
   <div className="flex gap-2"><input aria-label="搜索模型资产" className={input} placeholder="搜索名称、分类或用途" value={query} onChange={e=>setQuery(e.target.value)}/><CategoryPicker label="资产分类筛选" value={filter} onChange={setFilter} categories={[{value:"全部",label:"全部",revision:0},...categories]}/></div>
   <div className="asset-card-grid">{visible.map(a=><Button variant="soft" color="gray" size="2" key={a.id} disabled={busy} className={`asset-card ${selected?.id===a.id?'selected':''}`} onClick={()=>void choose(a.id,a.version)}>{a.thumbnail?<img src={a.thumbnail} alt={`${a.name} 几何缩略图`}/>:<div className="asset-placeholder">暂无缩略图</div>}<strong>{a.name}</strong><span>{categoryLabel(categories,a.category)} · v{a.version} · {a.parts} 个零件</span><small>固定版本 · 可查看验收</small></Button>)}</div>
   {!visible.length&&<p className="text-sm text-gray-400">{items.length?'没有匹配的资产':'资产库为空。先在场景中选择一个组件，再保存为资产。'}</p>}
   {intent==='manage'&&<><Button variant="soft" color="gray" size="2" disabled={busy} className="asset-button" onClick={()=>void run(async()=>{const backup=await exportAssetLibrary();const text=JSON.stringify(backup);if(new TextEncoder().encode(text).length>50*1024*1024)throw Error('备份超过50MB，请逐项下载');const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='模型资产库备份.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('已发起整个资产库版本备份，不含密钥；迁移后需重新验收。');})}>备份整个资产库</Button>
   <Button variant="soft" color="gray" size="2" disabled={busy} onClick={()=>file.current?.click()} className="asset-button">导入资产文件</Button><input ref={file} type="file" accept=".json,.chat3d-asset.json" hidden onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void importFile(f);}}/></>}
  </section><section className="space-y-3 rounded-lg border border-white/10 p-4">
   {mode==='save'&&<><h3>保存选中元素</h3><p className="text-sm text-blue-200">来源模型：{sourceLabel||'尚未选择'} · {picked.length} 个零件</p><p className="text-xs text-gray-400">选中组件中的一个零件会包含整个组件。目前包含 {picked.length} 个零件。原点统一到模型底面中心，单位米，Y向上；外部连接不随资产带入。</p>
   <label className="block">资产名称<input aria-label="资产名称" className={input} maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label>
   <div className="flex gap-2"><label>分类<CategoryPicker label="保存资产分类" value={category} onChange={setCategory} categories={categories}/></label><label>模型正面<select aria-label="资产正面" className={input} value={front} onChange={e=>setFront(e.target.value as ModelAssetVersion['front'])}>{['+Z','-Z','+X','-X'].map(x=><option key={x}>{x}</option>)}</select></label></div>
   <div className="flex flex-wrap gap-2"><Button variant="soft" color="gray" size="2" className="asset-button primary" disabled={busy||!picked.length||!name.trim()} onClick={()=>void save(false)}>保存为新资产</Button></div><details><summary>更新已有资产版本</summary><label className="block mt-2">目标资产<select aria-label="新版本目标资产" className={input} value={versionTarget} onChange={e=>{setVersionTarget(e.target.value);setConfirmVersion(false);}}><option value="">请选择要更新的资产</option>{items.map(item=><option key={item.id} value={item.id}>{item.name} · 当前 v{item.version}</option>)}</select></label>{target&&<><p className="text-sm mt-2">将“{sourceLabel}”保存为“{target.name}”的新版本 v{target.version+1}。旧版本保留，新版本沿用目标资产名称与分类。</p><label className="flex gap-2 mt-2"><input type="checkbox" aria-label="确认新版本目标" disabled={busy||!versionAsset} checked={confirmVersion} onChange={e=>setConfirmVersion(e.target.checked)}/>我已核对来源模型与目标资产</label></>}<Button variant="soft" color="gray" size="2" className="asset-button mt-2" disabled={busy||!picked.length||!name.trim()||!target||!confirmVersion||!versionAsset||!!versionIssue} onClick={()=>void save(true)}>保存为所选资产新版本</Button>{target&&versionIssue&&<p role="alert" className="text-amber-200 text-xs mt-2">选中模型来自另一资产，请保存为新资产。</p>}</details></>}
   {mode==='use'&&!selected&&<p className="text-sm text-gray-300">选择左侧资产，查看模型并插入场景。</p>}
   {mode==='use'&&selected&&<><h3>{latest?.name??selected.name}</h3>{latest?.name!==selected.name&&<p className="text-xs text-gray-400">此版本保存时的名称：{selected.name}</p>}<p className="text-xs text-gray-400">{selected.size.map(n=>n.toFixed(3)).join(' × ')} m · 正面 {selected.front} · 验收记录见下方。缩略图仅作形体预览，不支持材质验收。</p>
    <label>使用版本<select aria-label="插入资产版本" className={input} disabled={busy} value={selected.version} onChange={e=>void choose(selected.id,Number(e.target.value))}>{Array.from({length:latest?.version??selected.version},(_,i)=>i+1).map(v=><option key={v} value={v}>v{v}</option>)}</select></label>
    <div className="flex gap-2"><Button variant="soft" color="gray" size="2" className="asset-button primary" disabled={busy} onClick={insert}>插入场景</Button><Button variant="soft" color="gray" size="2" className="asset-button" disabled={busy} onClick={download}>下载该版本</Button></div>
    <details><summary>放置位置与角度（默认原点，单位米）</summary><div className="flex gap-2">{(['X','Y','Z'] as const).map((axis,i)=><label key={axis}>{axis}<input className={input} aria-label={`资产插入${axis}`} type="number" step="0.1" value={position[i]} onChange={e=>setPosition(p=>p.map((n,k)=>k===i?Number(e.target.value):n) as [number,number,number])}/></label>)}</div>
    <label>旋转角度<input className={input} aria-label="资产插入角度" type="number" value={yaw} onChange={e=>setYaw(Number(e.target.value))}/></label>
    </details><p className="text-xs text-gray-400">新增版本不会自动改变已有场景实例。插入后可独立修改，并使用撤销恢复。</p>
    <AssetInspection key={`${selected.id}:${selected.version}`} asset={selected} busy={busy} run={run} onContract={async contract=>{const rows=await listModelAssets(),head=rows.find(x=>x.id===selected.id);if(!head||head.version!==selected.version)throw Error('请先选择最新版本再保存连接点');const next={...structuredClone(selected),version:head.version+1,createdAt:new Date().toISOString(),contract};await saveModelAsset(next,head.version);setItems(await listModelAssets());setSelected(next);setNotice('用途和连接点已保存为新版本，旧版本与旧验收记录保持不变');}}/>
   </>}
  </section></div>
  {(error||categoryError)&&<p role="alert" className="mt-3 text-red-300">{error||categoryError}</p>}{notice&&<p role="status" className="mt-3 text-blue-200">{notice}</p>}
  <div className="mt-4 flex justify-end"><Button variant="soft" color="gray" size="2" className="asset-button" disabled={busy} onClick={onClose}>{busy?'处理中…':'关闭'}</Button></div>
 </Dialog.Content></Dialog.Root>;
}
