import {inspectAssetPreflight} from '../domain/assetPreflight';
import {useEffect,useState,useMemo} from 'react';
import {DETAIL_CRITERIA} from '../domain/detailAcceptance';
import {ANCHOR_KINDS,type AssetContract,type AssetAnchor} from '../domain/assetContract';
import {assetFingerprint,assetQualityStatus,validateAssetQuality,type AssetQualityRecord,type AssetEvidence} from '../domain/assetQuality';
import {assetDocument,type ModelAssetVersion} from '../domain/modelAssets';
import {readAssetQuality,saveAssetQuality} from '../domain/modelAssetStorage';
import {captureIsolatedSceneEvidence} from '../scene/capture';
const names={operation:'操作位',grip:'抓握点',input:'进料口',output:'出料口',mount:'安装面',support:'支撑面',custom:'自定义'};
export function AssetInspection({asset,busy,run,onContract}:{asset:ModelAssetVersion;busy:boolean;run:(f:()=>Promise<void>)=>Promise<void>;onContract:(c:AssetContract)=>Promise<void>}){
 const [contract,setContract]=useState<AssetContract>(()=>structuredClone(asset.contract??{purpose:'',features:[],anchors:[]}));
 const [checks,setChecks]=useState<AssetQualityRecord['checks']>(DETAIL_CRITERIA.map(c=>({criterion:c.key,status:'unknown',evidence:'尚未检查'})));
 const [views,setViews]=useState<AssetEvidence[]>([]),[status,setStatus]=useState('待验收'),[expandedView,setExpandedView]=useState<AssetEvidence|null>(null);
 useEffect(()=>{let active=true;void readAssetQuality(asset.id,asset.version).then(async r=>{if(r)await validateAssetQuality(asset,r);if(active&&r){setChecks(r.checks);setViews(r.views);setStatus(assetQualityStatus(r));}}).catch(()=>{if(active)setStatus('验收记录读取失败');});return()=>{active=false;};},[asset.id,asset.version]);
 const preflight=useMemo(()=>inspectAssetPreflight(asset),[asset]);
 const field='rounded border border-white/15 bg-black/30 p-2 text-sm';
 const changeAnchor=(id:string,patch:Partial<AssetAnchor>)=>setContract(c=>({...c,anchors:c.anchors.map(a=>a.id===id?{...a,...patch}:a)}));
 return <section className="space-y-3"><details><summary>用途与连接点</summary><p className="text-xs text-gray-400">连接点绑定实际零件，坐标为该零件的局部米制坐标。保存会建立新版本；连接点本身不能证明真实接触。</p>
 <label className="block">用途<input aria-label="资产用途" className={field+' w-full'} maxLength={600} value={contract.purpose} onChange={e=>setContract(c=>({...c,purpose:e.target.value}))}/></label>
 <label className="block">必须具备的结构（每行一项）<textarea aria-label="资产必需结构" className={field+' w-full'} value={contract.features.join('\n')} onChange={e=>setContract(c=>({...c,features:e.target.value.split('\n')}))}/></label>
 {contract.anchors.map(a=><fieldset className="border border-white/15 rounded p-2 space-y-2" key={a.id}><legend>{names[a.kind]}</legend><input aria-label={`连接点名称 ${a.id}`} className={field} value={a.name} onChange={e=>changeAnchor(a.id,{name:e.target.value})}/><select className={field} aria-label={`连接点用途 ${a.id}`} value={a.kind} onChange={e=>changeAnchor(a.id,{kind:e.target.value as AssetAnchor['kind']})}>{ANCHOR_KINDS.map(k=><option key={k} value={k}>{names[k]}</option>)}</select><select className={field+' w-full'} aria-label={`连接点零件 ${a.id}`} value={a.nodeId} onChange={e=>changeAnchor(a.id,{nodeId:e.target.value})}>{asset.nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select>
 <div className="flex gap-1">{(['X','Y','Z'] as const).map((axis,i)=><label key={axis}>{axis}<input type="number" step="0.01" className={field+' w-20'} aria-label={`连接点${axis} ${a.id}`} value={a.point[i]} onChange={e=>changeAnchor(a.id,{point:a.point.map((v,k)=>k===i?Number(e.target.value):v) as AssetAnchor['point']})}/></label>)}<label>朝向<select className={field} aria-label={`连接点朝向 ${a.id}`} value={a.normal.join(',')} onChange={e=>changeAnchor(a.id,{normal:e.target.value.split(',').map(Number) as AssetAnchor['normal']})}>{[['1,0,0','+X'],['-1,0,0','-X'],['0,1,0','+Y'],['0,-1,0','-Y'],['0,0,1','+Z'],['0,0,-1','-Z']].map(([v,label])=><option value={v} key={v}>{label}</option>)}</select></label></div><button disabled={busy} className="asset-button" onClick={()=>setContract(c=>({...c,anchors:c.anchors.filter(x=>x.id!==a.id)}))}>移除此连接点草稿</button></fieldset>)}
 <label className="block"><input type="checkbox" aria-label="声明预留空间" checked={!!contract.clearance} onChange={e=>setContract(c=>({...c,clearance:e.target.checked?{min:[-asset.size[0]/2,0,asset.size[2]/2],max:[asset.size[0]/2,Math.max(asset.size[1],1),asset.size[2]/2+1]}:undefined}))}/>声明操作或维护预留空间</label>
 {contract.clearance&&<div><p className="text-xs text-gray-400">资产坐标中的长方体范围；组合时检查包围盒占用候选，不代表精确碰撞或安全认证。</p>{(['min','max'] as const).map(bound=><div className="flex gap-1" key={bound}>{(['X','Y','Z'] as const).map((axis,i)=><label key={axis}>{bound==='min'?'最小':'最大'}{axis}<input type="number" step="0.1" className={field+' w-20'} aria-label={`预留空间${bound}${axis}`} value={contract.clearance![bound][i]} onChange={e=>setContract(c=>({...c,clearance:{...c.clearance!,[bound]:c.clearance![bound].map((v,k)=>k===i?Number(e.target.value):v)}}))}/></label>)}</div>)}</div>}
 <button className="asset-button" disabled={busy||contract.anchors.length>=64} onClick={()=>setContract(c=>({...c,anchors:[...c.anchors,{id:crypto.randomUUID(),name:'连接点',kind:'operation',nodeId:asset.nodes[0].id,point:[0,0,0],normal:[0,0,1]}]}))}>添加连接点</button>
 <button disabled={busy} className="asset-button" onClick={()=>void run(()=>onContract({...contract,features:contract.features.map(s=>s.trim()).filter(Boolean)}))}>保存用途与连接点为新版本</button>
 </details><details><summary>自动数据检查（不替代视觉验收）</summary><p className="text-xs text-gray-400">{preflight.note}</p>{preflight.geometryWarnings.map((w,i)=><p key={i}>{w}</p>)}{!preflight.geometryWarnings.length&&<p>未发现当前检查规则覆盖的形体警告。</p>}{preflight.anchors.map(a=><p key={a.id}>{a.name}：{a.status==='on_surface'?'贴近表面':a.status==='off_surface'?'未贴近表面':a.status==='unknown'?'未完成距离核对':'空间参考点'}{a.distance!==null?`（${a.distance.toFixed(3)} m）`:''}</p>)}</details><details><summary>单体质量验收 · {status==='user_reviewed'?'人工已复核':status==='needs_work'?'需要修正':status==='pending'?'仍有待验项':status}</summary><p className="text-xs text-gray-400">逐项记录人工结论。图片、依据绑定当前版本；软件图不能验收材质，场景组合后仍须检查关系。</p>
 <button className="asset-button" disabled={busy} onClick={()=>void run(async()=>{const images:AssetEvidence[]=[];for(const view of ['perspective','front','back'] as const){const evidence=await captureIsolatedSceneEvidence(assetDocument(asset),view);images.push({view,image:evidence.image,renderer:evidence.backend});}setViews(images);setChecks(DETAIL_CRITERIA.map(c=>({criterion:c.key,status:'unknown',evidence:'新图片待复核'})));setStatus('待验收');})}>生成三视角检查图</button>
 <div className="flex flex-wrap gap-2">{views.map(v=><button key={v.view} aria-label={`放大${v.view}检查图`} onClick={()=>setExpandedView(v)}><img src={v.image} alt={`${v.view} 资产检查`} className="w-40"/></button>)}</div>{expandedView&&<div role="region" aria-label="放大资产检查图" className="fixed inset-8 z-50 flex flex-col rounded-lg border border-white/20 bg-gray-950 p-4"><div className="flex justify-between"><span>{expandedView.view} · {expandedView.renderer==='software'?'软件几何检查，不支持材质验收':'渲染检查'}</span><button className="asset-button" onClick={()=>setExpandedView(null)}>关闭放大图</button></div><img src={expandedView.image} alt="资产检查原图" className="min-h-0 flex-1 object-contain"/></div>}
 {DETAIL_CRITERIA.map(c=>{const check=checks.find(x=>x.criterion===c.key)!;return <div key={c.key}><label>{c.name}<select className={field} aria-label={`验收${c.key}`} disabled={busy} value={check.status} onChange={e=>setChecks(xs=>xs.map(x=>x.criterion===c.key?{...x,status:e.target.value as typeof x.status}:x))}><option value="unknown">待核对</option><option value="fail">有问题</option><option value="pass">通过</option><option value="not_applicable">不适用</option></select></label><input className={field+' w-full'} aria-label={`依据${c.key}`} maxLength={600} value={check.evidence} onChange={e=>setChecks(xs=>xs.map(x=>x.criterion===c.key?{...x,evidence:e.target.value}:x))}/></div>})}
 <button className="asset-button" disabled={busy} onClick={()=>void run(async()=>{const record:AssetQualityRecord={assetId:asset.id,version:asset.version,createdAt:new Date().toISOString(),fingerprint:await assetFingerprint(asset),reviewer:'user',checks,views};await saveAssetQuality(record);setStatus(assetQualityStatus(record));})}>保存本版本验收记录</button>
 </details></section>;
}
