import {beginAssetPlacement} from './manualComposition';
import {activeConversationStore} from '../conversationStores';
import {useEffect,useRef,useState} from 'react';
import {Button,Input} from '@heroui/react';
import {CubeIcon,Cross1Icon,MagnifyingGlassIcon,ArrowRightIcon} from '@radix-ui/react-icons';
import {listModelAssets,readModelAsset} from '../domain/modelAssetStorage';
import {type ModelAssetSummary} from '../domain/modelAssets';
import {assertLibraryReady} from '../domain/libraryNavigation';
import {useDisplayDoc,useEditorStore} from '../store';
import {assemblyBounds} from '../domain/assemblyEditing';
import {selectionPropertyCommands} from '../domain/selectionProperties';
import {Vector3} from 'three';
import type {Command} from '../domain/commands';
import type {Vec3} from '../domain/types';
export function CanvasAssetShelf({onClose,onLibrary}:{onClose:()=>void;onLibrary:()=>void}){
 const [items,setItems]=useState<ModelAssetSummary[]>([]),[query,setQuery]=useState(''),[selected,setSelected]=useState<ModelAssetSummary|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[inserting,setInserting]=useState(false);
 const alive=useRef(true),busy=useRef(false);const locked=useEditorStore(s=>['capturing','context','generating','validating','previewing','applying'].includes(s.aiStatus));
 useEffect(()=>{alive.current=true;listModelAssets().then(v=>{if(alive.current)setItems(v)}).catch(e=>{if(alive.current)setError(String(e.message??e))}).finally(()=>{if(alive.current)setLoading(false)});return()=>{alive.current=false}},[]);
 async function insert(){if(!selected||busy.current)return;busy.current=true;setInserting(true);setError('');try{assertLibraryReady();const origin=activeConversationStore();const {projectId,revision}=origin.getState().doc;const asset=await readModelAsset(selected.id,selected.version);if(!alive.current)return;assertLibraryReady();if(activeConversationStore()!==origin)throw Error('会话已切换，请重新确认插入');const state=origin.getState();if(state.doc.projectId!==projectId||state.doc.revision!==revision)throw Error('场景已变化，请重新确认插入');beginAssetPlacement(asset);onClose();}catch(e){if(alive.current)setError(e instanceof Error?e.message:'引用失败')}finally{busy.current=false;if(alive.current)setInserting(false)}}
 return <section className="canvas-asset-shelf canvas-surface" aria-label="画布资产架"><header><MagnifyingGlassIcon/><Input aria-label="搜索画布资产" placeholder="搜索资产…" value={query} onChange={e=>setQuery(e.target.value)}/><Button isIconOnly variant="ghost" aria-label="收起资产架" onPress={onClose}><Cross1Icon/></Button></header><div className="canvas-asset-items">{items.filter(i=>`${i.name} ${i.category}`.toLowerCase().includes(query.toLowerCase())).map(i=><Button variant="ghost" key={i.id} aria-label={`选择资产 ${i.name}`} aria-pressed={selected?.id===i.id} onPress={()=>setSelected(i)} className="canvas-asset-item">{i.thumbnail?<img src={i.thumbnail} alt={`${i.name} 几何缩略图`}/>:<CubeIcon/>}<span>{i.name}</span><small>v{i.version}</small></Button>)}</div>{loading&&<p>正在读取资产…</p>}{!loading&&!items.length&&<p>资产库为空，先创建并保存一个模型。</p>}{error&&<p role="alert">{error}</p>}<footer><Button variant="ghost" onPress={onLibrary}>打开资产库<ArrowRightIcon/></Button>{selected&&<Button isDisabled={locked||inserting} onPress={()=>void insert()}>{inserting?'正在读取…':`放置 v${selected.version}`}</Button>}</footer></section>;
}
export type CanvasPropertyTab='position'|'rotation'|'size';
export function CanvasInspector({onClose,onAdvanced,tab,setTab}:{onClose:()=>void;onAdvanced:()=>void;tab:CanvasPropertyTab;setTab:(tab:CanvasPropertyTab)=>void}){
 const doc=useDisplayDoc(),ids=useEditorStore(s=>s.selection),status=useEditorStore(s=>s.aiStatus);const selectedIds=new Set(ids),nodes=doc.nodes.filter(n=>selectedIds.has(n.id)&&n.geometry);const [values,setValues]=useState(['0','0','0']),[scale,setScale]=useState('1'),[notice,setNotice]=useState('');const key=ids.join('|');
 useEffect(()=>{setValues(['0','0','0']);setScale('1');setNotice('')},[key,tab,doc.projectId]);
 if(!nodes.length)return null;
 const bounds=assemblyBounds(nodes),size=bounds.getSize(new Vector3()),title=nodes.length===1?nodes[0].name:nodes.every(n=>n.assemblyId&&n.assemblyId===nodes[0].assemblyId)?nodes[0].assemblyName??'选中组件':`${nodes.length} 个零件`;
 const locked=['capturing','context','generating','validating','previewing','applying'].includes(status);
 function apply(operations:Command[],label:string){const r=useEditorStore.getState().applyCommandBatch(operations,label);setNotice(r.ok?'已修改，可撤销':r.error??'修改失败');return r.ok}
 function transform(){try{if(tab==='size'){if(!scale.trim())throw Error('请输入缩放倍数');if(apply(selectionPropertyCommands(doc,ids,{kind:'size',value:Number(scale)}),'等比缩放选中对象'))setScale('1');}else{if(values.some(v=>!v.trim()||!Number.isFinite(Number(v))))throw Error('请输入有效数值');const v=values.map(Number) as Vec3;if(apply(selectionPropertyCommands(doc,ids,{kind:tab,value:v}),tab==='position'?'移动选中对象':'旋转选中对象'))setValues(['0','0','0']);}}catch(e){setNotice(e instanceof Error?e.message:'修改失败')}}
 function recolor(color:string){try{apply(selectionPropertyCommands(doc,ids,{kind:'color',value:color}),'修改选中对象颜色')}catch(e){setNotice(e instanceof Error?e.message:'修改失败')}}
 return <section className="canvas-inspector canvas-surface" aria-label="选中对象属性"><header><CubeIcon/><strong title={title}>{title}</strong><Button isIconOnly variant="ghost" aria-label="关闭属性面板" onPress={onClose}><Cross1Icon/></Button></header><p className="canvas-dimensions">尺寸 <strong>{[size.x,size.y,size.z].map(v=>(v*1000).toFixed(0)).join(' × ')} mm</strong></p><fieldset disabled={locked}><div className="canvas-swatches" aria-label="选中对象颜色">{['#2468B4','#A5ABB4','#41474F','#328566','#D5444C','#EBC45B'].map(color=><Button key={color} isIconOnly aria-label={`设为颜色 ${color}`} style={{background:color}} onPress={()=>recolor(color)}/>)}</div><div className="canvas-property-tabs" role="group" aria-label="属性类型">{([['position','位置'],['rotation','旋转'],['size','尺寸']] as const).map(([key,label])=><Button key={key} variant={tab===key?'primary':'ghost'} aria-pressed={tab===key} onPress={()=>setTab(key)}>{label}</Button>)}</div><p className="canvas-field-hint">{tab==='position'?'相对移动 · 米':tab==='rotation'?'围绕选区底部中心旋转 · 度':'等比缩放，保持零件比例'}</p>{tab==='size'?<label>倍数<Input aria-label="画布缩放倍数" type="number" min="0.001" max="1000" step="0.1" value={scale} onChange={e=>setScale(e.target.value)}/></label>:['X','Y','Z'].map((axis,i)=><label key={axis}>{axis}<Input aria-label={`画布${tab==='position'?'位移':'旋转'} ${axis}`} type="number" step={tab==='position'?'.1':'15'} value={values[i]} onChange={e=>setValues(v=>v.map((x,j)=>i===j?e.target.value:x))}/></label>)}<Button className="canvas-apply-transform" onPress={transform}>应用更改</Button></fieldset>{locked&&<p>请先结束生成或确认预览后再编辑。</p>}{notice&&<p role="status">{notice}</p>}<Button variant="ghost" className="canvas-advanced" onPress={onAdvanced}>更多属性与材质<ArrowRightIcon/></Button></section>;
}
export function CanvasSelectionSummary({onEdit}:{onEdit:()=>void}){const doc=useDisplayDoc(),ids=useEditorStore(s=>s.selection),selectedIds=new Set(ids),nodes=doc.nodes.filter(n=>selectedIds.has(n.id)&&n.geometry);if(!nodes.length)return null;const size=assemblyBounds(nodes).getSize(new Vector3());const name=nodes.length===1?nodes[0].name:nodes.every(n=>n.assemblyId===nodes[0].assemblyId)?nodes[0].assemblyName??'选中对象':`${nodes.length} 个零件`;return <div className="canvas-selection-summary canvas-surface"><span title={name}>{name}</span><small>{[size.x,size.y,size.z].map(v=>(v*1000).toFixed(0)).join(' × ')} mm</small><Button variant="ghost" onPress={onEdit}>编辑</Button></div>}
