import {useEffect,useRef,useState} from 'react';
import {Button,Dialog,DropdownMenu,TextArea,TextField} from '@radix-ui/themes';
import {ChevronDownIcon,PlusIcon} from '@radix-ui/react-icons';
import {categoryPath,orderedCategories,defaultLibraryCategories,listLibraryCategories,saveLibraryCategory,type LibraryCategory,type LibraryKind} from '../domain/libraryCategories';
import {normalizeLibraryMetadata,type LibraryMetadata} from '../domain/libraryMetadata';
import {listModelAssets} from '../domain/modelAssetStorage';
import {saveLibraryProject} from '../domain/workspaceLibrary';
import {useWorkspaceStore} from '../workspace';
import {useEditorStore} from '../store';
import {captureLibraryThumbnail} from '../scene/libraryThumbnail';
import './library-metadata.css';
export function useLibraryCategories(encountered:string[]=[],kind:LibraryKind='asset'){
 const [categories,setCategories]=useState<LibraryCategory[]>(()=>defaultLibraryCategories(kind)),[error,setError]=useState(''),[ready,setReady]=useState(false);const key=encountered.join('\u0000');
 useEffect(()=>{let alive=true,sequence=0;const refresh=()=>{const run=++sequence;void listLibraryCategories(encountered,kind).then(rows=>{if(alive&&run===sequence){setCategories(rows);setError('');setReady(true);}}).catch(e=>{if(alive&&run===sequence){setError(e.message);setReady(false);}});};refresh();window.addEventListener('chat3d:categories',refresh);window.addEventListener('focus',refresh);return()=>{alive=false;window.removeEventListener('chat3d:categories',refresh);window.removeEventListener('focus',refresh);};},[key,kind]);
 return {categories,error,ready};
}
export function CategoryPicker({value,onChange,categories,label='分类',optional=false,disabled=false,className}:{value:string;onChange:(value:string)=>void;categories:LibraryCategory[];label?:string;optional?:boolean;disabled?:boolean;className?:string}){
 return <DropdownMenu.Root><DropdownMenu.Trigger><Button type="button" variant="soft" color="gray" className={className} disabled={disabled} aria-label={label}>{optional&&!value?'未分类':categoryPath(categories,value)}<ChevronDownIcon/></Button></DropdownMenu.Trigger><DropdownMenu.Content color="gray" style={{maxHeight:300,overflowY:'auto'}}><DropdownMenu.RadioGroup value={value} onValueChange={onChange}>{optional&&<DropdownMenu.RadioItem value="">未分类</DropdownMenu.RadioItem>}{orderedCategories(categories).map(c=><DropdownMenu.RadioItem key={c.value} value={c.value}>{categoryPath(categories,c.value)}</DropdownMenu.RadioItem>)}</DropdownMenu.RadioGroup></DropdownMenu.Content></DropdownMenu.Root>;
}
export function CategoryManager({onClose,encountered=[],kind='asset',onCreated}:{onClose:()=>void;encountered?:string[];kind?:LibraryKind;onCreated?:(category:LibraryCategory)=>void}){
 const {categories,error:loadError,ready}=useLibraryCategories(encountered,kind),[parent,setParent]=useState(''),[editing,setEditing]=useState<LibraryCategory>(),[label,setLabel]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false);
 async function submit(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const saved=await saveLibraryCategory(label,editing,{kind,parentValue:parent});if(!editing)onCreated?.(saved);setEditing(undefined);setLabel('');setParent('');}catch(e){setError(e instanceof Error?e.message:'分类保存失败');}finally{lock.current=false;setBusy(false);}}
 return <Dialog.Root open onOpenChange={open=>{if(!open&&!lock.current)onClose();}}><Dialog.Content maxWidth="480px" className="library-metadata-dialog"><Dialog.Title>管理分类</Dialog.Title><Dialog.Description>分类保存在当前浏览器。重命名只更新显示名称，已有资产版本与场景引用保持不变。</Dialog.Description><div className="library-category-list">{categories.map(c=><div key={c.value}><span>{categoryPath(categories,c.value)}</span><Button variant="ghost" color="gray" type="button" disabled={busy||!ready} aria-label={`重命名分类 ${c.label}`} onClick={()=>{setEditing(c);setParent(c.parentValue??'');setLabel(c.label);setError('');}}>重命名</Button></div>)}</div><form onSubmit={e=>{e.preventDefault();void submit();}}><label>上级分类<select aria-label="上级分类" disabled={busy||!ready||!!editing} value={parent} onChange={e=>setParent(e.target.value)}><option value="">一级分类</option>{categories.filter(c=>!c.parentValue).map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</select></label><label>{editing?'新分类名称':'添加分类'}<TextField.Root aria-label="分类名称" value={label} maxLength={80} disabled={busy||!ready} onChange={e=>setLabel(e.target.value)}/></label><div className="library-dialog-actions">{editing&&<Button type="button" variant="soft" color="gray" disabled={busy} onClick={()=>{setEditing(undefined);setLabel('');setParent('');}}>取消重命名</Button>}<Button type="submit" disabled={busy||!ready||!label.trim()}>{editing?'保存分类名称':<><PlusIcon/>添加分类</>}</Button></div></form>{(error||loadError)&&<p role="alert" className="resource-error">{error||loadError}</p>}<div className="library-dialog-actions"><Button type="button" variant="soft" color="gray" disabled={busy} onClick={onClose}>完成</Button></div></Dialog.Content></Dialog.Root>;
}
export function LibraryMetadataDialog({kind,initial,title,submitLabel,onSubmit,onClose,onBusyChange}:{kind:'asset'|'scene';initial:LibraryMetadata;title:string;submitLabel:string;onSubmit:(metadata:LibraryMetadata)=>Promise<void>;onClose:()=>void;onBusyChange?:(busy:boolean)=>void}){
 const [name,setName]=useState(initial.name),[category,setCategory]=useState(initial.category??(kind==='asset'?'其他':'')),[description,setDescription]=useState(initial.description??''),[manage,setManage]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false),alive=useRef(true);
 const {categories,error:categoryError,ready}=useLibraryCategories(category?[category]:[],kind);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 async function submit(){if(lock.current)return;setError('');let metadata:LibraryMetadata;try{metadata=normalizeLibraryMetadata({name,category,description},kind);}catch(e){setError((e as Error).message);return;}lock.current=true;setBusy(true);onBusyChange?.(true);try{await onSubmit(metadata);if(alive.current)onClose();}catch(e){if(alive.current)setError(e instanceof Error?e.message:'保存失败');}finally{lock.current=false;onBusyChange?.(false);if(alive.current)setBusy(false);}}
 return <><Dialog.Root open onOpenChange={open=>{if(!open&&!lock.current)onClose();}}><Dialog.Content maxWidth="480px" className="library-metadata-dialog"><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{kind==='asset'?'整理资产名称、分类和说明。模型尺寸、版本与质量状态由实际数据保留。':'整理场景名称与说明，分类可选。场景中的资产引用保持固定版本。'}</Dialog.Description><form onSubmit={e=>{e.preventDefault();void submit();}}><label>{kind==='asset'?'资产名称':'场景名称'}<TextField.Root autoFocus aria-label={kind==='asset'?'资产名称':'场景名称'} value={name} maxLength={80} disabled={busy} onChange={e=>setName(e.target.value)} placeholder={kind==='asset'?'例如：蓝色网格托盘':'例如：原料仓库'}/></label><div className="library-category-field"><label>{kind==='scene'?'分类（可选）':'分类'}<CategoryPicker label={kind==='asset'?'资产分类':'场景分类'} value={category} onChange={setCategory} categories={categories} optional={kind==='scene'} disabled={busy||!ready}/></label><Button type="button" variant="ghost" color="gray" disabled={busy||!ready} onClick={()=>setManage(true)}>管理分类</Button></div><label>说明（可选）<TextArea aria-label="库内容说明" value={description} maxLength={1000} rows={3} disabled={busy} onChange={e=>setDescription(e.target.value)} placeholder={kind==='asset'?'用途、来源或需要注意的事项':'场景用途或备注'}/></label>{(error||categoryError)&&<p role="alert" className="resource-error">{error||categoryError}</p>}<div className="library-dialog-actions"><Button type="button" variant="soft" color="gray" disabled={busy} onClick={onClose}>取消</Button><Button type="submit" disabled={busy||!ready}>{busy?'正在保存…':submitLabel}</Button></div></form></Dialog.Content></Dialog.Root>{manage&&<CategoryManager kind={kind} onCreated={c=>{setCategory(c.value);setManage(false);}} encountered={category?[category]:[]} onClose={()=>setManage(false)}/>}</>;
}
export function LibraryProjectSaveDialog({onClose,onSaved,onBusyChange}:{onClose:()=>void;onSaved:(notice:string)=>void;onBusyChange:(busy:boolean)=>void}){
 const [target]=useState(()=>{const w=useWorkspaceStore.getState();return {session:w.sessions.find(s=>s.id===w.activeId),projectId:useEditorStore.getState().doc.projectId};});
 const [initial,setInitial]=useState<LibraryMetadata>(),[revision,setRevision]=useState(0),[error,setError]=useState('');const session=target.session;
 useEffect(()=>{let alive=true;void (async()=>{if(!session)throw Error('找不到当前项目');const head=session.assetSource?(await listModelAssets()).find(a=>a.id===session.assetSource!.id):undefined;if(session.assetSource&&!head)throw Error('找不到资产记录，草稿已保留');if(alive){setInitial(head?{name:head.name,category:head.category,description:head.description}:{name:/^未命名(资产|场景)$/.test(session.title)?'':session.title,category:session.moduleKind==='asset'?session.assetCategory:session.sceneCategory,description:session.libraryDescription});setRevision(head?.metadataRevision??session.libraryMetadataRevision??0);}})().catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[session]);
 if(!initial||!session)return <Dialog.Root open onOpenChange={open=>{if(!open)onClose();}}><Dialog.Content maxWidth="480px"><Dialog.Title>保存到库</Dialog.Title><Dialog.Description>{error||'正在读取项目信息…'}</Dialog.Description><Button variant="soft" color="gray" onClick={onClose}>取消</Button></Dialog.Content></Dialog.Root>;
 return <LibraryMetadataDialog kind={session.moduleKind??'scene'} initial={initial} title={session.moduleKind==='asset'?'保存资产到库':'保存场景到库'} submitLabel="保存到库" onBusyChange={onBusyChange} onClose={onClose} onSubmit={async metadata=>{let imageNotice='';const notice=await saveLibraryProject(async d=>{const result=await captureLibraryThumbnail(d);imageNotice=result.notice;return result.image;},{metadata,sessionId:session.id,projectId:target.projectId,metadataRevision:revision});onSaved(notice+(imageNotice?` ${imageNotice}`:''));}}/>;
}
