import {EyeOpenIcon,EyeNoneIcon,ChevronDownIcon,ChevronRightIcon} from '@radix-ui/react-icons';
import {useMemo,useState} from 'react';
import { useDisplayDoc, useEditorStore } from '../store';
import type {SceneNode} from '../domain/types';
export function ObjectTree(){
 const doc=useDisplayDoc(),selection=useEditorStore(s=>s.selection),select=useEditorStore(s=>s.select),apply=useEditorStore(s=>s.applyCommandBatch);
 const [expanded,setExpanded]=useState<Set<string>>(new Set()),[query,setQuery]=useState('');
 const groups=useMemo(()=>{const map=new Map<string,SceneNode[]>();for(const n of doc.nodes){const key=n.assemblyId??n.id;if(!map.has(key))map.set(key,[]);map.get(key)!.push(n);}return [...map.entries()].map(([id,nodes])=>({id,nodes,title:nodes[0].assemblyName??(nodes[0].assemblyId?nodes[0].name.split(' · ')[0]:nodes[0].name),zone:nodes[0].zone})).sort((a,b)=>a.title.localeCompare(b.title,'zh'));},[doc]);
 const shown=groups.filter(g=>(g.title+' '+g.zone+' '+g.nodes.map(n=>n.name).join(' ')).toLowerCase().includes(query.toLowerCase()));
 const row=(n:SceneNode)=><div key={n.id} className={`flex items-center gap-2 px-3 py-1.5 text-xs ${selection.includes(n.id)?'bg-blue-600/30':'hover:bg-white/5'}`}><button className="flex-1 truncate text-left" onClick={()=>select([n.id])}>{n.name}</button><button aria-label={`${n.visible?'隐藏':'显示'} ${n.name}`} onClick={()=>{const r=apply([{op:'setVisibility',targetId:n.id,visible:!n.visible}],'切换零件可见性');if(!r.ok)window.alert(r.error);}}>{n.visible?<EyeOpenIcon/>:<EyeNoneIcon/>}</button></div>;
 return <div className="flex flex-col h-full bg-[#252A31] text-gray-200"><div className="px-3 py-2 text-xs font-bold text-gray-400">场景组件 · {groups.length} 组 / {doc.nodes.length} 零件</div><input aria-label="搜索场景组件" value={query} onChange={e=>setQuery(e.target.value)} placeholder="查找设备、区域或零件" className="mx-2 mb-2 rounded border border-white/10 bg-black/20 p-2 text-xs"/><div className="flex-1 overflow-auto">{!shown.length&&<p className="p-4 text-xs text-gray-500">{doc.nodes.length?'没有匹配的组件':'空场景，可从对话或沙盘预览开始'}</p>}{shown.map(g=>g.nodes.length===1?row(g.nodes[0]):<div key={g.id} className="border-b border-white/5"><div className={`flex items-center p-2 gap-2 ${g.nodes.every(n=>selection.includes(n.id))?'bg-blue-600/25':''}`}><button aria-label={`${expanded.has(g.id)?'收起':'展开'} ${g.title}`} onClick={()=>setExpanded(old=>{const s=new Set(old);if(s.has(g.id))s.delete(g.id);else s.add(g.id);return s;})}>{expanded.has(g.id)?<ChevronDownIcon/>:<ChevronRightIcon/>}</button><button aria-label={`选择组件 ${g.title}`} className="min-w-0 flex-1 text-left text-xs" onClick={()=>select(g.nodes.map(n=>n.id))}><span className="block truncate">{g.title}</span>{g.zone&&<span className="text-[10px] text-gray-500">{g.zone}</span>}</button><span className="text-[10px] text-gray-500">{g.nodes.length}</span></div>{expanded.has(g.id)&&<div className="pl-3">{g.nodes.map(row)}</div>}</div>)}</div></div>;
}
