import {Button,Card,TextField,Badge} from '@radix-ui/themes';
import {useEffect,useRef,useState} from 'react';
import {CubeIcon,LayersIcon,PlusIcon,MagnifyingGlassIcon,ArrowRightIcon} from '@radix-ui/react-icons';
import {createSession,switchSession,useWorkspaceStore,type WorkspaceSession} from '../workspace';
import {ASSET_CATEGORIES,type AssetCategory,type ModelAssetSummary} from '../domain/modelAssets';
import {listModelAssets} from '../domain/modelAssetStorage';
import {assertLibraryReady,createSceneFromAsset,openLibraryAsset,projectIsDraft,projectLabel} from '../domain/libraryNavigation';
export function ProjectThumb({src,name,kind='scene'}:{src?:string;name:string;kind?:'asset'|'scene'}){return src?<img src={src} alt={`${name} 几何缩略图`}/>:<div className="resource-no-thumb">{kind==='asset'?<CubeIcon/>:<LayersIcon/>}<span>尚无预览图</span></div>;}
export function ProjectCreateForm({kind,onOpen,onCancel,fromAsset}:{kind:'asset'|'scene';onOpen:()=>void;onCancel:()=>void;fromAsset?:ModelAssetSummary}){
 const [name,setName]=useState(''),[category,setCategory]=useState<AssetCategory>('其他'),[error,setError]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false);
 return <form className="resource-create-form" aria-label={kind==='asset'?'新建资产表单':'新建场景表单'} onSubmit={async e=>{e.preventDefault();if(lock.current)return;if(!name.trim()){setError('请先输入名称');return;}lock.current=true;setBusy(true);try{assertLibraryReady();if(fromAsset)await createSceneFromAsset(fromAsset,name);else if(!createSession(undefined,{moduleKind:kind,title:name.trim().slice(0,80),...(kind==='asset'?{assetCategory:category}:{})}))throw Error('暂时无法新建');onOpen();}catch(e){setError(e instanceof Error?e.message:'新建失败');}finally{lock.current=false;setBusy(false);}}}>
 <h2>{fromAsset?'使用资产创建场景':kind==='asset'?'新建资产':'新建场景'}</h2>{fromAsset&&<p>引用 {fromAsset.name} · v{fromAsset.version}，保留资产原件。</p>}
 <label>{kind==='asset'?'资产名称':'场景名称'}<TextField.Root size="3" autoFocus aria-label={kind==='asset'?'新资产名称':'新场景名称'} value={name} maxLength={80} onChange={e=>setName(e.target.value)} placeholder={kind==='asset'?'例如：蓝色网格托盘':'例如：原料仓库'}/></label>
 {kind==='asset'&&<label>分类<select aria-label="新资产分类" value={category} onChange={e=>setCategory(e.target.value as AssetCategory)}>{ASSET_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label>}
 {error&&<p role="alert">{error}</p>}<div className="resource-form-actions"><Button variant="soft" color="gray" type="button" disabled={busy} onClick={onCancel}>取消</Button><Button variant="solid" color="blue" className="primary" disabled={busy} type="submit">{busy?'正在创建…':kind==='asset'?'创建资产':'创建场景'}</Button></div></form>;
}
export function ProjectLibrary({kind,onOpen,onManage}:{kind:'asset'|'scene';onOpen:()=>void;onManage:()=>void}){
 const sessions=useWorkspaceStore(s=>s.sessions),[items,setItems]=useState<ModelAssetSummary[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState('全部'),[view,setView]=useState<'saved'|'draft'>('saved'),[selected,setSelected]=useState(''),[create,setCreate]=useState(false),[useAsset,setUseAsset]=useState<ModelAssetSummary>(),[error,setError]=useState(''),[loading,setLoading]=useState(true),[opening,setOpening]=useState(false);const lock=useRef(false);
 useEffect(()=>{let alive=true;listModelAssets().then(rows=>{if(alive)setItems(rows);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[]);
 const matches=(title:string)=>title.toLowerCase().includes(query.trim().toLowerCase());
 const allProjects=sessions.filter(s=>!s.deletedAt&&(s.moduleKind??'scene')===kind).sort((a,b)=>b.updatedAt-a.updatedAt);
 const drafts=allProjects.filter(s=>kind==='asset'?(!s.assetSource||!s.librarySavedAt||s.savedRevision!==s.snapshot.doc.revision||s.snapshot.pendingBatch):projectIsDraft(s));
 const projects=(view==='draft'?drafts:allProjects.filter(s=>!projectIsDraft(s))).filter(s=>matches(s.title));
 const assets=items.filter(a=>matches(a.name)&&(filter==='全部'||a.category===filter));const selectedAsset=assets.find(a=>a.id===selected),selectedProject=projects.find(s=>s.id===selected);
 async function editAsset(a:ModelAssetSummary){if(lock.current)return;lock.current=true;setOpening(true);setError('');try{await openLibraryAsset(a);onOpen();}catch(e){setError(e instanceof Error?e.message:'打开失败');}finally{lock.current=false;setOpening(false);}}
 function openProject(s:WorkspaceSession){if(switchSession(s.id))onOpen();else setError('当前无法切换，请先处理执行任务或存储异常');}
 return <main className="resource-page" aria-label={kind==='asset'?'资产库模块':'场景库模块'}>
 <header className="resource-heading"><div><span className="resource-eyebrow">{kind==='asset'?'可复用的模型':'你的空间与布局'}</span><h1>{kind==='asset'?'资产库':'场景库'}</h1><p>{kind==='asset'?'管理可重复使用的模型，选择资产查看详情。':'管理完整场景，草稿与已保存内容分别查看。'}</p></div><Button variant="solid" color="blue" className="primary" onClick={()=>{setCreate(!create);setUseAsset(undefined);}}><PlusIcon/>{kind==='asset'?'新建资产':'新建场景'}</Button></header>
 {(create||useAsset)&&<ProjectCreateForm key={useAsset?.id??kind} kind={useAsset?'scene':kind} fromAsset={useAsset} onOpen={onOpen} onCancel={()=>{setCreate(false);setUseAsset(undefined);}}/>}
 <div className="resource-toolbar"><div className="resource-segments" aria-label="资源状态"><Button variant="soft" color="gray" aria-pressed={view==='saved'} onClick={()=>{setView('saved');setSelected('');}}>已保存{kind==='asset'?'资产':'场景'} <span>{kind==='asset'?items.length:allProjects.filter(s=>!projectIsDraft(s)).length}</span></Button><Button variant="soft" color="gray" aria-pressed={view==='draft'} onClick={()=>{setView('draft');setSelected('');}}>草稿 <span>{drafts.length}</span></Button></div><div className="resource-search"><TextField.Root size="3" aria-label="搜索库内容" placeholder={kind==='asset'?'搜索资产名称':'搜索场景名称'} value={query} onChange={e=>{setQuery(e.target.value);setSelected('');}}><TextField.Slot><MagnifyingGlassIcon/></TextField.Slot></TextField.Root></div>{kind==='asset'&&view==='saved'&&<select aria-label="资产分类筛选" value={filter} onChange={e=>{setFilter(e.target.value);setSelected('');}}><option>全部</option>{ASSET_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select>}</div>
 {error&&<p role="alert" className="resource-error">{error}</p>}
 <div className={`resource-browser ${selectedAsset||selectedProject?'has-detail':''}`}><section className="resource-results" aria-label="资源列表">
 {kind==='asset'&&view==='saved'?(loading?<p>正在读取资产…</p>:<div className="resource-grid">{assets.map(a=><Card asChild key={a.id}><button className="resource-tile" aria-pressed={selected===a.id} aria-label={`查看资产 ${a.name}`} key={a.id} onClick={()=>setSelected(a.id)}><ProjectThumb src={a.thumbnail} name={a.name} kind="asset"/><strong>{a.name}</strong><span>{a.category} · v{a.version} · {a.parts} 个零件</span></button></Card>)}</div>):<div className="resource-project-list">{projects.map(s=><Button variant="soft" color="gray" className="resource-row" aria-pressed={selected===s.id} aria-label={`查看${kind==='asset'?'草稿':'场景'} ${s.title}`} key={s.id} onClick={()=>setSelected(s.id)}><ProjectThumb src={s.sceneThumbnail??items.find(a=>a.id===s.assetSource?.id)?.thumbnail} name={s.title} kind={kind}/><span><strong>{s.title}</strong><small>{s.snapshot.doc.nodes.length} 个零件 · {projectLabel(s)}</small><small>{new Date(s.updatedAt).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}</small></span><ArrowRightIcon/></Button>)}</div>}
 {!loading&&(kind==='asset'&&view==='saved'?assets.length===0:projects.length===0)&&<div className="resource-empty"><CubeIcon/><h2>{query?'没有匹配内容':view==='draft'?'暂无草稿':kind==='asset'?'还没有保存的资产':'还没有保存的场景'}</h2><p>{query?'换一个关键词或分类试试。':view==='draft'?'未保存的编辑会出现在这里。':'新建后在工作台保存，即可在这里找到。'}</p>{query&&<Button variant="soft" color="gray" onClick={()=>{setQuery('');setFilter('全部');}}>清除筛选</Button>}</div>}
 </section>
 {selectedAsset&&<Card asChild><aside className="resource-detail" aria-label="资产详情"><div className="resource-detail-title"><h2>{selectedAsset.name}</h2><Button variant="soft" color="gray" aria-label="关闭详情" onClick={()=>setSelected('')}>关闭</Button></div><ProjectThumb src={selectedAsset.thumbnail} name={selectedAsset.name} kind="asset"/><dl><dt>分类</dt><dd>{selectedAsset.category}</dd><dt>版本</dt><dd>v{selectedAsset.version}</dd><dt>尺寸（X / Y / Z）</dt><dd>{selectedAsset.size.map(x=>x.toFixed(3)).join(' × ')} m</dd><dt>零件</dt><dd>{selectedAsset.parts}</dd><dt>质量</dt><dd><Badge color="amber" variant="soft">待验收</Badge></dd></dl><p className="resource-muted">场景引用固定版本，编辑实例不会改变资产原件。</p><div className="resource-detail-actions"><Button variant="soft" color="gray" disabled={opening} onClick={()=>void editAsset(selectedAsset)}>编辑资产</Button><Button variant="solid" color="blue" className="primary" disabled={opening} onClick={()=>{setUseAsset(selectedAsset);setCreate(false);}}>用于新场景</Button></div><Button variant="soft" color="gray" className="resource-secondary" onClick={onManage}>版本记录与资产备份</Button></aside></Card>}
 {selectedProject&&<Card asChild><aside className="resource-detail" aria-label="项目详情"><div className="resource-detail-title"><h2>{selectedProject.title}</h2><Button variant="soft" color="gray" aria-label="关闭详情" onClick={()=>setSelected('')}>关闭</Button></div><ProjectThumb src={selectedProject.sceneThumbnail??items.find(a=>a.id===selectedProject.assetSource?.id)?.thumbnail} name={selectedProject.title} kind={kind}/><dl><dt>状态</dt><dd>{projectLabel(selectedProject)}</dd><dt>零件</dt><dd>{selectedProject.snapshot.doc.nodes.length}</dd><dt>类型</dt><dd>{kind==='asset'?'资产编辑':'场景'}</dd></dl>{kind==='scene'&&<><h3>引用资产</h3>{Array.from(new Map(selectedProject.snapshot.doc.nodes.filter(n=>n.modelAsset).map(n=>[n.modelAsset!.instanceId,n.modelAsset!])).values()).map(a=><p className="resource-reference" key={a.instanceId}>{items.find(i=>i.id===a.id)?.name??'资产实例'} · v{a.version}</p>)}{!selectedProject.snapshot.doc.nodes.some(n=>n.modelAsset)&&<p className="resource-muted">尚未引用资产</p>}</>}<Button variant="solid" color="blue" className="primary" onClick={()=>openProject(selectedProject)}>{kind==='asset'?'继续编辑草稿':'打开场景'}</Button></aside></Card>}
 </div><footer className="resource-footer"><span>当前浏览器保存 · 请定期导出备份</span>{kind==='asset'&&<Button variant="soft" color="gray" onClick={onManage}>导入与备份</Button>}</footer>
 </main>;
}
