import {LibraryCategoryTree} from './LibraryCategoryTree';
import {captureLibraryThumbnail} from '../scene/libraryThumbnail';
import {assetDocument} from '../domain/modelAssets';
import {Button,Card,TextField,Badge} from '@radix-ui/themes';
import {useEffect,useRef,useState} from 'react';
import {CubeIcon,LayersIcon,PlusIcon,MagnifyingGlassIcon,ArrowRightIcon,GridIcon,RowsIcon,Cross1Icon} from '@radix-ui/react-icons';
import {createSession,switchSession,useWorkspaceStore,editLibrarySessionMetadata,syncAssetCatalogMetadata,type WorkspaceSession} from '../workspace';
import type {ModelAssetSummary} from '../domain/modelAssets';
import {CategoryManager,CategoryPicker,LibraryMetadataDialog,useLibraryCategories} from './LibraryMetadataDialog';
import {categoryLabel,categoryMatches,categoryPath} from '../domain/libraryCategories';
import {listModelAssets,moveModelAssetsToCategory,updateModelAssetMetadata,readModelAsset,updateAssetThumbnail} from '../domain/modelAssetStorage';
import {assertLibraryReady,openLibraryAsset,projectIsDraft,projectLabel} from '../domain/libraryNavigation';
export function ProjectThumb({src,name,kind='scene'}:{src?:string;name:string;kind?:'asset'|'scene'}){return src?<img src={src} alt={`${name} 几何缩略图`}/>:<div className="resource-no-thumb">{kind==='asset'?<CubeIcon/>:<LayersIcon/>}<span>尚无预览图</span></div>;}
export function ProjectLibrary({kind,onOpen,onManage}:{kind:'asset'|'scene';onOpen:()=>void;onManage:()=>void}){
 const sessions=useWorkspaceStore(s=>s.sessions),[items,setItems]=useState<ModelAssetSummary[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState('全部'),[view,setView]=useState<'saved'|'draft'>('saved'),[selected,setSelected]=useState(''),[manageCategories,setManageCategories]=useState(false),[editingAsset,setEditingAsset]=useState<ModelAssetSummary>(),[editingProject,setEditingProject]=useState<WorkspaceSession>(),[notice,setNotice]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[opening,setOpening]=useState(false),[layout,setLayout]=useState<'grid'|'list'>('grid');const lock=useRef(false),alive=useRef(true);const [bulk,setBulk]=useState(false),[checked,setChecked]=useState<string[]>([]),[moveTarget,setMoveTarget]=useState('');
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const {categories,error:categoryError}=useLibraryCategories(sessions.filter(s=>(s.moduleKind??'scene')===kind).map(s=>kind==='asset'?s.assetCategory:s.sceneCategory).filter((c):c is string=>!!c),kind);
 async function editAssetInfo(item:ModelAssetSummary){if(lock.current)return;lock.current=true;setOpening(true);setError('');try{assertLibraryReady();const rows=await listModelAssets();const head=rows.find(a=>a.id===item.id);if(!head)throw Error('找不到资产记录');if(alive.current){setItems(rows);setEditingAsset(head);}}catch(e){setError(e instanceof Error?e.message:'读取失败');}finally{lock.current=false;setOpening(false);}}
 async function createProject(){if(lock.current)return;lock.current=true;setOpening(true);setError('');try{assertLibraryReady();if(!createSession(undefined,{moduleKind:kind,title:kind==='asset'?'未命名资产':'未命名场景',...(filter!=='全部'&&filter!=='未分类'?(kind==='asset'?{assetCategory:filter}:{sceneCategory:filter}):{})}))throw Error('暂时无法新建');onOpen();}catch(e){setError(e instanceof Error?e.message:'新建失败');lock.current=false;setOpening(false);}}
 useEffect(()=>{let alive=true;listModelAssets().then(rows=>{if(alive)setItems(rows);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[]);
 const matches=(title:string)=>title.toLowerCase().includes(query.trim().toLowerCase());
 const allProjects=sessions.filter(s=>!s.deletedAt&&(s.moduleKind??'scene')===kind).sort((a,b)=>b.updatedAt-a.updatedAt);
 const drafts=allProjects.filter(s=>kind==='asset'?(!s.assetSource||!s.librarySavedAt||s.savedRevision!==s.snapshot.doc.revision||s.snapshot.pendingBatch):projectIsDraft(s));
 const projects=(view==='draft'?drafts:allProjects.filter(s=>!projectIsDraft(s))).filter(s=>matches(s.title+' '+(s.libraryDescription??'')+' '+categoryPath(categories,kind==='asset'?s.assetCategory:s.sceneCategory))&&(query.trim()||categoryMatches(categories,kind==='asset'?s.assetCategory:s.sceneCategory,filter)));
 const assets=items.filter(a=>matches(a.name+' '+(a.description??'')+' '+(a.purpose??'')+' '+categoryPath(categories,a.category))&&(query.trim()||categoryMatches(categories,a.category,filter)));const selectedAsset=assets.find(a=>a.id===selected),selectedProject=projects.find(s=>s.id===selected);
 const firstVisibleId=kind==='asset'&&view==='saved'?assets[0]?.id:projects[0]?.id;
 useEffect(()=>{if(!loading&&!selected&&firstVisibleId)setSelected(firstVisibleId);},[loading,kind,view,query,filter,firstVisibleId]);
 async function editAsset(a:ModelAssetSummary){if(lock.current)return;lock.current=true;setOpening(true);setError('');try{await openLibraryAsset(a,()=>alive.current);onOpen();}catch(e){setError(e instanceof Error?e.message:'打开失败');}finally{lock.current=false;setOpening(false);}}
 async function refreshThumbnail(item:ModelAssetSummary){if(lock.current)return;lock.current=true;setOpening(true);setError('');setNotice('');try{assertLibraryReady();const version=await readModelAsset(item.id,item.version);const result=await captureLibraryThumbnail(assetDocument(version));if(!alive.current)return;const updated=await updateAssetThumbnail(item.id,item.version,result.image);if(alive.current){setItems(rows=>rows.map(a=>a.id===item.id?updated:a));setNotice(result.notice+' 模型版本未改变。');}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'更新预览失败');}finally{lock.current=false;if(alive.current)setOpening(false);}}
 async function moveAssets(){if(lock.current)return;lock.current=true;setOpening(true);setError('');try{assertLibraryReady();const chosen=checked.map(id=>items.find(a=>a.id===id));if(chosen.some(a=>!a))throw Error('选中资产已变化，请重新选择');const changed=await moveModelAssetsToCategory(chosen as ModelAssetSummary[],moveTarget);setItems(rows=>rows.map(a=>changed.find(c=>c.id===a.id)??a));setChecked([]);for(const item of changed)await syncAssetCatalogMetadata(item);setNotice('已移动 '+changed.length+' 项资产，模型版本和场景引用未改变');}catch(e){setError((e as Error).message);}finally{lock.current=false;if(alive.current)setOpening(false);}}
 function openProject(s:WorkspaceSession){if(switchSession(s.id))onOpen();else setError('当前无法切换，请先处理存储异常');}
 return <main className={`resource-page resource-page-${kind}`} aria-label={kind==='asset'?'资产库模块':'场景库模块'}>
 <header className="resource-heading"><div><h1>{kind==='asset'?'资产库':'场景库'}</h1><p>{kind==='asset'?'管理和复用可编辑的 3D 资产':'创建和管理包含多个资产的 3D 场景'}</p></div><div className="resource-heading-actions"><div className="resource-search"><TextField.Root size="3" aria-label="搜索库内容" placeholder="跨分类搜索名称、说明" value={query} onChange={e=>{setQuery(e.target.value);setSelected('');}}><TextField.Slot><MagnifyingGlassIcon/></TextField.Slot></TextField.Root></div><Button variant="solid" color="gray" className="primary" disabled={opening} onClick={()=>void createProject()}><PlusIcon/>{kind==='asset'?'新建资产':'新建场景'}</Button><div className="resource-view-switch" role="group" aria-label="资源显示方式"><Button variant="ghost" color="gray" aria-label="网格视图" aria-pressed={layout==='grid'} onClick={()=>setLayout('grid')}><GridIcon/></Button><Button variant="ghost" color="gray" aria-label="列表视图" aria-pressed={layout==='list'} onClick={()=>setLayout('list')}><RowsIcon/></Button></div></div></header>

 <div className="resource-toolbar"><div className="resource-segments" aria-label="资源状态"><Button variant="soft" color="gray" aria-pressed={view==='saved'} onClick={()=>{setView('saved');setSelected('');}}>已保存{kind==='asset'?'资产':'场景'} <span>{kind==='asset'?items.length:allProjects.filter(s=>!projectIsDraft(s)).length}</span></Button><Button variant="soft" color="gray" aria-pressed={view==='draft'} onClick={()=>{setView('draft');setSelected('');}}>草稿 <span>{drafts.length}</span></Button></div><Button variant="ghost" color="gray" onClick={()=>setManageCategories(true)}>管理分类</Button>{kind==='asset'&&view==='saved'&&<Button variant="soft" color="gray" aria-pressed={bulk} onClick={()=>{setBulk(!bulk);setChecked([]);}}>{bulk?'退出多选':'批量整理'}</Button>}</div>
 {(error||categoryError)&&<p role="alert" className="resource-error">{error||categoryError}</p>}
 <div className="library-organizer"><LibraryCategoryTree categories={categories} values={kind==='asset'&&view==='saved'?items.map(a=>a.category):(view==='draft'?drafts:allProjects.filter(s=>!projectIsDraft(s))).map(s=>kind==='asset'?s.assetCategory:s.sceneCategory)} value={query.trim()?'全部':filter} onChange={v=>{setFilter(v);setQuery('');setSelected('');setChecked([]);}} onManage={()=>setManageCategories(true)}/><div>
 {query.trim()&&<p className="resource-muted">正在跨分类搜索名称、说明和分类</p>}
 {bulk&&kind==='asset'&&view==='saved'&&<div className="library-bulk-actions"><span>已选 {checked.length} 项</span><Button variant="soft" color="gray" disabled={opening} onClick={()=>setChecked(assets.map(a=>a.id))}>全选结果</Button><Button variant="ghost" color="gray" onClick={()=>setChecked([])}>清空选择</Button><CategoryPicker label="移动到分类" value={moveTarget} onChange={setMoveTarget} categories={categories} optional disabled={opening}/><Button disabled={opening||!checked.length||!moveTarget} onClick={()=>void moveAssets()}>移动分类</Button></div>}
 <div className="resource-results-heading"><span>{view==='draft'?'编辑中的项目':kind==='asset'?'可复用资产':'已保存场景'}</span><span>{kind==='asset'&&view==='saved'?assets.length:projects.length} 项结果</span></div>
 <div className={`resource-browser ${selectedAsset||selectedProject?'has-detail':''} resource-layout-${layout}`}><section className="resource-results" aria-label="资源列表">
 {kind==='asset'&&view==='saved'?(loading?<p>正在读取资产…</p>:<div className="resource-grid">{assets.map(a=><div className="resource-selectable" key={a.id}>{bulk&&<input className="resource-bulk-check" type="checkbox" aria-label={`选择资产 ${a.name}`} disabled={opening} checked={checked.includes(a.id)} onChange={e=>setChecked(ids=>e.target.checked?[...ids,a.id]:ids.filter(id=>id!==a.id))}/>}<Card asChild><button className="resource-tile" aria-pressed={selected===a.id} aria-label={`查看资产 ${a.name}`} key={a.id} onClick={()=>setSelected(a.id)}><ProjectThumb src={a.thumbnail} name={a.name} kind="asset"/><strong>{a.name}</strong>{(a.description||a.purpose)&&<span className="resource-tile-description">{a.description||a.purpose}</span>}<span className="resource-tile-dimensions">{a.size.map(v=>Number(v.toFixed(2))).join(' × ')} m</span><span className="resource-tile-meta"><Badge color="gray" variant="soft">{categoryLabel(categories,a.category)}</Badge><span>v{a.version} · {a.parts} 个零件</span></span></button></Card></div>)}</div>):<div className={`resource-project-list ${layout==='grid'?'resource-project-grid':''}`}>{projects.map(s=><Button variant="soft" color="gray" className="resource-row" aria-pressed={selected===s.id} aria-label={`查看${kind==='asset'?'草稿':'场景'} ${s.title}`} key={s.id} onClick={()=>setSelected(s.id)}><ProjectThumb src={s.sceneThumbnail??items.find(a=>a.id===s.assetSource?.id)?.thumbnail} name={s.title} kind={kind}/><span><strong>{s.title}</strong><small><Badge color="gray" variant="soft">{kind==='asset'?'资产':'场景'}</Badge>{s.snapshot.doc.nodes.length} 个零件 · {projectLabel(s)}</small><small>{new Date(s.updatedAt).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}</small></span><ArrowRightIcon/></Button>)}</div>}
 {!loading&&(kind==='asset'&&view==='saved'?assets.length===0:projects.length===0)&&<div className="resource-empty"><CubeIcon/><h2>{query?'没有匹配内容':view==='draft'?'暂无草稿':kind==='asset'?'还没有保存的资产':'还没有保存的场景'}</h2><p>{query?'换一个关键词或分类试试。':view==='draft'?'未保存的编辑会出现在这里。':'新建后在工作台保存，即可在这里找到。'}</p>{query&&<Button variant="soft" color="gray" onClick={()=>{setQuery('');setFilter('全部');}}>清除筛选</Button>}</div>}
 </section>
 {selectedAsset&&<Card asChild><aside className="resource-detail" aria-label="资产详情"><div className="resource-detail-title"><h2>{selectedAsset.name}</h2><Button variant="soft" color="gray" aria-label="关闭详情" onClick={()=>setSelected('')}><Cross1Icon/></Button></div><ProjectThumb src={selectedAsset.thumbnail} name={selectedAsset.name} kind="asset"/><dl><dt>分类</dt><dd>{categoryLabel(categories,selectedAsset.category)}</dd><dt>版本</dt><dd>v{selectedAsset.version}</dd><dt>尺寸（X / Y / Z）</dt><dd>{selectedAsset.size.map(x=>x.toFixed(3)).join(' × ')} m</dd><dt>零件</dt><dd>{selectedAsset.parts}</dd><dt>质量</dt><dd><Badge color="amber" variant="soft">待验收</Badge></dd></dl>{selectedAsset.description&&<p className="resource-detail-description">{selectedAsset.description}</p>}<p className="resource-muted">场景引用固定版本，编辑实例不会改变资产原件。</p><div className="resource-detail-actions" role="group" aria-label="资产操作"><Button variant="solid" color="blue" className="primary" disabled={opening} onClick={()=>void editAsset(selectedAsset)}>编辑资产</Button><Button variant="soft" color="gray" disabled={opening} onClick={()=>void editAssetInfo(selectedAsset)}>编辑信息</Button><Button variant="soft" color="gray" disabled={opening} onClick={()=>void refreshThumbnail(selectedAsset)}>{opening?'正在处理…':'更新预览图'}</Button><Button variant="soft" color="gray" disabled={opening} aria-label="版本记录与资产备份" onClick={onManage}>版本与备份</Button></div>{notice&&<p role="status" className="resource-muted">{notice}</p>}<p className="resource-muted resource-preview-help">更新预览图不增加模型版本。场景预览图在重新保存场景时更新。</p></aside></Card>}
 {selectedProject&&<Card asChild><aside className="resource-detail" aria-label="项目详情"><div className="resource-detail-title"><h2>{selectedProject.title}</h2><Button variant="soft" color="gray" aria-label="关闭详情" onClick={()=>setSelected('')}><Cross1Icon/></Button></div><ProjectThumb src={selectedProject.sceneThumbnail??items.find(a=>a.id===selectedProject.assetSource?.id)?.thumbnail} name={selectedProject.title} kind={kind}/><dl><dt>状态</dt><dd>{projectLabel(selectedProject)}</dd><dt>零件</dt><dd>{selectedProject.snapshot.doc.nodes.length}</dd><dt>类型</dt><dd>{kind==='asset'?'资产编辑':'场景'}</dd><dt>分类</dt><dd>{categoryLabel(categories,kind==='asset'?selectedProject.assetCategory:selectedProject.sceneCategory)}</dd></dl>{selectedProject.libraryDescription&&<p className="resource-detail-description">{selectedProject.libraryDescription}</p>}{kind==='scene'&&<><h3>引用资产</h3>{Array.from(new Map(selectedProject.snapshot.doc.nodes.filter(n=>n.modelAsset).map(n=>[n.modelAsset!.instanceId,n.modelAsset!])).values()).map(a=><p className="resource-reference" key={a.instanceId}>{items.find(i=>i.id===a.id)?.name??'资产实例'} · v{a.version}</p>)}{!selectedProject.snapshot.doc.nodes.some(n=>n.modelAsset)&&<p className="resource-muted">尚未引用资产</p>}</>}<Button variant="soft" color="gray" onClick={()=>setEditingProject(selectedProject)}>编辑信息</Button><Button variant="solid" color="blue" className="primary" onClick={()=>openProject(selectedProject)}>{kind==='asset'?'继续编辑草稿':'打开场景'}</Button></aside></Card>}

 </div></div></div><footer className="resource-footer"><span>当前浏览器保存 · 请定期导出备份</span>{kind==='asset'&&<Button variant="soft" color="gray" onClick={onManage}>导入与备份</Button>}</footer>
 {manageCategories&&<CategoryManager kind={kind} encountered={categories.map(c=>c.value)} onClose={()=>setManageCategories(false)}/>}
 {editingAsset&&<LibraryMetadataDialog kind="asset" initial={{name:editingAsset.name,category:editingAsset.category,description:editingAsset.description}} title="编辑资产信息" submitLabel="保存信息" onClose={()=>setEditingAsset(undefined)} onSubmit={async metadata=>{assertLibraryReady();const updated=await updateModelAssetMetadata(editingAsset.id,metadata,editingAsset);await syncAssetCatalogMetadata(updated);if(alive.current)setItems(rows=>rows.map(a=>a.id===updated.id?updated:a));}}/>}
 {editingProject&&<LibraryMetadataDialog kind={kind} initial={{name:editingProject.title,category:kind==='asset'?editingProject.assetCategory:editingProject.sceneCategory,description:editingProject.libraryDescription}} title={kind==='asset'?'编辑草稿信息':'编辑场景信息'} submitLabel="保存信息" onClose={()=>setEditingProject(undefined)} onSubmit={metadata=>editLibrarySessionMetadata(editingProject.id,metadata,editingProject.libraryMetadataRevision??0)}/>}
 </main>;
}
