import {useState} from 'react';
import {AlertDialog,Button,Dialog,DropdownMenu,IconButton,TextField} from '@radix-ui/themes';
import {PlusIcon,MagnifyingGlassIcon,DotsHorizontalIcon,Pencil1Icon,TrashIcon,ResetIcon,CubeIcon,Cross1Icon,DrawingPinIcon,DrawingPinFilledIcon} from '@radix-ui/react-icons';
import {useWorkspaceStore,createSession,switchSession,renameSession,trashSession,restoreSession,toggleSessionPinned,type WorkspaceSession} from '../workspace';
import {useEditorStore} from '../store';
import {sessionState,sessionStateLabel,sessionDateGroup} from './sessionPresentation';
export function SessionSidebar({locked,onClose}:{locked:boolean;onClose:()=>void}){
 const {sessions,activeId,error,ready}=useWorkspaceStore();
 const liveStatus=useEditorStore(s=>s.aiStatus);
 const [filter,setFilter]=useState<'all'|'review'|'draft'>('all');
 const [query,setQuery]=useState('');const [trash,setTrash]=useState(false);const [rename,setRename]=useState<WorkspaceSession|null>(null);const [name,setName]=useState('');const [remove,setRemove]=useState<WorkspaceSession|null>(null);
 const state=(s:WorkspaceSession)=>sessionState(s,s.id===activeId?liveStatus:undefined);
 const shown=sessions.filter(s=>!!s.deletedAt===trash&&s.title.toLowerCase().includes(query.toLowerCase())&&(trash||filter==='all'||state(s)===filter)).sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned)||b.updatedAt-a.updatedAt);
 return <>
 <div className="session-brand"><div className="brand-mark"><CubeIcon width="23" height="23"/></div><div><strong>chat3d</strong><span>建模工作台</span></div><IconButton className="sidebar-close" variant="ghost" color="gray" onClick={onClose} aria-label="收起会话列表"><Cross1Icon/></IconButton></div>
 <div className="session-controls"><Button size="3" style={{width:'100%'}} disabled={locked||!!error||!ready} onClick={()=>{if(createSession()){setTrash(false);setFilter('all');onClose();}}}><PlusIcon/>新建会话</Button><TextField.Root value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索会话" aria-label="搜索会话"><TextField.Slot><MagnifyingGlassIcon/></TextField.Slot></TextField.Root></div>
 {!trash&&<div className="session-filters" aria-label="会话筛选">{([['all','全部'],['review','待确认'],['draft','草稿']] as const).map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</div>}
 <div className="session-section"><span>{trash?'回收站':'工作会话'}</span><span>{shown.length}</span></div>
 <nav aria-label="会话列表" className="session-list">{!shown.length&&<div className="sidebar-empty">{query?'没有匹配的会话':trash?'回收站为空':filter==='all'?'还没有会话':filter==='review'?'没有待确认的会话':'没有未发送的草稿'}</div>}{shown.map((s,i)=><div key={s.id} className="session-entry">{(i===0||(!!s.pinned!==!!shown[i-1].pinned)||(!s.pinned&&sessionDateGroup(s.updatedAt)!==sessionDateGroup(shown[i-1].updatedAt)))&&<div className="session-date">{s.pinned&&!trash?'置顶':sessionDateGroup(s.updatedAt)}</div>}<div className={`session-item ${s.id===activeId&&!trash?'is-active':''}`}>
 <button className="session-open" disabled={locked||trash||!!error} aria-current={s.id===activeId?'page':undefined} onClick={()=>{if(switchSession(s.id))onClose();}}><span className={`session-state-dot ${state(s)}`} aria-label={sessionStateLabel[state(s)]}/><span><strong>{s.title}</strong><small>{sessionStateLabel[state(s)]} · {s.snapshot.doc.nodes.length} 个对象{s.pinned&&<DrawingPinFilledIcon/>}</small></span></button>
 {trash?<IconButton size="1" color="gray" variant="ghost" disabled={!!error} aria-label={`恢复 ${s.title}`} onClick={()=>restoreSession(s.id)}><ResetIcon/></IconButton>:<DropdownMenu.Root><DropdownMenu.Trigger><IconButton size="1" variant="ghost" color="gray" aria-label={`${s.title} 的菜单`} disabled={locked||!!error}><DotsHorizontalIcon/></IconButton></DropdownMenu.Trigger><DropdownMenu.Content><DropdownMenu.Item onSelect={()=>toggleSessionPinned(s.id)}><DrawingPinIcon/>{s.pinned?'取消置顶':'置顶会话'}</DropdownMenu.Item><DropdownMenu.Item onSelect={()=>{setRename(s);setName(s.title);}}><Pencil1Icon/>重命名</DropdownMenu.Item><DropdownMenu.Separator/><DropdownMenu.Item color="red" onSelect={()=>setRemove(s)}><TrashIcon/>移至回收站</DropdownMenu.Item></DropdownMenu.Content></DropdownMenu.Root>}</div></div>)}</nav>
 <div className="session-footer"><Button variant="ghost" color="gray" onClick={()=>setTrash(!trash)}><TrashIcon/>{trash?'返回会话':'回收站'}</Button><p>聊天、图片和项目保存在本浏览器<br/>不会自动同步到其他设备</p>{locked&&<p className="session-lock">结束生成或处理预览后可切换会话</p>}</div>
 <Dialog.Root open={!!rename} onOpenChange={open=>{if(!open)setRename(null);}}><Dialog.Content maxWidth="400px"><Dialog.Title>重命名会话</Dialog.Title><Dialog.Description size="2" mb="4">为项目起一个方便查找的名称</Dialog.Description><form onSubmit={e=>{e.preventDefault();if(rename&&renameSession(rename.id,name))setRename(null);}}><TextField.Root autoFocus value={name} maxLength={80} onChange={e=>setName(e.target.value)} aria-label="会话名称"/><div className="dialog-actions"><Dialog.Close><Button type="button" variant="soft" color="gray">取消</Button></Dialog.Close><Button type="submit" disabled={!name.trim()}>保存名称</Button></div></form></Dialog.Content></Dialog.Root>
 <AlertDialog.Root open={!!remove} onOpenChange={open=>{if(!open)setRemove(null);}}><AlertDialog.Content maxWidth="420px"><AlertDialog.Title>移至回收站？</AlertDialog.Title><AlertDialog.Description size="2">“{remove?.title}”的聊天、参考图与场景将一起移入回收站，之后可以恢复。</AlertDialog.Description><div className="dialog-actions"><AlertDialog.Cancel><Button variant="soft" color="gray">取消</Button></AlertDialog.Cancel><Button color="red" disabled={locked} onClick={()=>{if(remove&&trashSession(remove.id))setRemove(null);}}>移至回收站</Button></div></AlertDialog.Content></AlertDialog.Root>
 </>;
}
