import {DETAIL_CRITERIA} from '../domain/detailAcceptance';
import {runDiagnostics} from '../domain/runDiagnostics';
import {RunTrace} from './RunTrace';
import {useEffect,useState} from 'react';
import {useEditorStore} from '../store';
import {CheckCircledIcon,ClockIcon,ActivityLogIcon,CrossCircledIcon} from '@radix-ui/react-icons';
export function TaskPanel({onConversation}:{onConversation:()=>void}){
 const {lastRun,aiStatus,pendingBatch,pendingResult,doc,messages}=useEditorStore();
 const busy=['capturing','context','generating','validating','applying'].includes(aiStatus);
 const [now,setNow]=useState(Date.now());
 useEffect(()=>{if(!busy)return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[busy]);
 const exportDiagnostics=()=>{const state=useEditorStore.getState();const url=URL.createObjectURL(new Blob([JSON.stringify(runDiagnostics(state.aiStatus,state.lastRun,state.aiError),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chat3d-diagnostics.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const runs=messages.filter(m=>m.run).slice().reverse();
 const latestRun=runs[0]?.run;
 const latestReply=[...messages].reverse().find(m=>m.role==='assistant');
 const hasHistory=!!lastRun||!!latestRun||messages.some(m=>m.batch);
 const modeTitle=latestRun?.mode==='demo'?'历史模拟记录':latestRun?.mode==='single'?'单次生成':'本轮任务';
 const idleTitle=latestRun?.status==='failed'?'最近任务未完成':latestRun?.status==='stopped'?'最近任务已停止':hasHistory?`${modeTitle}已结束 · 当前无运行任务`:'用一句话开始建模';
 const outcomes=messages.filter(m=>m.batch).slice().reverse();
 return <section className="task-panel" aria-label="任务记录">
 <div className="task-panel-intro"><ActivityLogIcon/><h2>任务与执行记录</h2><p>查看当前进展、执行用量和场景修改结果</p></div>
 <div className={`task-current ${busy?'is-running':''}`}><div className="task-eyebrow"><span className="status-dot"/>{busy?'正在执行':pendingBatch?'等待你的确认':aiStatus==='error'?'执行遇到问题':aiStatus==='cancelled'?'已停止':hasHistory?'当前无运行任务':'尚未开始任务'}</div><h3>{busy?lastRun?.title??'正在处理请求':pendingBatch?'预览已保留，等待你的决定':idleTitle}</h3><p>{pendingBatch?'场景仍是预览，确认应用后才会写入项目':busy?'可回到对话查看进展或停止生成':latestReply?.outcome==='applied'?'本次修改已应用。后续撤销或再次编辑，以当前场景为准。':latestReply?.outcome==='discarded'?'本次预览已放弃，未写入场景。':hasHistory?(latestReply?.text.split('\n')[0].slice(0,160)??'可展开下方记录查看结果'):'每次修改先预览，再由你决定是否应用'}</p><button onClick={onConversation}>{pendingBatch?'返回对话确认预览':busy?'返回对话 / 停止生成':'前往对话'}</button></div>
 {lastRun&&<><div className="task-metrics"><div><strong>{lastRun.turn}</strong><span>{lastRun.parallelRuns?.length?'主代理轮次':'模型轮次'}</span></div><div><strong>{lastRun.toolCalls}</strong><span>{lastRun.parallelRuns?.length?'主代理工具调用':'工具调用'}</span></div><div><strong>{lastRun.usageReported?(lastRun.usageIncomplete?'≥ ':'')+(lastRun.inputTokens+lastRun.outputTokens).toLocaleString():'—'}</strong><span>{lastRun.parallelRuns?.length?'总 Token（含子代理）':'Token 用量'}</span></div></div>
 {!!lastRun.parallelRuns?.length&&<details className="task-section" open={busy?true:undefined}><summary>并行子代理 · {lastRun.parallelRuns.length} 项</summary><div className="task-events">{lastRun.parallelRuns.map(r=><p key={r.id}>{r.name} · {{queued:'排队',running:'生成中',ready:'数据已生成，尚未合并',done:'数据已合并，待统一验收',failed:'失败，未合并',cancelled:'已取消'}[r.status]} · {r.rounds} 轮 · {r.toolCalls} 次工具 · {r.usageReported?(r.inputTokens+r.outputTokens).toLocaleString()+' Token':'用量未报告'}{r.startedAt?' · '+((Math.max(r.endedAt??(busy?now:lastRun.lastEventAt),r.startedAt)-r.startedAt)/1000).toFixed(1)+' 秒':''}{r.error?' · '+r.error:''}</p>)}<p>总用量包含主代理和子代理。{lastRun.usageIncomplete?'存在未完整报告的请求，显示值仅为已知下限。':''}子草稿仍需统一质量验收。</p></div></details>}
 {lastRun.timings.some(t=>t.requestFootprint)&&<details className="task-section"><summary>请求开销分析</summary><p>以下为发送内容的字符数，不是 Token 或账单；Token 以服务报告为准。</p>{lastRun.timings.filter(t=>t.requestFootprint).map(t=>{const f=t.requestFootprint!;return <p key={t.id}>{t.label}：系统 {f.systemChars.toLocaleString()} · 工具定义 {f.toolSchemaChars.toLocaleString()} · 用户文本 {f.userTextChars.toLocaleString()} · 模型历史 {f.assistantChars.toLocaleString()} · 工具结果 {f.toolResultChars.toLocaleString()} · 图片 {f.imageCount} 张 · {t.inputTokens===undefined?'用量未报告':`输入 ${t.inputTokens.toLocaleString()} / 输出 ${(t.outputTokens??0).toLocaleString()} Token`}</p>})}</details>}
 {!!lastRun.plan.length&&<div className="task-section"><h3>执行计划</h3><ol>{lastRun.plan.map((step,i)=><li key={i}><span>{i+1}</span>{step}</li>)}</ol><p className="task-footnote">计划不等于完成结果，实际状态以执行记录和预览为准</p></div>}
 {lastRun.design&&<details className="task-section"><summary>设计方案 · {lastRun.design.equipment.length} 类设备</summary><div className="task-events"><p>工艺：{lastRun.design.flow.join(' → ')}</p><p>布局：{lastRun.design.layout}</p>{lastRun.design.equipment.map((e,i)=><p key={i}>{e.name} × {e.count}：{e.features.join('、')}</p>)}<p>检查标准：{lastRun.design.checks.join('；')}</p>{lastRun.design.composition&&<><p>分区：{lastRun.design.composition.zones.map(z=>z.name+'：'+z.purpose).join('；')}</p><p>连接：{lastRun.design.composition.connections.map(c=>c.from+' → '+c.to+'（'+c.via+'）').join('；')}</p><p>配套：{lastRun.design.composition.support.map(e=>e.name+' × '+e.count+'：'+e.purpose).join('；')}</p><p>观感：{lastRun.design.composition.palette.join('、')}；{lastRun.design.composition.presentation}</p></>}</div></details>}
 {!!lastRun.objectBlueprints?.length&&<details className="task-section"><summary>对象结构与细节档位 · {lastRun.objectBlueprints.length} 类</summary><div className="task-events"><p>用途与结构方案，关联部件不代表质量验收通过。</p>{lastRun.objectBlueprints.map(b=><details key={b.key}><summary>{b.name} · {{closeup:'关键近景',scene:'场景主体',background:'背景配套'}[b.detailLevel]}</summary><p>用途：{b.purpose}</p><p>轮廓：{b.silhouette}</p><p>细节安排：{b.detailReason}</p>{b.features.map(f=><p key={f.key}>{f.name} · {f.geometryApproach}</p>)}{!!b.negativeSpaces.length&&<p>开口与负空间：{b.negativeSpaces.join('；')}</p>}</details>)}{lastRun.blueprintCoverage?.issues.map((x,i)=><p key={i}>{x}</p>)}</div></details>}
 {!!lastRun.repairQueue?.total&&<details className="task-section"><summary>质量修复清单 · {lastRun.repairQueue.total} 项</summary><div className="task-events"><p>明确缺陷优先修复；缺证据、渲染受限和重试未通过分别保留。</p>{lastRun.repairQueue.items.map((x,i)=><p key={i}>{{repair:'待修复',inspect:'待补证据',blocked:'验证受限',deferred:'暂停重试'}[x.action]} · {lastRun.detailAcceptance?.targets.find(t=>t.id===x.componentId)?.name??x.componentId}：{x.reason}<br/>{x.next}</p>)}{!!lastRun.repairQueue.remaining&&<p>另有 {lastRun.repairQueue.remaining} 项；仍未验收。</p>}</div></details>}
 {lastRun.detailAcceptance&&<details className="task-section"><summary>细节验收 · {{not_required:'本轮无需重验',pending:'待验收',needs_work:'未达标',self_reviewed:'已自检，待人工确认'}[lastRun.detailAcceptance.status]}</summary><div className="task-events"><p>外形比例、功能结构、连接接触、材质表面、用途相关细节、完整性与环境关系。适用于所有模型。</p><p>检查版本 {lastRun.detailAcceptance.revision}{(pendingResult?.doc.revision??doc.revision)!==lastRun.detailAcceptance.revision?' · 已过期，需重新检查':''}</p>{lastRun.detailAcceptance.issues.map((x,i)=><p key={i}>{x}</p>)}{lastRun.detailAcceptance.reviews.map(r=><details key={r.componentId}><summary>{lastRun.detailAcceptance?.targets.find(t=>t.id===r.componentId)?.name}</summary>{r.reusedCriteria?.length&&<p>部分依据复用自先前检查，对应对象及已核对依赖未改；失效项目另行复查。</p>}{r.checks.map(c=><p key={c.criterion}>{DETAIL_CRITERIA.find(x=>x.key===c.criterion)?.name??c.criterion} · {{pass:'自检通过',fail:'未达标',unknown:'待核对',not_applicable:'不适用'}[c.status]}{r.reusedCriteria?.includes(c.criterion)?`（依据版本 ${r.criterionEvidence?.[c.criterion]??r.evidenceRevision}）`:''}：{c.evidence}</p>)}</details>)}<p>模型自检不等于人工验收，不按零件数量评分。</p></div></details>}
 {lastRun.quality&&<details className="task-section"><summary>场景检查 · {lastRun.quality.issues.length} 项待核对</summary><div className="task-events"><p>检查版本 {lastRun.quality.revision} · {lastRun.quality.componentCount} 个组件{(pendingResult?.doc.revision??doc.revision)!==lastRun.quality.revision?' · 场景已变化，检查可能已过期':''}</p>{lastRun.quality.coverage.map((c,i)=><p key={i}>{c.name}：已关联 {c.actual} / 计划 {c.expected}</p>)}{lastRun.quality.issues.map((issue,i)=><p key={i}>{issue}</p>)}<p>仅为清单和几何线索，仍需核对画面与工艺合理性</p></div></details>}
 <div className="task-section"><h3>执行时间线</h3>{lastRun.timings.length?lastRun.timings.map(t=><div className="task-timeline-item" key={t.id}>{t.failed?<CrossCircledIcon color="#e69f95"/>:t.endedAt!==undefined?<CheckCircledIcon/>:<ClockIcon/>}<div><strong>{t.label}</strong><span>{((Math.max(t.endedAt??(busy?now:lastRun.lastEventAt),t.startedAt)-t.startedAt)/1000).toFixed(1)} 秒 · {t.failed?'失败':t.endedAt!==undefined?'已结束':busy?'进行中':'已中断'}</span></div></div>):<p>暂未记录耗时</p>}</div>
 <details className="task-section"><summary>详细活动 · {lastRun.events.length} 条</summary><div className="task-events">{lastRun.events.map((event,i)=><p key={i}>{event}</p>)}</div></details></>}
 {!busy&&(lastRun||latestRun)&&<button onClick={exportDiagnostics}>下载脱敏诊断记录</button>}
 <div className="task-section"><h3>逐轮执行历史</h3>{runs.map(m=><details key={m.id} className="mt-2"><summary className="cursor-pointer text-sm">{m.text.slice(0,90)}</summary><RunTrace run={m.run!} now={now}/></details>)}</div>
 <div className="task-section"><h3>本会话的修改记录 <span>{outcomes.length}</span></h3>{outcomes.length?outcomes.map(m=><div className="task-outcome" key={m.id}><span className={`outcome-label ${m.outcome??'preview'}`}>{m.outcome==='applied'?'已应用':m.outcome==='discarded'?'已放弃':m.outcome==='superseded'?'已合并到后续预览':pendingBatch?.requestId===m.batch?.requestId?'待确认':'预览已结束'}</span><p>{m.batch?.summary||m.text}</p><small>{m.batch?.operations.length} 项操作 · {new Date(m.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></div>):<p className="task-footnote">还没有场景修改记录。完成一次生成后会在这里显示</p>}</div>
 </section>;
}
