import {createServer} from 'vite';import {chromium} from 'playwright-core';import fs from 'node:fs';import assert from 'node:assert/strict';
const server=await createServer({server:{port:4173,host:'127.0.0.1',strictPort:true},appType:'spa'});await server.listen();const browser=await chromium.launch({headless:true});const out='home-visual-results';fs.mkdirSync(out,{recursive:true});const errors=[];
try{const page=await browser.newPage({viewport:{width:1920,height:1024}});page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:4173/tests/visual/home.html');await page.getByRole('button',{name:'打开首页任务 机加车间沙盘'}).waitFor();await page.screenshot({path:`${out}/home-active-1920.png`,fullPage:true});
 assert.equal(await page.locator('.home-task-row').count(),2);assert.equal(await page.locator('.home-featured').count(),0);assert.equal(await page.locator('.home-prompt-shortcuts').count(),0);
 const measurements=await page.locator('.navigation-utilities').evaluate(e=>({width:e.getBoundingClientRect().width,buttons:[...e.querySelectorAll('button')].map(b=>({label:b.getAttribute('aria-label'),x:b.getBoundingClientRect().x,width:b.getBoundingClientRect().width}))}));
 const buttons=measurements.buttons;for(let i=1;i<buttons.length;i++)assert.ok(buttons[i].x>=buttons[i-1].x+buttons[i-1].width+5,'Header buttons overlap');
 await page.getByRole('button',{name:'查看全部任务',exact:true}).click();await page.getByRole('dialog',{name:'任务队列'}).waitFor();await page.screenshot({path:`${out}/task-drawer.png`});await page.getByRole('button',{name:'关闭任务队列'}).click();
 await page.getByRole('button',{name:'打开首页任务 机加车间沙盘'}).click();assert.equal(await page.getByRole('textbox',{name:'建模指令'}).inputValue(),'运行中保留的草稿');await page.getByRole('button',{name:'任务',exact:true}).click();await page.getByRole('dialog',{name:'任务队列'}).waitFor();await page.screenshot({path:`${out}/workbench-task-switch.png`});await page.getByRole('button',{name:'关闭任务队列'}).click();
 await page.getByRole('button',{name:'资产库',exact:true}).click();await page.getByRole('complementary',{name:'分类导航'}).waitFor();await page.screenshot({path:`${out}/asset-category.png`});
 const category=await page.locator('.library-category-tree button[aria-pressed=true]').evaluate(e=>({border:getComputedStyle(e).borderTopWidth,textAlign:getComputedStyle(e).textAlign}));assert.equal(category.border,'0px');assert.equal(category.textAlign,'left');
 await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('heading',{name:'设置',exact:true}).waitFor();await page.screenshot({path:`${out}/settings.png`,fullPage:true});assert.equal(await page.getByRole('button',{name:'任务',exact:true}).textContent(),'1');
 await page.getByRole('button',{name:'管理项目备份'}).click();await page.getByRole('heading',{name:'备份与恢复',exact:true}).waitFor();assert.equal(await page.getByText('使用与验收',{exact:true}).count(),0);await page.screenshot({path:`${out}/settings-backup.png`});await page.getByRole('button',{name:'关闭备份与恢复'}).click();
 await page.getByRole('button',{name:'模型配置',exact:true}).click();await page.getByRole('heading',{name:'连接模型服务'}).waitFor();await page.screenshot({path:`${out}/settings-model.png`});await page.getByRole('button',{name:'关闭模型配置'}).click();
 await page.getByRole('button',{name:'管理项目',exact:true}).click();await page.getByRole('heading',{name:'项目与回收站'}).waitFor();await page.screenshot({path:`${out}/settings-history.png`});await page.keyboard.press('Escape');await page.getByRole('heading',{name:'设置',exact:true}).waitFor();
 await page.getByRole('combobox',{name:'应用外观'}).click();await page.getByRole('option',{name:'深色',exact:true}).click();await page.screenshot({path:`${out}/settings-dark.png`});await page.getByRole('combobox',{name:'应用外观'}).click();await page.getByRole('option',{name:'浅色',exact:true}).click();await page.setViewportSize({width:700,height:900});await page.screenshot({path:`${out}/settings-narrow.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 await page.getByRole('button',{name:'首页',exact:true}).click();await page.setViewportSize({width:1100,height:800});await page.screenshot({path:`${out}/home-active-1100.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 fs.writeFileSync(`${out}/result.json`,JSON.stringify({passed:true,measurements,category,errors,limitations:'Controlled layout fixture, no model calls or real running tasks'},null,2));assert.deepEqual(errors,[]);
}finally{await browser.close();await server.close()}
