import {validateImageDataUrl,type TextureMap,type TextureMaps} from '../domain/textures';
function base64(bytes:Uint8Array){let s='';for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(s);}
export function prepareGlbTextures(json:any,bin:Uint8Array|undefined){
 const images:string[]=[];let total=0;
 for(const image of json.images??[]){if(image.uri||!Number.isInteger(image.bufferView)||!['image/png','image/jpeg'].includes(image.mimeType))throw Error('GLB贴图需使用内嵌PNG/JPEG缓冲，不能引用外部图片');const v=json.bufferViews?.[image.bufferView];if(!bin||!v||v.buffer!==0||!Number.isInteger(v.byteLength)||v.byteLength<=0||v.byteLength>2*1024*1024||!Number.isInteger(v.byteOffset??0)||(v.byteOffset??0)<0||(v.byteOffset??0)+v.byteLength>bin.length)throw Error('贴图缓冲范围无效');total+=v.byteLength;if(total>8*1024*1024)throw Error('GLB贴图总量超过8MB');const url='data:'+image.mimeType+';base64,'+base64(bin.subarray(v.byteOffset??0,(v.byteOffset??0)+v.byteLength));validateImageDataUrl(url);images.push(url);}
 for(const t of json.textures??[])if(!Number.isInteger(t.source)||!images[t.source])throw Error('GLB贴图引用无效');
 const texture=(info:any):TextureMap|undefined=>{if(!info)return;const tex=json.textures?.[info.index];if(!tex||!images[tex.source])throw Error('材质贴图引用无效');if((info.texCoord??0)!==0)throw Error('当前只导入第一套UV坐标');const sampler=json.samplers?.[tex.sampler]??{},tr=info.extensions?.KHR_texture_transform??{};if((tr.texCoord??0)!==0)throw Error('当前只导入第一套UV坐标');const wrap=(v:number|undefined)=>v===33071?'clamp' as const:v===33648?'mirror' as const:'repeat' as const;return {dataUrl:images[tex.source],repeat:tr.scale??[1,1],offset:tr.offset??[0,0],rotation:tr.rotation??0,wrapS:wrap(sampler.wrapS),wrapT:wrap(sampler.wrapT)};};
 const materials=(json.materials??[]).map((m:any)=>{for(const extension of Object.values(m.extensions??{}))if(extension&&typeof extension==='object'&&Object.keys(extension).some(k=>/Texture$/.test(k)))throw Error('当前暂不导入高级材质扩展中的贴图，请烘焙为标准PBR贴图');const maps:TextureMaps={};for(const [key,info] of [['baseColor',m.pbrMetallicRoughness?.baseColorTexture],['normal',m.normalTexture],['roughness',m.pbrMetallicRoughness?.metallicRoughnessTexture],['metalness',m.pbrMetallicRoughness?.metallicRoughnessTexture],['emissive',m.emissiveTexture],['occlusion',m.occlusionTexture]] as const){const t=texture(info);if(t)maps[key]=t;}return {maps,normalScale:m.normalTexture?.scale??1};});
 const clean=structuredClone(json);delete clean.images;delete clean.textures;delete clean.samplers;clean.extensionsRequired=(clean.extensionsRequired??[]).filter((x:string)=>x!=='KHR_texture_transform');
 for(const m of clean.materials??[]){for(const key of ['normalTexture','emissiveTexture','occlusionTexture'])delete m[key];if(m.pbrMetallicRoughness){delete m.pbrMetallicRoughness.baseColorTexture;delete m.pbrMetallicRoughness.metallicRoughnessTexture;}}
 return {materials,clean};
}
export function packGlb(json:any,bin?:Uint8Array):ArrayBuffer {const raw=new TextEncoder().encode(JSON.stringify(json)),len=Math.ceil(raw.length/4)*4,binary=bin?Math.ceil(bin.length/4)*4:0,data=new ArrayBuffer(20+len+(bin?8+binary:0)),v=new DataView(data),bytes=new Uint8Array(data);v.setUint32(0,0x46546c67,true);v.setUint32(4,2,true);v.setUint32(8,data.byteLength,true);v.setUint32(12,len,true);v.setUint32(16,0x4e4f534a,true);bytes.fill(32,20,20+len);bytes.set(raw,20);if(bin){v.setUint32(20+len,binary,true);v.setUint32(24+len,0x004e4942,true);bytes.set(bin,28+len);}return data;}
