import {refinePersonInteraction,type InteractionStyle} from './personInteraction';
import {Matrix4,Quaternion,Vector3} from 'three';
import {importGlb} from './importGlb';
import type {SceneNode,Material,Vec3,Quaternion as Q,SceneRole} from '../domain/types';
export const MESH_CATALOG=[{"key": "vmc", "name": "立式加工中心", "role": "equipment", "parts": 145, "size": [2.935, 2.542, 1.92], "front": "+Z", "features": "空腔防护壳、滑门/观察窗、主轴、夹具、T槽、密集HMI按键、手轮、急停、通风/塔灯、背部检修门/铰链/锁扣/百叶", "queryHints": ["pendant", "keypad", "spindle", "vice"]}, {"key": "hmc", "name": "卧式加工中心", "role": "equipment", "parts": 63, "size": [3.47, 2.635, 2.1], "front": "+Z", "features": "水平主轴、回转托盘、夹具塔、独立刀库/刀位、控制台", "queryHints": ["controller", "quill", "tombstone"]}, {"key": "gantry", "name": "龙门加工中心", "role": "equipment", "parts": 94, "size": [5.58, 3.56, 3.0], "front": "+Z", "features": "双立柱跨梁、导轨与伸缩护罩、拖链、主轴、长工作台和夹具", "queryHints": ["controller", "spindle", "clamp"]}, {"key": "cmm", "name": "三坐标检测工位", "role": "equipment", "parts": 28, "size": [4.05, 2.21, 1.8], "front": "+Z", "features": "花岗石台、桥架、Z测杆/红宝石测头、隔振脚、空气轴承、检测终端", "queryHints": ["probe", "monitor", "desk"]}, {"key": "cleaning", "name": "多槽清洗设备", "role": "equipment", "parts": 42, "size": [2.51, 1.878, 1.21], "front": "+Z", "features": "三槽清洗、独立开启槽盖、篮筐、控制按钮", "queryHints": ["controls", "tank", "basket"]}, {"key": "grinding", "name": "打磨除尘工位", "role": "equipment", "parts": 37, "size": [3.28, 2.255, 1.18], "front": "+Z", "features": "砂轮与眼部防护、工件托架、下吸工作台、挡板和集尘管道", "queryHints": ["motor", "wheel", "work rest"]}, {"key": "packing", "name": "装箱工位", "role": "workstation", "parts": 36, "size": [3.95, 1.714, 1.1], "front": "+Z", "features": "工作台、开启箱盖、封箱工具及滚筒输送段", "queryHints": ["bench", "tape", "roller"]}, {"key": "rack", "name": "仓储货架", "role": "storage", "parts": 27, "size": [2.685, 3.1, 1.045], "front": "+Z", "features": "立柱/横梁/层板货架（空架，需按需求放置物料）", "queryHints": ["shelf", "upright"]}, {"key": "production-worker", "name": "生产人员", "role": "person", "parts": 24, "size": [0.599, 1.755, 0.61], "front": "-Z", "features": "蓝色工装、帽子、自然身体轮廓、弯曲操作手臂、手指", "queryHints": ["hand", "fingers", "torso", "tablet", "scanner", "tape"]}, {"key": "quality-worker", "name": "质检人员", "role": "person", "parts": 27, "size": [0.599, 1.755, 0.61], "front": "-Z", "features": "浅色工装、检测终端与卡尺", "queryHints": ["hand", "fingers", "torso", "tablet", "scanner", "tape"]}, {"key": "warehouse-worker", "name": "仓管员", "role": "person", "parts": 27, "size": [0.599, 1.755, 0.62], "front": "-Z", "features": "绿色工装、手持扫码器", "queryHints": ["hand", "fingers", "torso", "tablet", "scanner", "tape"]}, {"key": "packing-worker", "name": "打包人员", "role": "person", "parts": 27, "size": [0.599, 1.755, 0.63], "front": "-Z", "features": "橙色工装、封箱胶带枪", "queryHints": ["hand", "fingers", "torso", "tablet", "scanner", "tape"]}] as const;
export interface MeshPlacement {key:string;name:string;position:Vec3;yaw?:number;scaleFactor?:number;planKey?:string;zone?:string}
const bytesCache=new Map<string,ArrayBuffer>();
export async function loadMeshComponent(args:MeshPlacement,signal?:AbortSignal,fetcher:typeof fetch=fetch):Promise<{nodes:SceneNode[];materials:Material[]}>{
 const entry=MESH_CATALOG.find(x=>x.key===args.key);if(!entry)throw Error('不存在的精细模型');
 if(!args.name?.trim()||args.name.length>80||!Array.isArray(args.position)||args.position.length!==3||args.position.some(x=>!Number.isFinite(x)||Math.abs(x)>10000)||!Number.isFinite(args.yaw??0)||!Number.isFinite(args.scaleFactor??1)||(args.scaleFactor??1)<.1||(args.scaleFactor??1)>10)throw Error('模型名称、位置、角度或比例无效');
 if(signal?.aborted)throw new DOMException('已停止','AbortError');
 let data=bytesCache.get(entry.key);
 if(!data){const response=await fetcher('/model-assets/'+entry.key+'.glb',{signal});if(!response.ok)throw Error('精细模型载入失败，请稍后重试');data=await response.arrayBuffer();bytesCache.set(entry.key,data);}
 if(signal?.aborted)throw new DOMException('已停止','AbortError');
 const {doc}=await importGlb(data,args.name);
 const styles:Record<string,InteractionStyle>={'production-worker':'operate','quality-worker':'inspect','warehouse-worker':'scan','packing-worker':'pack'};
 // Upgrade only newly loaded assets; existing user geometry is not silently replaced.
 if(styles[entry.key]){for(const n of doc.nodes)n.name=(n.name.startsWith(args.name+' · ')?n.name:args.name+' · '+n.name.replace(/^.*?\|_?/, '').replace(/_/g,' ').trim());doc.nodes=refinePersonInteraction(doc.nodes,styles[entry.key]).nodes;}
 const q=new Quaternion().setFromAxisAngle(new Vector3(0,1,0),(args.yaw??0)*Math.PI/180),factor=args.scaleFactor??1;
 const root=new Matrix4().compose(new Vector3(...args.position),q,new Vector3(factor,factor,factor));
 const group=doc.nodes[0].assemblyId!;for(const n of doc.nodes){const p=new Vector3(),r=new Quaternion(),s=new Vector3();const m=new Matrix4().compose(new Vector3(...n.transform.position),new Quaternion(...n.transform.rotationQuaternion),new Vector3(...n.transform.scale)).premultiply(root);m.decompose(p,r,s);n.transform={position:p.toArray() as Vec3,rotationQuaternion:r.normalize().toArray() as Q,scale:s.toArray() as Vec3};n.assemblyId=group;n.assemblyName=args.name;n.sceneRole=entry.role as SceneRole;n.planKey=args.planKey;n.zone=args.zone;n.name=(n.name.startsWith(args.name+' · ')?n.name:args.name+' · '+n.name.replace(/^.*?\|_?/, '').replace(/_/g,' ').trim());}
 const used=new Set(doc.nodes.map(n=>n.materialId));return {nodes:doc.nodes,materials:doc.materials.filter(m=>used.has(m.id))};
}
