import * as THREE from 'three';import type {SurfaceDetail,TextureMap} from '../domain/textures';import {validateImageDataUrl} from '../domain/textures';
export const materialReady=new WeakMap<THREE.Material,Promise<void>>();
const pixelCache=new Map<string,{normal:Uint8Array;rough:Uint8Array}>();
export function proceduralMaps(s:SurfaceDetail){let pixels=pixelCache.get(s.preset);const N=128;if(!pixels){const normal=new Uint8Array(N*N*4),rough=new Uint8Array(N*N*4);const height=(x:number,y:number)=>{const a=Math.sin(x*12.9898+y*78.233)*43758.5453,n=a-Math.floor(a);switch(s.preset){case 'brushed_metal':return .35*Math.sin(y*1.6)+n*.09;case 'fabric':return .22*(Math.sin(x*1.6)+Math.sin(y*1.6));case 'wood':return .3*Math.sin(y*.24+Math.sin(x*.035)*2)+n*.05;case 'rubber':return n*.12;case 'powder_coat':return n*.07;default:return n*.20;}};for(let y=0;y<N;y++)for(let x=0;x<N;x++){const i=(y*N+x)*4,h=height(x,y),dx=height(x+1,y)-h,dy=height(x,y+1)-h;normal.set([128-dx*70,128-dy*70,250,255],i);const r=Math.max(0,Math.min(255,190+h*55));rough.set([r,r,r,255],i);}pixels={normal,rough};pixelCache.set(s.preset,pixels);}const make=(data:Uint8Array)=>{const t=new THREE.DataTexture(data,N,N,THREE.RGBAFormat);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(...s.repeat);t.magFilter=THREE.LinearFilter;t.minFilter=THREE.LinearMipmapLinearFilter;t.generateMipmaps=true;t.needsUpdate=true;return t;};return {normal:make(pixels.normal),rough:make(pixels.rough)};}
const images=new Map<string,Promise<HTMLImageElement>>();
export function embeddedTexture(t:TextureMap,color:boolean){validateImageDataUrl(t.dataUrl);const texture=new THREE.Texture();texture.colorSpace=color?THREE.SRGBColorSpace:THREE.NoColorSpace;const wrap={repeat:THREE.RepeatWrapping,clamp:THREE.ClampToEdgeWrapping,mirror:THREE.MirroredRepeatWrapping};texture.wrapS=wrap[t.wrapS??'repeat'];texture.wrapT=wrap[t.wrapT??'repeat'];texture.repeat.set(...(t.repeat??[1,1]));texture.offset.set(...(t.offset??[0,0]));texture.rotation=t.rotation??0;texture.flipY=false;
 let promise=images.get(t.dataUrl);if(!promise){promise=new Promise<HTMLImageElement>((resolve,reject)=>{if(typeof Image==='undefined'){reject(Error('当前环境无法解码图片贴图'));return;}const image=new Image();image.onload=()=>{if(image.width>2048||image.height>2048)reject(Error('贴图分辨率超出限制'));else resolve(image);};image.onerror=()=>reject(Error('贴图图片解码失败'));image.src=t.dataUrl;});images.set(t.dataUrl,promise);if(images.size>32)images.delete(images.keys().next().value!);}
 const ready=promise.then(image=>{texture.image=image;texture.needsUpdate=true;});return {texture,ready};
}
export function disposeMaterialTextures(m:THREE.Material){const material=m as THREE.MeshStandardMaterial;for(const key of ['map','normalMap','roughnessMap','metalnessMap','emissiveMap','aoMap'] as const)material[key]?.dispose();m.dispose();}
