import fs from 'node:fs';import {pathToFileURL} from 'node:url';
const valid=n=>typeof n==='number'&&Number.isFinite(n)&&n>=0;
const sum=xs=>xs.reduce((a,b)=>a+b,0);
export function analyzeRun(document){
 if(document?.format!=='chat3d-diagnostics-v1'||!document.run||!Array.isArray(document.run.timings))throw Error('Expected a Chat3D diagnostics run');
 const run=document.run,rows=run.timings,closed=rows.filter(t=>valid(t.startedAt)&&valid(t.endedAt)&&t.endedAt>=t.startedAt),model=closed.filter(t=>t.kind==='model'),tools=closed.filter(t=>t.kind==='tool');
 const durations=rs=>rs.map(t=>(t.endedAt-t.startedAt)/1000);const modelSeconds=sum(durations(model)),toolSeconds=sum(durations(tools));
 const wallSeconds=closed.length?(Math.max(...closed.map(t=>t.endedAt))-Math.min(...closed.map(t=>t.startedAt)))/1000:null;
 const groups=new Map();for(const t of tools){const name=typeof t.toolName==='string'&&/^[a-z][a-z0-9_]{0,63}$/.test(t.toolName)?t.toolName:'unrecorded';const g=groups.get(name)??{tool:name,calls:0,seconds:0,failed:0,repeatedInputs:0,maxResultChars:0};g.calls++;g.repeatedInputs+=t.repeatedInput===true?1:0;g.seconds+=(t.endedAt-t.startedAt)/1000;g.failed+=t.failed===true?1:0;g.maxResultChars=Math.max(g.maxResultChars,valid(t.resultChars)?t.resultChars:0);groups.set(name,g);}
 const usageUnknown=rows.filter(t=>t.kind==='model'&&(t.usageState==='unknown'||(!t.usageState&&!(t.inputTokens>0||t.outputTokens>0)))).length;
 const footprints=model.map(t=>t.requestFootprint).filter(Boolean);const maxField=k=>Math.max(0,...footprints.map(f=>valid(f[k])?f[k]:0));
 return {schema:'chat3d-run-analysis-v1',executionMeta:run.executionMeta?{appVersion:run.executionMeta.appVersion,buildCommit:run.executionMeta.buildCommit,contextPolicy:run.executionMeta.contextPolicy}:undefined,wallSeconds,modelSeconds,toolSeconds,modelRequests:rows.filter(t=>t.kind==='model').length,toolCalls:rows.filter(t=>t.kind==='tool').length,unfinishedTimings:rows.length-closed.length,failedTimings:rows.filter(t=>t.failed===true).length,usageUnknown,usageIncomplete:!!run.usageIncomplete||usageUnknown>0,reportedInputTokens:valid(run.inputTokens)?run.inputTokens:null,reportedOutputTokens:valid(run.outputTokens)?run.outputTokens:null,requestWindowOutputTokensPerSecond:modelSeconds&&valid(run.outputTokens)?run.outputTokens/modelSeconds:null,peak:{toolResultChars:maxField('toolResultChars'),toolSchemaChars:maxField('toolSchemaChars'),systemChars:maxField('systemChars'),imageCount:maxField('imageCount'),serializedChars:maxField('totalSerializedChars')},tools:[...groups.values()].sort((a,b)=>b.maxResultChars-a.maxResultChars),limits:['Elapsed span covers recorded closed timings only.','Summed durations can overlap if the source includes parallel work.','Request-window throughput includes request/network/wait time; it is not decode speed.','Characters and image base64 size are not token counts.','Different tasks, services or versions are not a controlled performance comparison.']};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){try{const path=process.argv[2];if(!path)throw Error('Usage: node scripts/analyze-run.mjs diagnostics.json');if(fs.statSync(path).size>50*1024*1024)throw Error('Input exceeds 50 MiB');console.log(JSON.stringify(analyzeRun(JSON.parse(fs.readFileSync(path,'utf8'))),null,2));}catch(e){console.error(e.message);process.exitCode=1;}}
